import type { VocabItem } from '@/types/content';
import { pack, w } from '../shared/helpers';

/**
 * Vocabulary for the Arabic-connection feature.
 *
 * These are ordinary curriculum words in ordinary categories and levels — the
 * only thing that distinguishes them is that `ARABIC_CONNECTIONS` has
 * something true to say about each one. Keeping them here rather than
 * scattered across the level files makes the set maintainable; keeping them
 * as plain `VocabItem`s means they show up in the vocabulary explorer, the
 * SRS deck, favourites, search, listening and exercises with no special
 * handling anywhere.
 *
 * Words already present elsewhere in the curriculum are NOT repeated here —
 * the connection map decorates those in place.
 */

/* ------------------------------------------------------------------ */
/* A1 — the first words an Arabic reader recognises                    */
/* ------------------------------------------------------------------ */

const A1_LINKS: VocabItem[] = [
  ...pack('greetings', 'a1', 'interjection', [
    w('merhaba', 'mer-ha-BA', 'مرحباً', 'سڵاو',
      ['Merhaba, nasılsın?', 'mer-ha-BA na-sıl-SIN', 'مرحباً، كيف حالك؟', 'سڵاو، چۆنی؟']),
    w('selam', 'se-LAM', 'سلام، تحية', 'سڵاو',
      ['Arkadaşlarıma selam söyle.', 'ar-ka-daş-la-rı-MA se-LAM söy-LE', 'بلّغ سلامي لأصدقائي.', 'سڵاوم لە هاوڕێکانم بگەیەنە.']),
    w('teşekkür', 'te-şek-KÜR', 'شكر', 'سوپاس',
      ['Yardımın için teşekkür ederim.', 'yar-dı-MIN i-ÇİN te-şek-KÜR e-de-RİM', 'أشكرك على مساعدتك.', 'سوپاس بۆ یارمەتیت.']),
    w('rica', 'ri-CA', 'رجاء، طلب مهذّب', 'داواکاری',
      ['Bir ricam var.', 'BİR ri-CAM var', 'عندي طلب.', 'داواکارییەکم هەیە.']),
  ]),
  ...pack('time', 'a1', 'noun', [
    w('dakika', 'da-ki-KA', 'دقيقة', 'خولەک',
      ['Beş dakika bekle.', 'BEŞ da-ki-KA bek-LE', 'انتظر خمس دقائق.', 'پێنج خولەک چاوەڕێ بکە.']),
    w('saniye', 'sa-ni-YE', 'ثانية', 'چرکە',
      ['Bir saniye lütfen.', 'BİR sa-ni-YE lüt-FEN', 'ثانية من فضلك.', 'چرکەیەک تکایە.']),
    w('sene', 'se-NE', 'سنة', 'ساڵ',
      ['Bu sene Türkiye’ye gidiyorum.', 'BU se-NE tür-ki-YE-ye gi-di-yo-RUM', 'هذه السنة أسافر إلى تركيا.', 'ئەم ساڵە دەچمە تورکیا.']),
    w('tarih', 'ta-RİH', 'تاريخ، موعد', 'مێژوو، ڕێکەوت',
      ['Bugünün tarihi nedir?', 'bu-gü-NÜN ta-ri-Hİ ne-DİR', 'ما تاريخ اليوم؟', 'ڕێکەوتی ئەمڕۆ چییە؟']),
    w('vakit', 'va-KİT', 'وقت', 'کات',
      ['Vaktim yok.', 'vak-TİM YOK', 'ليس لديّ وقت.', 'کاتم نییە.']),
    w('asır', 'a-SIR', 'قرن، عصر', 'سەدە',
      ['Yirminci asırda çok şey değişti.', 'yir-min-Cİ a-sır-DA ÇOK ŞEY de-ğiş-Tİ', 'تغيّر الكثير في القرن العشرين.', 'لە سەدەی بیستەمدا زۆر شت گۆڕا.']),
  ]),
  ...pack('school', 'a1', 'noun', [
    w('harf', 'HARF', 'حرف', 'پیت',
      ['Türkçede yirmi dokuz harf var.', 'türk-çe-DE yir-mi do-KUZ HARF var', 'في التركية تسعة وعشرون حرفاً.', 'لە تورکیدا بیست و نۆ پیت هەیە.']),
  ]),
];

/* ------------------------------------------------------------------ */
/* A2 — everyday Arabic-derived words                                  */
/* ------------------------------------------------------------------ */

const A2_LINKS: VocabItem[] = [
  ...pack('emotions', 'a2', 'noun', [
    w('ruh', 'RUH', 'روح', 'ڕۆح',
      ['Bu şarkının ruhu var.', 'BU şar-kı-nın ru-HU var', 'لهذه الأغنية روح.', 'ئەم گۆرانییە ڕۆحی هەیە.']),
    w('akıl', 'a-KIL', 'عقل', 'عەقڵ',
      ['Aklıma iyi bir fikir geldi.', 'ak-lı-MA i-Yİ bir fi-KİR gel-Dİ', 'خطرت لي فكرة جيدة.', 'بیرۆکەیەکی باشم بۆ هات.']),
    w('hayal', 'ha-YAL', 'خيال، حلم', 'خەیاڵ',
      ['Çocukken büyük hayallerim vardı.', 'ço-cuk-KEN bü-YÜK ha-yal-le-RİM var-DI', 'كانت لي أحلام كبيرة في طفولتي.', 'لە منداڵیدا خەونی گەورەم هەبوو.']),
    w('rüya', 'rü-YA', 'رؤيا، حلم النوم', 'خەون',
      ['Dün gece güzel bir rüya gördüm.', 'DÜN ge-CE gü-ZEL bir rü-YA gör-DÜM', 'رأيت حلماً جميلاً ليلة أمس.', 'دوێنێ شەو خەونێکی جوانم بینی.']),
    w('sabır', 'sa-BIR', 'صبر', 'ئارامگرتن',
      ['Biraz sabır göster.', 'bi-RAZ sa-BIR gös-TER', 'اصبر قليلاً.', 'کەمێک ئارام بگرە.']),
    w('dua', 'du-A', 'دعاء', 'دوعا',
      ['Annem her gün bana dua ediyor.', 'an-NEM HER gün ba-NA du-A e-di-YOR', 'أمي تدعو لي كل يوم.', 'دایکم هەموو ڕۆژێک دوعام بۆ دەکات.']),
  ]),
  ...pack('expressions', 'a2', 'interjection', [
    w('maalesef', 'ma-a-le-SEF', 'مع الأسف، للأسف', 'بەداخەوە',
      ['Maalesef gelemeyeceğim.', 'ma-a-le-SEF ge-le-me-ye-ce-ĞİM', 'للأسف لن أستطيع الحضور.', 'بەداخەوە ناتوانم بێم.']),
    w('elbette', 'el-bet-TE', 'بالتأكيد، طبعاً', 'بێگومان',
      ['Elbette yardım ederim.', 'el-bet-TE yar-DIM e-de-RİM', 'بالتأكيد سأساعد.', 'بێگومان یارمەتی دەدەم.']),
    w('inşallah', 'in-şal-LAH', 'إن شاء الله', 'ئینشاڵڵا',
      ['İnşallah yarın görüşürüz.', 'in-şal-LAH ya-RIN gö-rü-şü-RÜZ', 'إن شاء الله نلتقي غداً.', 'ئینشاڵڵا سبەینێ یەکتر دەبینین.']),
    w('maşallah', 'ma-şal-LAH', 'ما شاء الله', 'ماشاڵڵا',
      ['Maşallah, çok güzel olmuş.', 'ma-şal-LAH ÇOK gü-ZEL ol-MUŞ', 'ما شاء الله، صار جميلاً جداً.', 'ماشاڵڵا، زۆر جوان بووە.']),
    w('vallahi', 'val-la-Hİ', 'والله (قسم)', 'وەڵڵا',
      ['Vallahi bilmiyorum.', 'val-la-Hİ bil-mi-yo-RUM', 'والله لا أعرف.', 'وەڵڵا نازانم.']),
    w('mesela', 'me-se-LA', 'مثلاً', 'بۆ نموونە',
      ['Mesela bu kelimeyi ele alalım.', 'me-se-LA BU ke-li-me-Yİ e-LE a-la-LIM', 'لنأخذ هذه الكلمة مثلاً.', 'بۆ نموونە با ئەم وشەیە وەربگرین.']),
    w('acaba', 'a-ca-BA', 'يا ترى، هل يا ترى', 'عەجەب',
      ['Acaba nerede kaldı?', 'a-ca-BA ne-re-DE kal-DI', 'يا ترى أين تأخّر؟', 'عەجەب لە کوێ مایەوە؟']),
  ]),
  ...pack('house', 'a2', 'noun', [
    w('bina', 'bi-NA', 'بناء، مبنى', 'بینا',
      ['Bu bina çok eski.', 'BU bi-NA ÇOK es-Kİ', 'هذا المبنى قديم جداً.', 'ئەم بینایە زۆر کۆنە.']),
    w('mahalle', 'ma-hal-LE', 'محلّة، حيّ', 'گەڕەک',
      ['Mahallemizde güzel bir park var.', 'ma-hal-le-miz-DE gü-ZEL bir PARK var', 'في حيّنا حديقة جميلة.', 'لە گەڕەکەکەماندا پارکێکی جوان هەیە.']),
    w('sofra', 'sof-RA', 'سفرة، مائدة', 'خوان',
      ['Sofra hazır.', 'sof-RA ha-ZIR', 'المائدة جاهزة.', 'خوان ئامادەیە.']),
    w('tabak', 'ta-BAK', 'طبق، صحن', 'قاپ',
      ['Tabakları yıkadım.', 'ta-bak-la-RI yı-ka-DIM', 'غسلت الصحون.', 'قاپەکانم شوشت.']),
    w('daire', 'da-i-RE', 'شقّة سكنية', 'شوقە',
      ['Üçüncü kattaki dairede oturuyorlar.', 'ü-çün-CÜ kat-ta-Kİ da-i-re-DE o-tu-ru-yor-LAR', 'يسكنون في الشقّة بالطابق الثالث.', 'لە شوقەی نهۆمی سێیەم دەژین.']),
  ]),
  ...pack('places', 'a2', 'noun', [
    w('sahil', 'sa-HİL', 'ساحل', 'کەنار',
      ['Akşamları sahilde yürüyoruz.', 'ak-şam-la-RI sa-hil-DE yü-rü-yo-RUZ', 'نمشي على الساحل مساءً.', 'ئێواران لە کەنار پیاسە دەکەین.']),
    w('mekân', 'me-KÂN', 'مكان', 'شوێن',
      ['Burası çok sevdiğim bir mekân.', 'bu-ra-SI ÇOK sev-di-ĞİM bir me-KÂN', 'هذا مكان أحبّه كثيراً.', 'ئێرە شوێنێکە زۆرم خۆشدەوێت.']),
  ]),
  ...pack('greetings', 'a2', 'noun', [
    w('hediye', 'he-di-YE', 'هدية', 'دیاری',
      ['Anneme bir hediye aldım.', 'an-ne-ME bir he-di-YE al-DIM', 'اشتريت هدية لأمي.', 'دیارییەکم بۆ دایکم کڕی.']),
    w('davet', 'da-VET', 'دعوة', 'بانگهێشت',
      ['Düğün davetini aldın mı?', 'dü-ĞÜN da-ve-ti-Nİ al-DIN mı', 'هل وصلتك دعوة العرس؟', 'بانگهێشتی زەماوەندت پێگەیشت؟']),
    w('ziyaret', 'zi-ya-RET', 'زيارة', 'سەردان',
      ['Hastaneye ziyarete gittik.', 'has-ta-ne-YE zi-ya-re-TE git-TİK', 'ذهبنا لزيارة في المستشفى.', 'بۆ سەردان چووینە نەخۆشخانە.']),
  ]),
  ...pack('adjectives', 'a2', 'adjective', [
    w('hazır', 'ha-ZIR', 'جاهز، مُعدّ', 'ئامادە',
      ['Yemek hazır mı?', 'ye-MEK ha-ZIR mı', 'هل الطعام جاهز؟', 'خواردن ئامادەیە؟']),
    w('meşgul', 'meş-GUL', 'مشغول', 'سەرقاڵ',
      ['Şu an meşgulüm, sonra arayayım.', 'ŞU an meş-gu-LÜM son-RA a-ra-ya-YIM', 'أنا مشغول الآن، سأتصل لاحقاً.', 'ئێستا سەرقاڵم، دواتر پەیوەندی دەکەم.']),
    w('fena', 'fe-NA', 'سيّئ', 'خراپ',
      ['Fena bir fikir değil.', 'fe-NA bir fi-KİR de-ĞİL', 'ليست فكرة سيّئة.', 'بیرۆکەیەکی خراپ نییە.']),
    w('lazım', 'la-ZIM', 'لازم، ضروري', 'پێویست',
      ['Bana biraz para lazım.', 'ba-NA bi-RAZ pa-RA la-ZIM', 'أحتاج بعض المال.', 'کەمێک پارەم پێویستە.']),
  ]),
  ...pack('nouns', 'a2', 'noun', [
    w('hata', 'ha-TA', 'خطأ', 'هەڵە',
      ['Küçük bir hata yaptım.', 'kü-ÇÜK bir ha-TA yap-TIM', 'ارتكبت خطأً صغيراً.', 'هەڵەیەکی بچووکم کرد.']),
    w('sır', 'SIR', 'سرّ', 'نهێنی',
      ['Bu bir sır, kimseye söyleme.', 'BU bir SIR kim-se-YE söy-le-ME', 'هذا سرّ، لا تخبر أحداً.', 'ئەمە نهێنییە، بە کەس مەڵێ.']),
    w('hava', 'ha-VA', 'هواء، طقس، جوّ', 'هەوا',
      ['Bugün hava çok güzel.', 'bu-GÜN ha-VA ÇOK gü-ZEL', 'الطقس جميل جداً اليوم.', 'ئەمڕۆ هەوا زۆر خۆشە.']),
    w('keyif', 'ke-YİF', 'مزاج طيّب، متعة', 'کەیف',
      ['Bugün keyfim yerinde.', 'bu-GÜN key-FİM ye-rin-DE', 'مزاجي جيّد اليوم.', 'ئەمڕۆ کەیفم خۆشە.']),
    w('sohbet', 'soh-BET', 'دردشة، حديث ودّي', 'گفتوگۆ',
      ['Uzun bir sohbet ettik.', 'u-ZUN bir soh-BET et-TİK', 'أجرينا حديثاً طويلاً.', 'گفتوگۆیەکی درێژمان کرد.']),
    w('muhabbet', 'mu-hab-BET', 'دردشة، جلسة ودّية', 'قسەوباس',
      ['Çayla muhabbet daha güzel.', 'çay-LA mu-hab-BET da-HA gü-ZEL', 'الدردشة مع الشاي أجمل.', 'قسەوباس لەگەڵ چا خۆشترە.']),
  ]),
];

/* ------------------------------------------------------------------ */
/* B1 — civic, practical and discourse vocabulary                      */
/* ------------------------------------------------------------------ */

const B1_LINKS: VocabItem[] = [
  ...pack('society', 'b1', 'noun', [
    w('devlet', 'dev-LET', 'دولة', 'دەوڵەت',
      ['Devlet yeni bir yasa çıkardı.', 'dev-LET ye-Nİ bir ya-SA çı-kar-DI', 'أصدرت الدولة قانوناً جديداً.', 'دەوڵەت یاسایەکی نوێی دەرکرد.']),
    w('hükümet', 'hü-kü-MET', 'حكومة', 'حکومەت',
      ['Hükümet yeni bir karar aldı.', 'hü-kü-MET ye-Nİ bir ka-RAR al-DI', 'اتّخذت الحكومة قراراً جديداً.', 'حکومەت بڕیارێکی نوێی دا.']),
    w('vatan', 'va-TAN', 'وطن', 'نیشتمان',
      ['Vatanını çok seviyor.', 'va-ta-nı-NI ÇOK se-vi-YOR', 'يحبّ وطنه كثيراً.', 'نیشتمانەکەی زۆر خۆشدەوێت.']),
    w('halk', 'HALK', 'شعب، ناس', 'گەل',
      ['Halk sokaklara döküldü.', 'HALK so-kak-la-RA dö-kül-DÜ', 'خرج الشعب إلى الشوارع.', 'گەل ڕژایە سەر شەقامەکان.']),
    w('millet', 'mil-LET', 'أمة، شعب', 'نەتەوە',
      ['Bir milletin dili kimliğidir.', 'BİR mil-le-TİN di-Lİ kim-li-ği-DİR', 'لغة الأمة هي هويتها.', 'زمانی نەتەوەیەک ناسنامەیەتی.']),
    w('memleket', 'mem-le-KET', 'بلد، مسقط الرأس', 'وڵات، شوێنی لەدایکبوون',
      ['Yaz tatilinde memlekete gidiyorum.', 'YAZ ta-ti-lin-DE mem-le-ke-TE gi-di-yo-RUM', 'أسافر إلى بلدتي في عطلة الصيف.', 'لە پشووی هاویندا دەچمە وڵاتەکەم.']),
  ]),
  ...pack('work', 'b1', 'noun', [
    w('karar', 'ka-RAR', 'قرار', 'بڕیار',
      ['Zor bir karar verdim.', 'ZOR bir ka-RAR ver-DİM', 'اتّخذت قراراً صعباً.', 'بڕیارێکی سەختم دا.']),
    w('kabul', 'ka-BUL', 'قبول، موافقة', 'قبووڵکردن',
      ['Teklifi kabul etti.', 'tek-li-Fİ ka-BUL et-Tİ', 'قبل العرض.', 'پێشنیارەکەی قبووڵ کرد.']),
    w('talep', 'ta-LEP', 'طلب', 'داواکاری',
      ['Talebiniz değerlendiriliyor.', 'ta-le-bi-NİZ de-ğer-len-di-ri-li-YOR', 'يجري النظر في طلبكم.', 'داواکارییەکەتان هەڵدەسەنگێنرێت.']),
    w('hizmet', 'hiz-MET', 'خدمة', 'خزمەت',
      ['Bu şirket iyi hizmet veriyor.', 'BU şir-KET i-Yİ hiz-MET ve-ri-YOR', 'تقدّم هذه الشركة خدمة جيدة.', 'ئەم کۆمپانیایە خزمەتی باش پێشکەش دەکات.']),
    w('vazife', 'va-zi-FE', 'واجب، مهمّة', 'ئەرک',
      ['Bu benim vazifem.', 'BU be-NİM va-zi-FEM', 'هذا واجبي.', 'ئەمە ئەرکی منە.']),
    w('sahip', 'sa-HİP', 'صاحب، مالك', 'خاوەن',
      ['Dükkânın sahibi kim?', 'dük-kâ-NIN sa-hi-Bİ KİM', 'من صاحب المحل؟', 'خاوەنی دووکانەکە کێیە؟']),
    w('ücret', 'üc-RET', 'أجرة، رسم', 'کرێ',
      ['Giriş ücreti ne kadar?', 'gi-RİŞ üc-re-Tİ NE ka-dar', 'كم رسم الدخول؟', 'کرێی چوونەژوورەوە چەندە؟']),
  ]),
  ...pack('school', 'b1', 'noun', [
    w('fikir', 'fi-KİR', 'فكرة، رأي', 'بیرۆکە',
      ['Bu konuda ne fikirdesin?', 'BU ko-nu-DA NE fi-kir-de-SİN', 'ما رأيك في هذا الموضوع؟', 'لەم بارەیەوە چ بیرۆکەیەکت هەیە؟']),
    w('hesap', 'he-SAP', 'حساب', 'حساب',
      ['Hesabı ben ödeyeceğim.', 'he-sa-BI BEN ö-de-ye-ce-ĞİM', 'سأدفع الحساب أنا.', 'من حسابەکە دەدەم.']),
    w('rakam', 'ra-KAM', 'رقم', 'ژمارە',
      ['Bu rakamlar doğru mu?', 'BU ra-kam-LAR doğ-RU mu', 'هل هذه الأرقام صحيحة؟', 'ئەم ژمارانە ڕاستن؟']),
    w('fiil', 'fi-İL', 'فعل', 'کردار',
      ['Bu cümlede fiil sonda gelir.', 'BU cüm-le-DE fi-İL son-DA ge-LİR', 'الفعل في هذه الجملة يأتي في النهاية.', 'لەم ڕستەیەدا کردار لە کۆتاییدا دێت.']),
    w('sıfat', 'sı-FAT', 'صفة', 'ئاوەڵناو',
      ['Sıfat isimden önce gelir.', 'sı-FAT i-sim-DEN ön-CE ge-LİR', 'الصفة تسبق الاسم.', 'ئاوەڵناو پێش ناو دێت.']),
    w('zamir', 'za-MİR', 'ضمير', 'جێناو',
      ['Ben, sen, o birer zamirdir.', 'BEN SEN O bi-RER za-mir-DİR', 'أنا، أنت، هو ضمائر.', 'من، تۆ، ئەو جێناون.']),
    w('edat', 'e-DAT', 'أداة، حرف', 'ئامراز',
      ['Türkçede edatlar isimden sonra gelir.', 'türk-çe-DE e-dat-LAR i-sim-DEN son-RA ge-LİR', 'الأدوات في التركية تأتي بعد الاسم.', 'لە تورکیدا ئامرازەکان دوای ناو دێن.']),
    w('misal', 'mi-SAL', 'مثال', 'نموونە',
      ['Bir misal verebilir misiniz?', 'BİR mi-SAL ve-re-bi-LİR mi-si-niz', 'هل يمكنك إعطاء مثال؟', 'دەتوانیت نموونەیەک بدەیت؟']),
    w('sayfa', 'say-FA', 'صفحة', 'لاپەڕە',
      ['Kitabın ellinci sayfasındayım.', 'ki-ta-BIN el-lin-Cİ say-fa-sın-da-YIM', 'أنا في الصفحة الخمسين من الكتاب.', 'لە لاپەڕەی پەنجای کتێبەکەدام.']),
    w('satır', 'sa-TIR', 'سطر', 'ڕیز',
      ['Üçüncü satırı okur musun?', 'ü-çün-CÜ sa-tı-RI o-KUR mu-sun', 'هل تقرأ السطر الثالث؟', 'ڕیزی سێیەم دەخوێنیتەوە؟']),
    w('nokta', 'nok-TA', 'نقطة', 'خاڵ',
      ['Cümlenin sonuna nokta koy.', 'cüm-le-NİN so-nu-NA nok-TA koy', 'ضع نقطة في نهاية الجملة.', 'لە کۆتایی ڕستەکەدا خاڵ دابنێ.']),
    w('şekil', 'şe-KİL', 'شكل، صورة', 'شێوە',
      ['Bu şekilde daha kolay olur.', 'BU şe-kil-DE da-HA ko-LAY o-LUR', 'بهذا الشكل يصبح أسهل.', 'بەم شێوەیە ئاسانتر دەبێت.']),
  ]),
  ...pack('emotions', 'b1', 'noun', [
    w('şeref', 'şe-REF', 'شرف', 'شەرەف',
      ['Sizi tanımak bir şereftir.', 'si-Zİ ta-nı-MAK bir şe-ref-TİR', 'معرفتكم شرف لي.', 'ناسینتان شەرەفە.']),
    w('hatıra', 'ha-tı-RA', 'ذكرى', 'یادەوەری',
      ['Bu fotoğraf güzel bir hatıra.', 'BU fo-toğ-RAF gü-ZEL bir ha-tı-RA', 'هذه الصورة ذكرى جميلة.', 'ئەم وێنەیە یادەوەرییەکی جوانە.']),
    w('cesaret', 'ce-sa-RET', 'جسارة، شجاعة', 'ئازایەتی',
      ['Konuşmaya cesaret edemedi.', 'ko-nuş-ma-YA ce-sa-RET e-de-me-Dİ', 'لم يجرؤ على الكلام.', 'نەیوێرا قسە بکات.']),
    w('heves', 'he-VES', 'حماسة عابرة، رغبة', 'پەرۆشی',
      ['İlk hevesi çabuk geçti.', 'İLK he-ve-Sİ ça-BUK geç-Tİ', 'زالت حماسته الأولى سريعاً.', 'پەرۆشی یەکەمی بە خێرایی نەما.']),
  ]),
  ...pack('expressions', 'b1', 'conjunction', [
    w('fakat', 'fa-KAT', 'لكن', 'بەڵام',
      ['Denedim, fakat olmadı.', 'de-ne-DİM fa-KAT ol-ma-DI', 'حاولت، لكن لم ينجح.', 'هەوڵمدا، بەڵام نەبوو.']),
    w('lakin', 'lâ-KİN', 'لكن (أدبي)', 'بەڵام',
      ['Haklısın, lakin geç kaldık.', 'hak-lı-SIN lâ-KİN GEÇ kal-DIK', 'معك حقّ، لكننا تأخّرنا.', 'ڕاست دەکەیت، بەڵام دواکەوتین.']),
    w('rağmen', 'rağ-MEN', 'رغم', 'سەرەڕای',
      ['Yağmura rağmen çıktık.', 'yağ-mu-RA rağ-MEN çık-TIK', 'خرجنا رغم المطر.', 'سەرەڕای باران دەرچووین.']),
    w('zaten', 'za-TEN', 'على أي حال، أصلاً', 'بەهەرحاڵ',
      ['Zaten gitmek istemiyordum.', 'za-TEN git-MEK is-te-mi-yor-DUM', 'أصلاً لم أكن أريد الذهاب.', 'بەهەرحاڵ نەمدەویست بڕۆم.']),
    w('asla', 'as-LA', 'أبداً', 'هەرگیز',
      ['Böyle bir şeyi asla yapmam.', 'böy-LE bir şe-Yİ as-LA yap-MAM', 'لن أفعل شيئاً كهذا أبداً.', 'هەرگیز شتی وا ناکەم.']),
    w('daima', 'da-i-MA', 'دائماً', 'هەمیشە',
      ['Daima yanındayım.', 'da-i-MA ya-nın-da-YIM', 'أنا دائماً بجانبك.', 'هەمیشە لەگەڵتم.']),
    w('takriben', 'tak-ri-BEN', 'تقريباً', 'نزیکەی',
      ['Takriben iki saat sürdü.', 'tak-ri-BEN i-Kİ sa-AT sür-DÜ', 'استغرق ساعتين تقريباً.', 'نزیکەی دوو کاتژمێری خایاند.']),
    w('tamamen', 'ta-ma-MEN', 'تماماً', 'بە تەواوی',
      ['Tamamen haklısınız.', 'ta-ma-MEN hak-lı-sı-NIZ', 'أنتم محقّون تماماً.', 'بە تەواوی ڕاست دەکەن.']),
    w('hakikaten', 'ha-ki-ka-TEN', 'حقيقةً، فعلاً', 'بەڕاستی',
      ['Hakikaten çok yardımcı oldunuz.', 'ha-ki-ka-TEN ÇOK yar-dım-CI ol-du-NUZ', 'ساعدتم فعلاً كثيراً.', 'بەڕاستی زۆر یارمەتیدەر بوون.']),
    w('estağfurullah', 'es-tağ-fu-rul-LAH', 'لا شكر على واجب', 'شایانی باسکردن نییە',
      ['— Çok teşekkürler. — Estağfurullah.', 'ÇOK te-şek-kür-LER es-tağ-fu-rul-LAH', '— شكراً جزيلاً. — لا شكر على واجب.', '— زۆر سوپاس. — شایانی باسکردن نییە.']),
  ]),
  ...pack('health', 'b1', 'noun', [
    w('mide', 'mi-DE', 'معدة', 'گەدە',
      ['Midem ağrıyor.', 'mi-DEM ağ-rı-YOR', 'معدتي تؤلمني.', 'گەدەم دەئێشێت.']),
    w('afiyet', 'a-fi-YET', 'عافية', 'تەندروستی',
      ['Afiyet olsun!', 'a-fi-YET ol-SUN', 'بالعافية!', 'نۆشی گیان!']),
  ]),
  ...pack('nouns', 'b1', 'noun', [
    w('kaza', 'ka-ZA', 'حادث', 'ڕووداو',
      ['Yolda küçük bir kaza oldu.', 'yol-DA kü-ÇÜK bir ka-ZA ol-DU', 'وقع حادث صغير في الطريق.', 'لە ڕێگادا ڕووداوێکی بچووک ڕوویدا.']),
    w('tehlike', 'teh-li-KE', 'خطر', 'مەترسی',
      ['Burada tehlike var.', 'bu-ra-DA teh-li-KE var', 'هنا يوجد خطر.', 'لێرە مەترسی هەیە.']),
    w('şart', 'ŞART', 'شرط', 'مەرج',
      ['Tek şartım var.', 'TEK şar-TIM var', 'لديّ شرط واحد.', 'تەنها یەک مەرجم هەیە.']),
    w('netice', 'ne-ti-CE', 'نتيجة', 'ئەنجام',
      ['Netice olarak haklı çıktı.', 'ne-ti-CE o-la-RAK hak-LI çık-TI', 'وفي النتيجة كان محقّاً.', 'لە ئەنجامدا ڕاستی دەرکەوت.']),
    w('hedef', 'he-DEF', 'هدف', 'ئامانج',
      ['Hedefime ulaştım.', 'he-de-fi-ME u-laş-TIM', 'وصلت إلى هدفي.', 'گەیشتمە ئامانجەکەم.']),
    w('mesafe', 'me-sa-FE', 'مسافة', 'دووری',
      ['İki şehir arasındaki mesafe kısa.', 'i-Kİ şe-HİR a-ra-sın-da-Kİ me-sa-FE kı-SA', 'المسافة بين المدينتين قصيرة.', 'دووری نێوان دوو شار کورتە.']),
    w('taraf', 'ta-RAF', 'طرف، جهة', 'لا',
      ['Hangi taraftan geldin?', 'han-Gİ ta-raf-TAN gel-DİN', 'من أيّ جهة أتيت؟', 'لە کام لاوە هاتیت؟']),
  ]),
];

/* ------------------------------------------------------------------ */
/* B2 — law, institutions, arts, character                             */
/* ------------------------------------------------------------------ */

const B2_LINKS: VocabItem[] = [
  ...pack('law', 'b2', 'noun', [
    w('kanun', 'ka-NUN', 'قانون', 'یاسا',
      ['Yeni kanun yarın yürürlüğe giriyor.', 'ye-Nİ ka-NUN ya-RIN yü-rür-lü-ĞE gi-ri-YOR', 'يدخل القانون الجديد حيّز التنفيذ غداً.', 'یاسا نوێیەکە سبەینێ جێبەجێ دەکرێت.']),
    w('hukuk', 'hu-KUK', 'حقوق، قانون (تخصّص)', 'مافەکان',
      ['Hukuk fakültesinde okuyor.', 'hu-KUK fa-kül-te-sin-DE o-ku-YOR', 'يدرس في كلية الحقوق.', 'لە فاکەڵتی یاسا دەخوێنێت.']),
    w('adalet', 'a-da-LET', 'عدالة', 'دادپەروەری',
      ['Adalet herkes için olmalı.', 'a-da-LET her-KES i-ÇİN ol-ma-LI', 'يجب أن تكون العدالة للجميع.', 'دادپەروەری دەبێت بۆ هەمووان بێت.']),
    w('hâkim', 'hâ-KİM', 'قاضٍ', 'دادوەر',
      ['Hâkim kararını açıkladı.', 'hâ-KİM ka-ra-rı-NI a-çık-la-DI', 'أعلن القاضي حكمه.', 'دادوەر بڕیارەکەی ڕاگەیاند.']),
    w('şahit', 'şa-HİT', 'شاهد', 'شایەت',
      ['Olaya iki kişi şahit oldu.', 'o-la-YA i-Kİ ki-Şİ şa-HİT ol-DU', 'شهد الحادثة شخصان.', 'دوو کەس شایەتی ڕووداوەکە بوون.']),
    w('vekil', 'və-KİL', 'وكيل، نائب', 'وەکیل',
      ['Şirketin hukuk vekili aradı.', 'şir-ke-TİN hu-KUK ve-ki-Lİ a-ra-DI', 'اتّصل وكيل الشركة القانوني.', 'وەکیلی یاسایی کۆمپانیاکە پەیوەندی کرد.']),
    w('mesuliyet', 'me-su-li-YET', 'مسؤولية', 'بەرپرسیارێتی',
      ['Bu işin mesuliyeti bana ait.', 'BU i-ŞİN me-su-li-ye-Tİ ba-NA a-İT', 'مسؤولية هذا العمل تقع عليّ.', 'بەرپرسیارێتی ئەم کارە هی منە.']),
    w('vesika', 'və-si-KA', 'وثيقة', 'بەڵگەنامە',
      ['Gerekli vesikaları hazırladım.', 'ge-rek-Lİ və-si-ka-la-RI ha-zır-la-DIM', 'حضّرت الوثائق المطلوبة.', 'بەڵگەنامە پێویستەکانم ئامادە کرد.']),
    w('imza', 'im-ZA', 'إمضاء، توقيع', 'واژوو',
      ['Sözleşmeyi imzaladık.', 'söz-leş-me-Yİ im-za-la-DIK', 'وقّعنا العقد.', 'گرێبەستەکەمان واژوو کرد.']),
  ]),
  ...pack('society', 'b2', 'noun', [
    w('meclis', 'mec-LİS', 'مجلس، برلمان', 'ئەنجومەن',
      ['Meclis bugün toplanıyor.', 'mec-LİS bu-GÜN top-la-nı-YOR', 'يجتمع المجلس اليوم.', 'ئەنجومەن ئەمڕۆ کۆدەبێتەوە.']),
    w('idare', 'i-da-RE', 'إدارة', 'بەڕێوەبردن',
      ['Okul idaresi ile görüştüm.', 'o-KUL i-da-re-Sİ i-LE gö-rüş-TÜM', 'قابلت إدارة المدرسة.', 'لەگەڵ بەڕێوەبەرایەتی قوتابخانە دانیشتم.']),
    w('cemiyet', 'ce-mi-YET', 'جمعية', 'کۆمەڵە',
      ['Yardım cemiyetine üye oldu.', 'yar-DIM ce-mi-ye-ti-NE ü-YE ol-DU', 'انضمّ إلى جمعية خيرية.', 'بووە ئەندامی کۆمەڵەیەکی یارمەتیدان.']),
    w('nüfus', 'nü-FUS', 'عدد السكان، السجل المدني', 'دانیشتوان',
      ['Şehrin nüfusu hızla artıyor.', 'şeh-RİN nü-fu-SU hız-LA ar-tı-YOR', 'يزداد عدد سكان المدينة بسرعة.', 'دانیشتوانی شارەکە بە خێرایی زیاد دەکات.']),
    w('hürriyet', 'hür-ri-YET', 'حرية', 'ئازادی',
      ['Basın hürriyeti önemlidir.', 'ba-SIN hür-ri-ye-Tİ ö-nem-li-DİR', 'حرية الصحافة مهمّة.', 'ئازادی ڕۆژنامەگەری گرنگە.']),
    w('hak', 'HAK', 'حقّ', 'ماف',
      ['Herkesin eğitim hakkı vardır.', 'her-ke-SİN e-ği-TİM hak-KI var-DIR', 'لكلّ إنسان حقّ في التعليم.', 'هەموو کەسێک مافی خوێندنی هەیە.']),
    w('hakikat', 'ha-ki-KAT', 'حقيقة', 'ڕاستی',
      ['Hakikati er geç öğreneceğiz.', 'ha-ki-ka-Tİ ER geç öğ-re-ne-ce-ĞİZ', 'سنعرف الحقيقة عاجلاً أم آجلاً.', 'زوو یان درەنگ ڕاستییەکە دەزانین.']),
    w('zulüm', 'zu-LÜM', 'ظلم', 'ستەم',
      ['Zulme karşı sessiz kalmadı.', 'zul-ME kar-ŞI ses-SİZ kal-ma-DI', 'لم يصمت أمام الظلم.', 'بەرامبەر ستەم بێدەنگ نەبوو.']),
    w('emniyet', 'em-ni-YET', 'أمن، شرطة', 'ئاسایش',
      ['Emniyet müdürlüğüne başvurdu.', 'em-ni-YET mü-dür-lü-ğü-NE baş-vur-DU', 'تقدّم بطلب إلى مديرية الأمن.', 'داواکاری بۆ بەڕێوەبەرایەتی ئاسایش پێشکەش کرد.']),
    w('asker', 'as-KER', 'عسكري، جندي', 'سەرباز',
      ['Kardeşim asker oldu.', 'kar-de-ŞİM as-KER ol-DU', 'صار أخي جندياً.', 'برام بووە سەرباز.']),
    w('silah', 'si-LAH', 'سلاح', 'چەک',
      ['Silahların kontrolü tartışılıyor.', 'si-lah-la-RIN kont-ro-LÜ tar-tı-şı-lı-YOR', 'يُناقَش ضبط الأسلحة.', 'کۆنترۆڵی چەک باس دەکرێت.']),
    w('sulh', 'SULH', 'صلح، سلام', 'ئاشتی',
      ['İki taraf sulh yaptı.', 'i-Kİ ta-RAF SULH yap-TI', 'تصالح الطرفان.', 'هەردوو لا ئاشت بوونەوە.']),
    w('ittifak', 'it-ti-FAK', 'تحالف', 'هاوپەیمانی',
      ['İki parti ittifak kurdu.', 'i-Kİ par-Tİ it-ti-FAK kur-DU', 'أقام الحزبان تحالفاً.', 'دوو پارت هاوپەیمانییان دروست کرد.']),
    w('şehit', 'şe-HİT', 'شهيد', 'شەهید',
      ['Şehitler anıldı.', 'şe-hit-LER a-nıl-DI', 'أُحيِيَت ذكرى الشهداء.', 'یادی شەهیدان کرایەوە.']),
    w('memur', 'me-MUR', 'موظّف حكومي', 'فەرمانبەر',
      ['Devlet memuru olarak çalışıyor.', 'dev-LET me-mu-RU o-la-RAK ça-lı-şı-YOR', 'يعمل موظّفاً حكومياً.', 'وەک فەرمانبەری دەوڵەت کار دەکات.']),
  ]),
  ...pack('literary', 'b2', 'noun', [
    w('edebiyat', 'e-de-bi-YAT', 'أدب', 'ئەدەبیات',
      ['Türk edebiyatını seviyorum.', 'TÜRK e-de-bi-ya-tı-NI se-vi-yo-RUM', 'أحبّ الأدب التركي.', 'ئەدەبیاتی تورکیم خۆشدەوێت.']),
    w('şiir', 'şi-İR', 'شِعر، قصيدة', 'شیعر',
      ['Bu şiiri ezbere biliyorum.', 'BU şi-i-Rİ ez-be-RE bi-li-yo-RUM', 'أحفظ هذه القصيدة.', 'ئەم شیعرە لەبەرم.']),
    w('şair', 'şa-İR', 'شاعر', 'شاعیر',
      ['Nâzım Hikmet büyük bir şairdir.', 'nâ-ZIM hik-MET bü-YÜK bir şa-ir-DİR', 'ناظم حكمت شاعر كبير.', 'ناظم حیکمەت شاعیرێکی گەورەیە.']),
    w('hikâye', 'hi-kâ-YE', 'حكاية، قصة', 'چیرۆک',
      ['Bana bir hikâye anlat.', 'ba-NA bir hi-kâ-YE an-LAT', 'احكِ لي قصة.', 'چیرۆکێکم بۆ بگێڕەوە.']),
    w('sanat', 'sa-NAT', 'فنّ', 'هونەر',
      ['Sanat insanı özgürleştirir.', 'sa-NAT in-sa-NI öz-gür-leş-ti-RİR', 'الفنّ يحرّر الإنسان.', 'هونەر مرۆڤ ئازاد دەکات.']),
    w('resim', 'rə-SİM', 'رسم، صورة', 'وێنە',
      ['Duvarda güzel bir resim var.', 'du-var-DA gü-ZEL bir rə-SİM var', 'على الجدار لوحة جميلة.', 'لەسەر دیوارەکە وێنەیەکی جوان هەیە.']),
    w('mimari', 'mi-ma-Rİ', 'عمارة، معماري', 'تەلارسازی',
      ['Osmanlı mimarisi çok etkileyici.', 'os-man-LI mi-ma-ri-Sİ ÇOK et-ki-le-yi-Cİ', 'العمارة العثمانية مؤثّرة جداً.', 'تەلارسازی عوسمانی زۆر کاریگەرە.']),
    w('tercüme', 'ter-cü-ME', 'ترجمة', 'وەرگێڕان',
      ['Bu romanın tercümesi çok iyi.', 'BU ro-ma-NIN ter-cü-me-Sİ ÇOK i-Yİ', 'ترجمة هذه الرواية جيدة جداً.', 'وەرگێڕانی ئەم ڕۆمانە زۆر باشە.']),
    w('lisan', 'li-SAN', 'لسان، لغة (رسمي)', 'زمان',
      ['Yabancı lisan öğrenmek şart.', 'ya-ban-CI li-SAN öğ-ren-MEK ŞART', 'تعلّم لغة أجنبية ضرورة.', 'فێربوونی زمانی بیانی پێویستە.']),
  ]),
  ...pack('finance', 'b2', 'noun', [
    w('ticaret', 'ti-ca-RET', 'تجارة', 'بازرگانی',
      ['İki ülke arasındaki ticaret arttı.', 'i-Kİ ül-KE a-ra-sın-da-Kİ ti-ca-RET art-TI', 'ازدادت التجارة بين البلدين.', 'بازرگانی نێوان دوو وڵات زیادی کرد.']),
    w('tüccar', 'tüc-CAR', 'تاجر', 'بازرگان',
      ['Babası kumaş tüccarıydı.', 'ba-ba-SI ku-MAŞ tüc-ca-rıy-DI', 'كان أبوه تاجر أقمشة.', 'باوکی بازرگانی قوماش بوو.']),
    w('sanayi', 'sa-na-Yİ', 'صناعة', 'پیشەسازی',
      ['Otomotiv sanayii büyüyor.', 'o-to-mo-TİV sa-na-yi-İ bü-yü-YOR', 'تنمو الصناعة السيارية.', 'پیشەسازی ئۆتۆمبێل گەشە دەکات.']),
    w('ziraat', 'zi-ra-AT', 'زراعة', 'کشتوکاڵ',
      ['Bölge ziraatla geçiniyor.', 'böl-GE zi-ra-at-LA ge-çi-ni-YOR', 'تعيش المنطقة على الزراعة.', 'ناوچەکە بە کشتوکاڵ بژێو دەکات.']),
    w('iktisat', 'ik-ti-SAT', 'اقتصاد', 'ئابووری',
      ['İktisat bölümünde okuyor.', 'ik-ti-SAT bö-lü-mün-DE o-ku-YOR', 'يدرس في قسم الاقتصاد.', 'لە بەشی ئابووری دەخوێنێت.']),
    w('servet', 'ser-VET', 'ثروة', 'سامان',
      ['Bütün servetini bağışladı.', 'bü-TÜN ser-ve-ti-Nİ ba-ğış-la-DI', 'تبرّع بكلّ ثروته.', 'هەموو سامانەکەی بەخشی.']),
    w('menfaat', 'men-fa-AT', 'منفعة، مصلحة', 'بەرژەوەندی',
      ['Kişisel menfaat peşinde değil.', 'ki-şi-SEL men-fa-AT pe-şin-DE de-ĞİL', 'ليس وراء مصلحة شخصية.', 'دوای بەرژەوەندی کەسی نییە.']),
    w('mülk', 'MÜLK', 'ملك، عقار', 'موڵک',
      ['Bu mülk aileye ait.', 'BU MÜLK a-i-le-YE a-İT', 'هذا العقار ملك للعائلة.', 'ئەم موڵکە هی خێزانەکەیە.']),
    w('emlak', 'em-LAK', 'عقارات', 'خانووبەرە',
      ['Emlak fiyatları yükseldi.', 'em-LAK fi-yat-la-RI yük-sel-Dİ', 'ارتفعت أسعار العقارات.', 'نرخی خانووبەرە بەرزبووەوە.']),
    w('inşaat', 'in-şa-AT', 'إنشاء، بناء', 'بیناسازی',
      ['İnşaat üç yıl sürdü.', 'in-şa-AT ÜÇ YIL sür-DÜ', 'استغرق البناء ثلاث سنوات.', 'بیناسازییەکە سێ ساڵی خایاند.']),
    w('maliye', 'ma-li-YE', 'مالية', 'دارایی',
      ['Maliye Bakanlığı açıklama yaptı.', 'ma-li-YE ba-kan-lı-ĞI a-çık-la-MA yap-TI', 'أصدرت وزارة المالية بياناً.', 'وەزارەتی دارایی ڕاگەیەندراوێکی بڵاوکردەوە.']),
    w('fakir', 'fa-KİR', 'فقير', 'هەژار',
      ['Fakir ailelere yardım ediyor.', 'fa-KİR a-i-le-le-RE yar-DIM e-di-YOR', 'يساعد العائلات الفقيرة.', 'یارمەتی خێزانە هەژارەکان دەدات.'], 'adjective'),
    w('fayda', 'fay-DA', 'فائدة، نفع', 'سوود',
      ['Bunun bize ne faydası var?', 'bu-NUN bi-ZE NE fay-da-SI var', 'ما فائدة هذا لنا؟', 'ئەمە چ سوودێکی بۆ ئێمە هەیە؟']),
    w('müsabaka', 'mü-sa-ba-KA', 'مسابقة', 'پێشبڕکێ',
      ['Şiir müsabakasında birinci oldu.', 'şi-İR mü-sa-ba-ka-sın-DA bi-rin-Cİ ol-DU', 'حلّ أولاً في مسابقة الشعر.', 'لە پێشبڕکێی شیعردا یەکەم بوو.']),
  ]),
  ...pack('academic', 'b2', 'noun', [
    w('ilim', 'i-LİM', 'علم', 'زانست',
      ['İlim öğrenmek herkese farzdır.', 'i-LİM öğ-ren-MEK her-ke-SE farz-DIR', 'طلب العلم فريضة على الجميع.', 'فێربوونی زانست لەسەر هەمووان پێویستە.']),
    w('coğrafya', 'coğ-raf-YA', 'جغرافيا', 'جوگرافیا',
      ['Coğrafya dersini seviyorum.', 'coğ-raf-YA der-si-Nİ se-vi-yo-RUM', 'أحبّ درس الجغرافيا.', 'وانەی جوگرافیام خۆشدەوێت.']),
    w('tecrübe', 'tec-rü-BE', 'تجربة، خبرة', 'ئەزموون',
      ['On yıllık tecrübesi var.', 'ON yıl-LIK tec-rü-be-Sİ var', 'لديه خبرة عشر سنوات.', 'دە ساڵ ئەزموونی هەیە.']),
    w('tahlil', 'tah-LİL', 'تحليل', 'شیکاری',
      ['Kan tahlili sonucu çıktı.', 'KAN tah-li-Lİ so-nu-CU çık-TI', 'صدرت نتيجة تحليل الدم.', 'ئەنجامی شیکاری خوێن دەرچوو.']),
    w('takdir', 'tak-DİR', 'تقدير', 'ڕێزلێنان',
      ['Çabalarınızı takdir ediyorum.', 'ça-ba-la-rı-nı-ZI tak-DİR e-di-yo-RUM', 'أقدّر جهودكم.', 'ڕێز لە هەوڵەکانتان دەگرم.']),
    w('tavsiye', 'tav-si-YE', 'توصية، نصيحة', 'ئامۆژگاری',
      ['Bir kitap tavsiye eder misiniz?', 'BİR ki-TAP tav-si-YE e-DER mi-si-niz', 'هل توصون بكتاب؟', 'کتێبێک پێشنیار دەکەن؟']),
    w('nasihat', 'na-si-HAT', 'نصيحة', 'ئامۆژگاری',
      ['Babamın nasihatini unutmam.', 'ba-ba-MIN na-si-ha-ti-Nİ u-nut-MAM', 'لا أنسى نصيحة أبي.', 'ئامۆژگاری باوکم لەبیر ناکەم.']),
    w('münakaşa', 'mü-na-ka-ŞA', 'مشادّة، جدال', 'دەمەقاڵێ',
      ['Küçük bir münakaşa çıktı.', 'kü-ÇÜK bir mü-na-ka-ŞA çık-TI', 'نشب جدال صغير.', 'دەمەقاڵێیەکی بچووک ڕوویدا.']),
    w('usul', 'u-SUL', 'أسلوب، إجراء', 'ڕێکار',
      ['Bu işin bir usulü var.', 'BU i-ŞİN bir u-su-LÜ var', 'لهذا العمل أصول.', 'ئەم کارە ڕێکاری خۆی هەیە.']),
    w('kaide', 'ka-i-DE', 'قاعدة', 'بنەما',
      ['Her kaidenin bir istisnası vardır.', 'HER ka-i-de-NİN bir is-tis-na-SI var-DIR', 'لكلّ قاعدة استثناء.', 'هەموو بنەمایەک ئیستیسنایەکی هەیە.']),
    w('ihtimal', 'ih-ti-MAL', 'احتمال', 'ئەگەر',
      ['Yağmur ihtimali yüksek.', 'yağ-MUR ih-ti-ma-Lİ yük-SEK', 'احتمال المطر مرتفع.', 'ئەگەری باران بەرزە.']),
    w('maksat', 'mak-SAT', 'مقصد، غرض', 'مەبەست',
      ['Maksadım seni üzmek değildi.', 'mak-sa-DIM se-Nİ üz-MEK de-ğil-Dİ', 'لم يكن قصدي إزعاجك.', 'مەبەستم نەبوو دڵت بشکێنم.']),
    w('gaye', 'ga-YE', 'غاية، هدف نهائي', 'ئامانج',
      ['Hayattaki gayen ne?', 'ha-yat-ta-Kİ ga-YEN ne', 'ما غايتك في الحياة؟', 'ئامانجت لە ژیاندا چییە؟']),
    w('vasıta', 'va-sı-TA', 'واسطة، وسيلة', 'ئامراز',
      ['Dil bir iletişim vasıtasıdır.', 'DİL bir i-le-ti-ŞİM va-sı-ta-sı-DIR', 'اللغة وسيلة تواصل.', 'زمان ئامرازی پەیوەندییە.']),
    w('mantık', 'man-TIK', 'منطق', 'لۆژیک',
      ['Bu açıklamanın mantığı yok.', 'BU a-çık-la-ma-NIN man-tı-ĞI yok', 'هذا التفسير لا منطق له.', 'ئەم ڕوونکردنەوەیە لۆژیکی نییە.']),
    w('malumat', 'ma-lu-MAT', 'معلومات (رسمي)', 'زانیاری',
      ['Konu hakkında malumatım yok.', 'ko-NU hak-kın-DA ma-lu-ma-TIM yok', 'ليست لديّ معلومات عن الموضوع.', 'زانیاریم دەربارەی بابەتەکە نییە.']),
  ]),
  ...pack('adjectives', 'b2', 'adjective', [
    w('meşhur', 'meş-HUR', 'مشهور', 'بەناوبانگ',
      ['Bu lokanta kebabıyla meşhur.', 'BU lo-kan-TA ke-ba-bıy-LA meş-HUR', 'هذا المطعم مشهور بكبابه.', 'ئەم چێشتخانەیە بە کەبابەکەی بەناوبانگە.']),
    w('mecbur', 'mec-BUR', 'مجبور، مضطرّ', 'ناچار',
      ['Gitmek zorunda, mecburum.', 'git-MEK zo-run-DA mec-bu-RUM', 'مضطرّ للذهاب.', 'ناچارم بڕۆم.']),
    w('muhtaç', 'muh-TAÇ', 'محتاج', 'پێویستیدار',
      ['Yardıma muhtaç insanlar var.', 'yar-dı-MA muh-TAÇ in-san-LAR var', 'هناك أناس محتاجون للمساعدة.', 'کەسانێک هەن پێویستیان بە یارمەتییە.']),
    w('münasip', 'mü-na-SİP', 'مناسب', 'گونجاو',
      ['Münasip bir zaman seçelim.', 'mü-na-SİP bir za-MAN se-çe-LİM', 'لنختر وقتاً مناسباً.', 'با کاتێکی گونجاو هەڵبژێرین.']),
    w('müstakil', 'müs-ta-KİL', 'مستقلّ', 'سەربەخۆ',
      ['Müstakil bir evde oturuyorlar.', 'müs-ta-KİL bir ev-DE o-tu-ru-yor-LAR', 'يسكنون في بيت مستقلّ.', 'لە ماڵێکی سەربەخۆدا دەژین.']),
    w('vasat', 'va-SAT', 'متوسّط (بمعنى ضعيف)', 'مامناوەند',
      ['Film vasat bir işti.', 'FİLM va-SAT bir iş-Tİ', 'كان الفيلم عملاً متوسّطاً.', 'فیلمەکە کارێکی مامناوەند بوو.']),
    w('mahsus', 'mah-SUS', 'مخصوص، خاصّ بـ', 'تایبەت',
      ['Bu yol yayalara mahsustur.', 'BU YOL ya-ya-la-RA mah-sus-TUR', 'هذا الطريق مخصّص للمشاة.', 'ئەم ڕێگایە تایبەتە بە پیادەکان.']),
    w('hususi', 'hu-su-Sİ', 'خصوصي (رسمي)', 'تایبەت',
      ['Hususi bir araçla geldiler.', 'hu-su-Sİ bir a-raç-LA gel-di-LER', 'جاؤوا بسيارة خاصّة.', 'بە ئۆتۆمبێلێکی تایبەت هاتن.']),
  ]),
  ...pack('emotions', 'b2', 'noun', [
    w('his', 'HİS', 'حسّ، شعور', 'هەست',
      ['İçimde kötü bir his var.', 'i-çim-DE kö-TÜ bir HİS var', 'لديّ إحساس سيّئ.', 'هەستێکی خراپم هەیە.']),
    w('hafıza', 'ha-fı-ZA', 'ذاكرة', 'بیرگە',
      ['Hafızası çok kuvvetli.', 'ha-fı-za-SI ÇOK kuv-vet-Lİ', 'ذاكرته قويّة جداً.', 'بیرگەی زۆر بەهێزە.']),
    w('zekâ', 'ze-KÂ', 'ذكاء', 'زیرەکی',
      ['Yapay zekâ hızla gelişiyor.', 'ya-PAY ze-KÂ hız-LA ge-li-şi-YOR', 'يتطوّر الذكاء الاصطناعي بسرعة.', 'زیرەکی دەستکرد بە خێرایی گەشە دەکات.']),
    w('ahlak', 'ah-LAK', 'أخلاق', 'ئەخلاق',
      ['İş ahlakı çok önemli.', 'İŞ ah-la-KI ÇOK ö-nem-Lİ', 'أخلاقيات العمل مهمّة جداً.', 'ئەخلاقی کار زۆر گرنگە.']),
    w('terbiye', 'ter-bi-YE', 'تربية', 'پەروەردە',
      ['Çocuk terbiyesi sabır ister.', 'ço-CUK ter-bi-ye-Sİ sa-BIR is-TER', 'تربية الأطفال تحتاج صبراً.', 'پەروەردەی منداڵ ئارام دەوێت.']),
    w('merhamet', 'mer-ha-MET', 'رحمة', 'بەزەیی',
      ['Merhametli bir insandı.', 'mer-ha-met-Lİ bir in-san-DI', 'كان إنساناً رحيماً.', 'مرۆڤێکی بەزەییدار بوو.']),
    w('şefkat', 'şef-KAT', 'شفقة، حنان', 'میهرەبانی',
      ['Anne şefkati eşsizdir.', 'an-NE şef-ka-Tİ eş-siz-DİR', 'حنان الأم لا يُضاهى.', 'میهرەبانی دایک بێوێنەیە.']),
    w('aşk', 'AŞK', 'عشق', 'عەشق',
      ['Bu bir aşk hikâyesi.', 'BU bir AŞK hi-kâ-ye-Sİ', 'هذه قصّة حبّ.', 'ئەمە چیرۆکی عەشقە.']),
    w('keder', 'ke-DER', 'كدر، حزن', 'خەم',
      ['Kederini kimseyle paylaşmadı.', 'ke-de-ri-Nİ kim-sey-LE pay-laş-ma-DI', 'لم يشارك حزنه مع أحد.', 'خەمەکەی لەگەڵ کەس بەشدار نەکرد.']),
    w('irade', 'i-ra-DE', 'إرادة', 'ویست',
      ['Güçlü bir iradesi var.', 'güç-LÜ bir i-ra-de-Sİ var', 'لديه إرادة قوية.', 'ویستێکی بەهێزی هەیە.']),
    w('azim', 'a-ZİM', 'عزم', 'بڕیاردانی توند',
      ['Azimle çalıştı ve başardı.', 'a-zim-LE ça-lış-TI ve ba-şar-DI', 'عمل بعزم ونجح.', 'بە بڕیارێکی توند کاری کرد و سەرکەوت.']),
    w('kader', 'ka-DER', 'قدر، مصير', 'چارەنووس',
      ['Kaderine razı oldu.', 'ka-de-ri-NE ra-ZI ol-DU', 'رضي بقدره.', 'ڕازی بوو بە چارەنووسی.']),
    w('nasip', 'na-SİP', 'نصيب', 'بەش',
      ['Nasip olursa görüşürüz.', 'na-SİP o-lur-SA gö-rü-şü-RÜZ', 'إن كان نصيب سنلتقي.', 'ئەگەر بەش بێت یەکتر دەبینین.']),
    w('kısmet', 'kıs-MET', 'قسمة، حظّ', 'قسمەت',
      ['Kısmet buraya kadarmış.', 'kıs-MET bu-ra-YA ka-dar-MIŞ', 'كان النصيب إلى هنا.', 'قسمەت تا ئێرە بوو.']),
    w('bereket', 'be-re-KET', 'بركة', 'بەرەکەت',
      ['Yağmur berekettir.', 'yağ-MUR be-re-ket-TİR', 'المطر بركة.', 'باران بەرەکەتە.']),
    w('hürmet', 'hür-MET', 'احترام', 'ڕێز',
      ['Büyüklere hürmet göstermeli.', 'bü-yük-le-RE hür-MET gös-ter-me-Lİ', 'ينبغي احترام الكبار.', 'دەبێت ڕێز لە گەورەکان بگیرێت.']),
    w('ayıp', 'a-YIP', 'عيب', 'عەیب',
      ['Böyle konuşmak ayıp.', 'böy-LE ko-nuş-MAK a-YIP', 'الكلام هكذا عيب.', 'بەم شێوەیە قسەکردن عەیبە.']),
    w('kusur', 'ku-SUR', 'قصور، عيب', 'کەموکوڕی',
      ['Kusuruma bakmayın.', 'ku-su-ru-MA bak-ma-YIN', 'اعذروا تقصيري.', 'لە کەموکوڕیم ببوورن.']),
    w('şiddet', 'şid-DET', 'عنف', 'توندوتیژی',
      ['Şiddete karşı çıkıyoruz.', 'şid-de-TE kar-ŞI çı-kı-yo-RUZ', 'نحن ضدّ العنف.', 'دژی توندوتیژی دەوەستین.']),
    w('afet', 'a-FET', 'كارثة طبيعية', 'کارەسات',
      ['Deprem büyük bir afetti.', 'dep-REM bü-YÜK bir a-fet-Tİ', 'كان الزلزال كارثة كبيرة.', 'بوومەلەرزەکە کارەساتێکی گەورە بوو.']),
    w('imdat', 'im-DAT', 'النجدة!', 'فریام بکەون!',
      ['İmdat! Yardım edin!', 'im-DAT yar-DIM e-DİN', 'النجدة! ساعدوني!', 'فریام بکەون! یارمەتیم بدەن!'], 'interjection'),
    w('devam', 'de-VAM', 'استمرار', 'بەردەوامی',
      ['Derse devam edelim.', 'ders-SE de-VAM e-de-LİM', 'لنكمل الدرس.', 'با بەردەوام بین لە وانەکە.']),
    w('muhit', 'mu-HİT', 'وسط اجتماعي، بيئة', 'ژینگەی کۆمەڵایەتی',
      ['İyi bir muhitte büyüdü.', 'i-Yİ bir mu-hit-TE bü-yü-DÜ', 'نشأ في وسط جيّد.', 'لە ژینگەیەکی باشدا گەورە بوو.']),
    w('tabiat', 'ta-bi-AT', 'طبيعة', 'سروشت',
      ['Tabiatı korumalıyız.', 'ta-bi-a-TI ko-ru-ma-lı-YIZ', 'علينا حماية الطبيعة.', 'دەبێت سروشت بپارێزین.']),
  ]),
  ...pack('places', 'b2', 'noun', [
    w('mevki', 'mev-Kİ', 'موقع، منصب', 'شوێن، پلە',
      ['Yüksek bir mevkiye geldi.', 'yük-SEK bir mev-ki-YE gel-Dİ', 'وصل إلى منصب رفيع.', 'گەیشتە پلەیەکی بەرز.']),
    w('hudut', 'hu-DUT', 'حدود', 'سنوور',
      ['Hudut kapısı kapalı.', 'hu-DUT ka-pı-SI ka-pa-LI', 'البوّابة الحدودية مغلقة.', 'دەروازەی سنوور داخراوە.']),
    w('ikram', 'ik-RAM', 'إكرام، ضيافة', 'خزمەت',
      ['Bu çay bizden ikram.', 'BU ÇAY biz-DEN ik-RAM', 'هذا الشاي ضيافة منّا.', 'ئەم چایە لە ئێمەوە خزمەتە.']),
    w('ziyafet', 'zi-ya-FET', 'مأدبة', 'خوانی میوانداری',
      ['Akşam büyük bir ziyafet var.', 'ak-ŞAM bü-YÜK bir zi-ya-FET var', 'هناك مأدبة كبيرة مساءً.', 'ئێوارە خوانێکی گەورە هەیە.']),
    w('mektup', 'mek-TUP', 'رسالة', 'نامە',
      ['Ona uzun bir mektup yazdım.', 'o-NA u-ZUN bir mek-TUP yaz-DIM', 'كتبت له رسالة طويلة.', 'نامەیەکی درێژم بۆ نووسی.']),
    w('ilan', 'i-LAN', 'إعلان', 'ڕاگەیاندن',
      ['Gazeteye iş ilanı verdik.', 'ga-ze-te-YE İŞ i-la-NI ver-DİK', 'وضعنا إعلان وظيفة في الجريدة.', 'ڕاگەیاندنی کارمان لە ڕۆژنامەدا بڵاوکردەوە.']),
  ]),
];

/* ------------------------------------------------------------------ */
/* C1 — abstract and scholarly                                         */
/* ------------------------------------------------------------------ */

const C1_LINKS: VocabItem[] = [
  ...pack('academic', 'c1', 'noun', [
    w('felsefe', 'fel-se-FE', 'فلسفة', 'فەلسەفە',
      ['Felsefe soru sormayı öğretir.', 'fel-se-FE so-RU sor-ma-YI öğ-re-TİR', 'الفلسفة تعلّم طرح الأسئلة.', 'فەلسەفە فێری پرسیارکردن دەکات.']),
    w('medeniyet', 'me-de-ni-YET', 'حضارة، مدنية', 'شارستانیەت',
      ['Anadolu birçok medeniyete ev sahipliği yaptı.', 'a-na-do-LU bir-ÇOK me-de-ni-ye-TE EV sa-hip-li-Ğİ yap-TI', 'احتضنت الأناضول حضارات كثيرة.', 'ئەناتۆلی میوانداری چەندین شارستانیەتی کردووە.']),
    w('tefsir', 'tef-SİR', 'تفسير', 'لێکدانەوە',
      ['Metnin tefsiri tartışmalı.', 'met-NİN tef-si-Rİ tar-tış-ma-LI', 'تفسير النصّ محلّ خلاف.', 'لێکدانەوەی دەقەکە جێی ناکۆکییە.']),
    w('bilhassa', 'bil-has-SA', 'بخاصّة، لا سيّما', 'بەتایبەتی',
      ['Bilhassa gençler etkilendi.', 'bil-has-SA genç-LER et-ki-len-Dİ', 'تأثّر الشباب بخاصّة.', 'بەتایبەتی گەنجان کاریان لێکرا.'], 'adverb'),
  ]),
];

export const ARABIC_LINK_VOCABULARY: VocabItem[] = [
  ...A1_LINKS,
  ...A2_LINKS,
  ...B1_LINKS,
  ...B2_LINKS,
  ...C1_LINKS,
];
