import type { SentencePack } from '@/types/content';
import { b, p } from '../shared/helpers';

export const A2_SENTENCES: SentencePack[] = [
  {
    id: 'a2-sent-past',
    level: 'a2',
    order: 1,
    title: 'Geçmişten Söz Etmek',
    titleI18n: b('الحديث عن الماضي', 'باسکردن لە ڕابردوو'),
    focus: b('احكِ ما فعلته أمس والأسبوع الماضي.', 'ئەوە بگێڕەوە کە دوێنێ و هەفتەی ڕابردوو کردت.'),
    sentences: [
      p('Dün çok yoruldum.', 'DÜN ÇOK yo-rul-DUM', 'تعبت كثيراً أمس.', 'دوێنێ زۆر ماندوو بووم.'),
      p('Geçen hafta İstanbul’a gittim.', 'ge-ÇEN haf-TA is-tan-BUL-a git-TİM', 'ذهبت إلى إسطنبول الأسبوع الماضي.', 'هەفتەی ڕابردوو چوومە ئەستەنبوڵ.'),
      p('Orada üç gün kaldım.', 'o-ra-DA ÜÇ GÜN kal-DIM', 'بقيت هناك ثلاثة أيام.', 'سێ ڕۆژ لەوێ مامەوە.'),
      p('Ayasofya’yı gezdim, çok etkilendim.', 'a-ya-sof-YA-yı gez-DİM ÇOK et-ki-len-DİM', 'زرت آيا صوفيا وتأثّرت كثيراً.', 'بەسەر ئایاسۆفیادا گەڕام، زۆر کاریگەر بووم.'),
      p('Boğazda vapura bindik.', 'bo-az-DA va-pu-RA bin-DİK', 'ركبنا العبّارة في البوسفور.', 'لە بۆغازەکەدا سواری کەشتی بووین.'),
      p('Akşam balık yedik.', 'ak-ŞAM ba-LIK ye-DİK', 'أكلنا سمكاً في المساء.', 'ئێوارە ماسیمان خوارد.'),
      p('Dönüşte trene bindim.', 'dö-nüş-TE tre-NE bin-DİM', 'ركبت القطار في العودة.', 'لە گەڕانەوەدا سواری شەمەندەفەر بووم.'),
      p('Çok güzel bir tatildi.', 'ÇOK gü-ZEL bir ta-til-Dİ', 'كانت عطلة جميلة جداً.', 'پشوویەکی زۆر جوان بوو.'),
      p('Fotoğraf çekmeyi unuttum.', 'fo-toğ-RAF çek-me-Yİ u-nut-TUM', 'نسيت أن ألتقط صوراً.', 'لەبیرم چوو وێنە بگرم.'),
    ],
  },
  {
    id: 'a2-sent-future',
    level: 'a2',
    order: 2,
    title: 'Gelecek Planları',
    titleI18n: b('الخطط المستقبلية', 'پلانی داهاتوو'),
    focus: b('تحدّث عمّا ستفعله غداً والعام القادم.', 'باس لەوە بکە کە سبەینێ و ساڵی داهاتوو دەیکەیت.'),
    sentences: [
      p('Yarın erken kalkacağım.', 'ya-RIN er-KEN kal-ka-dja-IM', 'سأستيقظ باكراً غداً.', 'سبەینێ زوو هەڵدەستم.'),
      p('Gelecek ay yeni bir işe başlayacağım.', 'ge-le-DJEK AY ye-Nİ bir i-ŞE baş-la-ya-dja-IM', 'سأبدأ عملاً جديداً الشهر القادم.', 'مانگی داهاتوو دەست بە کارێکی نوێ دەکەم.'),
      p('Bu yaz tatile çıkacağız.', 'BU YAZ ta-ti-LE çı-ka-dja-IZ', 'سنخرج في إجازة هذا الصيف.', 'ئەم هاوینە دەچینە پشوو.'),
      p('Türkçemi geliştirmek istiyorum.', 'türk-çe-Mİ ge-liş-tir-MEK is-ti-YO-rum', 'أريد تطوير لغتي التركية.', 'دەمەوێت تورکییەکەم باشتر بکەم.'),
      p('Bir yıl sonra sınava gireceğim.', 'bir YIL son-RA sı-na-VA gi-re-dje-İM', 'سأدخل الامتحان بعد سنة.', 'دوای ساڵێک دەچمە تاقیکردنەوە.'),
      p('Belki yurt dışında okuyacağım.', 'bel-Kİ yurt dı-şın-DA o-ku-ya-dja-IM', 'ربما سأدرس في الخارج.', 'لەوانەیە لە دەرەوەی وڵات بخوێنم.'),
      p('Söz veriyorum, seni arayacağım.', 'SÖZ ve-ri-YO-rum se-Nİ a-ra-ya-dja-IM', 'أعدك، سأتصل بك.', 'بەڵێنت پێدەدەم، پەیوەندیت پێوە دەکەم.'),
      p('Bu akşam dışarı çıkmayacağız.', 'BU ak-ŞAM dı-şa-RI çık-ma-ya-dja-IZ', 'لن نخرج هذا المساء.', 'ئەم ئێوارەیە نایەینە دەرەوە.'),
    ],
  },
  {
    id: 'a2-sent-directions',
    level: 'a2',
    order: 3,
    title: 'Yol Sormak ve Tarif Etmek',
    titleI18n: b('السؤال عن الطريق ووصفه', 'پرسیاری ڕێگا و ڕوونکردنەوەی'),
    focus: b('لا تضِع في مدينة تركية أبداً.', 'هەرگیز لە شارێکی تورکیدا ون مەبە.'),
    sentences: [
      p('Affedersiniz, metro istasyonu nerede?', 'af-fe-der-si-NİZ met-RO is-tas-yo-NU ne-re-DE', 'عذراً، أين محطة المترو؟', 'ببوورە، وێستگەی مێترۆ لە کوێیە؟'),
      p('Buraya nasıl giderim?', 'bu-ra-YA na-SIL gi-de-rim', 'كيف أذهب إلى هنا؟', 'چۆن بچمە ئێرە؟'),
      p('Doğru gidin, sonra sağa dönün.', 'do-RU gi-DİN son-RA sa-A dö-NÜN', 'امشِ مستقيماً ثم انعطف يميناً.', 'ڕاست بڕۆ، پاشان بەلای ڕاستدا بسووڕێوە.'),
      p('İkinci sokaktan sola sapın.', 'i-kin-DJİ so-kak-TAN so-LA sa-PIN', 'انعطف يساراً من الشارع الثاني.', 'لە کۆڵانی دووەمەوە بەلای چەپدا بسووڕێوە.'),
      p('Yürüyerek ne kadar sürer?', 'yü-rü-ye-REK ne ka-DAR sü-RER', 'كم يستغرق سيراً على الأقدام؟', 'بە پێ چەند دەخایەنێت؟'),
      p('Yaklaşık on dakika.', 'yak-la-ŞIK ON da-ki-KA', 'حوالي عشر دقائق.', 'نزیکەی دە خولەک.'),
      p('Çok uzak mı?', 'ÇOK u-ZAK mı', 'هل هو بعيد جداً؟', 'زۆر دوورە؟'),
      p('Hayır, çok yakın. Şurada.', 'ha-YIR ÇOK ya-KIN şu-ra-DA', 'لا، قريب جداً. هناك.', 'نەخێر، زۆر نزیکە. لەوێیە.'),
      p('Kayboldum, yardım eder misiniz?', 'kay-bol-DUM yar-DIM e-DER mi-si-niz', 'ضللت الطريق، هل تساعدني؟', 'ون بووم، یارمەتیم دەدەیت؟'),
    ],
  },
  {
    id: 'a2-sent-shopping',
    level: 'a2',
    order: 4,
    title: 'Alışveriş Yapmak',
    titleI18n: b('التسوّق والمساومة', 'بازاڕکردن و کڕین'),
    focus: b('اشترِ وقايض واسأل عن المقاس.', 'بکڕە و بازاڕ بکە و پرسیاری قەبارە بکە.'),
    sentences: [
      p('Bunun fiyatı ne kadar?', 'bu-NUN fi-ya-TI ne ka-DAR', 'كم سعر هذا؟', 'نرخی ئەمە چەندە؟'),
      p('Daha ucuzu var mı?', 'da-HA u-dju-ZU var MI', 'هل يوجد أرخص؟', 'هەرزانتری هەیە؟'),
      p('Biraz indirim yapar mısınız?', 'bi-RAZ in-di-RİM ya-PAR mı-sı-nız', 'هل تعطيني خصماً قليلاً؟', 'کەمێک داشکاندن دەکەیت؟'),
      p('Bir büyük beden var mı?', 'bir bü-YÜK be-DEN var MI', 'هل يوجد مقاس أكبر؟', 'قەبارەیەکی گەورەتر هەیە؟'),
      p('Bunu deneyebilir miyim?', 'bu-NU de-ne-ye-bi-LİR mi-yim', 'هل يمكنني تجربة هذا؟', 'دەتوانم ئەمە تاقی بکەمەوە؟'),
      p('Bu bana çok dar geldi.', 'BU ba-NA ÇOK DAR gel-Dİ', 'هذا ضيّق عليّ جداً.', 'ئەمە زۆر تەسکە بۆم.'),
      p('Bunu alıyorum.', 'bu-NU a-lı-YO-rum', 'سآخذ هذا.', 'ئەمە دەکڕم.'),
      p('Fişimi alabilir miyim?', 'fi-şi-Mİ a-la-bi-LİR mi-yim', 'هل يمكنني أخذ الإيصال؟', 'دەتوانم پسووڵەکەم وەربگرم؟'),
      p('Değişim yapabilir miyim?', 'de-i-ŞİM ya-pa-bi-LİR mi-yim', 'هل يمكنني الاستبدال؟', 'دەتوانم بیگۆڕمەوە؟'),
    ],
  },
  {
    id: 'a2-sent-opinion',
    level: 'a2',
    order: 5,
    title: 'Fikir Belirtmek',
    titleI18n: b('إبداء الرأي', 'دەربڕینی ڕا'),
    focus: b('قل رأيك بأدب واختلف بلياقة.', 'ڕات بە ڕێزەوە بڵێ و بە شێوەیەکی جوان جیاواز بە.'),
    sentences: [
      p('Bence bu çok güzel bir fikir.', 'ben-DJE BU ÇOK gü-ZEL bir fi-KİR', 'برأيي هذه فكرة جميلة جداً.', 'بە بۆچوونی من ئەمە بیرۆکەیەکی زۆر جوانە.'),
      p('Bana göre bu doğru değil.', 'ba-NA gö-RE BU do-RU de-İL', 'بالنسبة لي هذا ليس صحيحاً.', 'بە ڕای من ئەمە ڕاست نییە.'),
      p('Katılıyorum, haklısın.', 'ka-tı-lı-YO-rum hak-lı-SIN', 'أوافق، أنت على حق.', 'هاوڕام، ڕاست دەکەیت.'),
      p('Maalesef sana katılmıyorum.', 'ma-a-le-SEF sa-NA ka-tıl-mı-YO-rum', 'للأسف لا أوافقك.', 'بەداخەوە هاوڕا نیم لەگەڵت.'),
      p('Bu konuda emin değilim.', 'BU ko-nu-DA e-MİN de-i-LİM', 'لست متأكداً في هذا الموضوع.', 'لەم بابەتەدا دڵنیا نیم.'),
      p('Bence daha çok düşünmeliyiz.', 'ben-DJE da-HA ÇOK dü-şün-me-li-YİZ', 'برأيي يجب أن نفكّر أكثر.', 'بە بۆچوونی من دەبێت زیاتر بیر بکەینەوە.'),
      p('Sen ne düşünüyorsun?', 'SEN NE dü-şü-nü-yor-sun', 'ما رأيك أنت؟', 'تۆ چی بیر دەکەیتەوە؟'),
      p('Bana kalırsa en iyi seçenek bu.', 'ba-NA ka-lır-SA EN i-Yİ se-çe-NEK BU', 'في اعتقادي هذا أفضل خيار.', 'بە بۆچوونی من ئەمە باشترین هەڵبژاردەیە.'),
    ],
  },
];
