/**
 * Collocations, as an overlay.
 *
 * Turkish builds an enormous amount of its everyday meaning out of a noun plus
 * a light verb: `karar vermek`, `dikkat etmek`, `yardım etmek`, `hayal kurmak`.
 * The noun alone is nearly useless — a student who learns `karar` and then
 * guesses "karar yapmak" has learned a word and produced a mistake.
 *
 * These are keyed by Turkish word and applied over the vocabulary in
 * `content/index.ts`, exactly as the Arabic connections are. Same reasons:
 *
 *   - the words already exist across twenty content files, and editing all of
 *     them to add one field each would be churn with no benefit;
 *   - one file makes the pairings reviewable as a set, which is how a teacher
 *     would want to check them.
 *
 * An entry is only added where the pairing is genuinely fixed. `masa` takes no
 * characteristic verb, so `masa` is not here.
 */
export const COLLOCATIONS: Record<string, string[]> = {

  /* ---------------- decisions, opinions, thought ---------------- */

  karar: ['karar vermek', 'karar almak', 'kararı değiştirmek', 'kesin karar'],
  fikir: ['fikir vermek', 'fikir almak', 'fikrini değiştirmek', 'fikir ayrılığı'],
  görüş: ['görüş bildirmek', 'görüş almak', 'görüş ayrılığı'],
  mesele: ['meseleyi çözmek', 'mesele çıkarmak', 'önemli bir mesele'],
  sorun: ['sorun çıkarmak', 'sorunu çözmek', 'sorun yaşamak'],
  çözüm: ['çözüm bulmak', 'çözüm üretmek', 'kalıcı çözüm'],
  amaç: ['amaç edinmek', 'amaca ulaşmak', 'amacı doğrultusunda'],
  hedef: ['hedef koymak', 'hedefe ulaşmak', 'hedef kitle'],
  kural: ['kural koymak', 'kurala uymak', 'kuralı çiğnemek'],
  sebep: ['sebep olmak', 'sebebini açıklamak', 'geçerli sebep'],
  sonuç: ['sonuca varmak', 'sonuç çıkarmak', 'sonuç vermek'],
  etki: ['etki etmek', 'etki altında kalmak', 'olumsuz etki'],
  eleştiri: ['eleştiri yapmak', 'eleştiriye açık olmak', 'yapıcı eleştiri'],
  kavram: ['kavram karmaşası', 'kavramı tanımlamak'],
  mantık: ['mantığa uygun', 'mantık yürütmek', 'mantıklı davranmak'],
  ihtimal: ['ihtimal vermek', 'güçlü bir ihtimal', 'ihtimal dahilinde'],
  şart: ['şart koşmak', 'şartı yerine getirmek', 'ön şart'],
  gerekçe: ['gerekçe göstermek', 'gerekçesiz', 'haklı gerekçe'],
  kanıt: ['kanıt sunmak', 'kanıt toplamak', 'somut kanıt'],
  varsayım: ['varsayımda bulunmak', 'varsayımı test etmek'],
  tahmin: ['tahmin etmek', 'tahminde bulunmak', 'hava tahmini'],
  tercih: ['tercih etmek', 'tercih yapmak', 'kişisel tercih'],
  tavsiye: ['tavsiye etmek', 'tavsiyede bulunmak', 'tavsiye üzerine'],
  nasihat: ['nasihat vermek', 'nasihat dinlemek'],
  takdir: ['takdir etmek', 'takdir toplamak', 'takdire şayan'],

  /* ---------------- work and organisations ---------------- */

  toplantı: ['toplantı yapmak', 'toplantıya katılmak', 'toplantıyı ertelemek'],
  proje: ['proje yürütmek', 'projeye başlamak', 'projeyi teslim etmek'],
  görev: ['görev almak', 'görevi yerine getirmek', 'görevden ayrılmak'],
  sorumluluk: ['sorumluluk almak', 'sorumluluğu üstlenmek', 'sorumluluk sahibi'],
  deneyim: ['deneyim kazanmak', 'iş deneyimi', 'deneyim sahibi'],
  başvuru: ['başvuru yapmak', 'başvuruda bulunmak', 'başvuruyu değerlendirmek'],
  mülakat: ['mülakata girmek', 'mülakat yapmak'],
  izin: ['izin almak', 'izin vermek', 'yıllık izin'],
  sözleşme: ['sözleşme imzalamak', 'sözleşmeyi feshetmek', 'sözleşmeyi yenilemek'],
  anlaşma: ['anlaşma sağlamak', 'anlaşmaya varmak', 'anlaşmayı bozmak'],
  teklif: ['teklif etmek', 'teklifi kabul etmek', 'teklifi reddetmek'],
  rapor: ['rapor hazırlamak', 'rapor sunmak', 'yıllık rapor'],
  performans: ['performans göstermek', 'performansı değerlendirmek'],
  strateji: ['strateji belirlemek', 'strateji geliştirmek', 'uzun vadeli strateji'],
  ekip: ['ekip kurmak', 'ekip çalışması', 'ekibe katılmak'],
  yetenek: ['yetenek geliştirmek', 'doğal yetenek'],
  beceri: ['beceri kazanmak', 'iletişim becerisi'],
  terfi: ['terfi almak', 'terfi ettirmek'],
  kariyer: ['kariyer yapmak', 'kariyer planlamak', 'kariyer değiştirmek'],
  müzakere: ['müzakere etmek', 'müzakereye oturmak'],
  yönetim: ['yönetimi devralmak', 'üst yönetim', 'yönetim kurulu'],
  denetim: ['denetim yapmak', 'denetimden geçmek', 'iç denetim'],

  /* ---------------- money and the economy ---------------- */

  bütçe: ['bütçe ayırmak', 'bütçeyi aşmak', 'bütçe açığı'],
  yatırım: ['yatırım yapmak', 'yatırımı çekmek', 'uzun vadeli yatırım'],
  kâr: ['kâr etmek', 'kâr elde etmek', 'kâr marjı'],
  zarar: ['zarar etmek', 'zarar görmek', 'zarara uğramak'],
  borç: ['borç almak', 'borç ödemek', 'borca girmek'],
  vergi: ['vergi ödemek', 'vergi indirimi', 'vergiden muaf'],
  gelir: ['gelir elde etmek', 'gelir düzeyi', 'sabit gelir'],
  gider: ['gideri karşılamak', 'gider kalemi'],
  maliyet: ['maliyeti düşürmek', 'maliyeti karşılamak', 'birim maliyet'],
  piyasa: ['piyasaya çıkmak', 'piyasa koşulları', 'piyasayı takip etmek'],
  enflasyon: ['enflasyon oranı', 'enflasyonla mücadele'],
  rekabet: ['rekabet etmek', 'rekabete girmek', 'haksız rekabet'],
  sermaye: ['sermaye koymak', 'sermaye artırmak'],
  ihracat: ['ihracat yapmak', 'ihracatı artırmak'],
  ithalat: ['ithalat yapmak', 'ithalatı kısıtlamak'],
  ücret: ['ücret ödemek', 'ücret almak', 'giriş ücreti'],
  hesap: ['hesap açmak', 'hesabı ödemek', 'hesap sormak'],

  /* ---------------- study and research ---------------- */

  araştırma: ['araştırma yapmak', 'araştırmaya katılmak', 'saha araştırması'],
  tez: ['tez yazmak', 'tezi savunmak', 'yüksek lisans tezi'],
  sunum: ['sunum yapmak', 'sunum hazırlamak'],
  kayıt: ['kayıt yaptırmak', 'kayıt olmak', 'kaydı silinmek'],
  burs: ['burs almak', 'bursa başvurmak', 'burs kazanmak'],
  makale: ['makale yazmak', 'makale yayımlamak', 'hakemli makale'],
  atıf: ['atıf yapmak', 'atıfta bulunmak', 'atıf almak'],
  özet: ['özet çıkarmak', 'özet geçmek'],
  alıntı: ['alıntı yapmak', 'doğrudan alıntı'],
  deney: ['deney yapmak', 'deneyi tekrarlamak', 'kontrollü deney'],
  gözlem: ['gözlem yapmak', 'gözlem altında tutmak'],
  bulgu: ['bulgu elde etmek', 'bulguları paylaşmak'],
  veri: ['veri toplamak', 'veriyi analiz etmek', 'ham veri'],
  ölçüt: ['ölçüt belirlemek', 'ölçüte uymak'],
  yöntem: ['yöntem geliştirmek', 'yöntemi uygulamak', 'bilimsel yöntem'],
  kaynak: ['kaynak göstermek', 'kaynak taraması', 'birincil kaynak'],
  literatür: ['literatür taraması', 'literatüre katkı'],
  intihal: ['intihal yapmak', 'intihal tespiti'],

  /* ---------------- health ---------------- */

  tedavi: ['tedavi görmek', 'tedavi olmak', 'tedaviye başlamak'],
  teşhis: ['teşhis koymak', 'erken teşhis'],
  belirti: ['belirti göstermek', 'ilk belirtiler'],
  aşı: ['aşı olmak', 'aşı yaptırmak'],
  stres: ['stres yapmak', 'stresle başa çıkmak', 'stres altında'],
  bakım: ['bakım yapmak', 'bakıma almak', 'cilt bakımı'],
  nöbet: ['nöbet tutmak', 'nöbete kalmak'],
  doz: ['doz aşımı', 'dozu artırmak'],
  salgın: ['salgın başlamak', 'salgınla mücadele'],

  /* ---------------- feelings and character ---------------- */

  hayal: ['hayal kurmak', 'hayal kırıklığı', 'hayale kapılmak'],
  umut: ['umut etmek', 'umudunu kesmek', 'umut vermek'],
  kaygı: ['kaygı duymak', 'kaygıyı gidermek'],
  güven: ['güven duymak', 'güven kazanmak', 'güveni sarsmak'],
  şüphe: ['şüphe duymak', 'şüpheye düşmek'],
  dikkat: ['dikkat etmek', 'dikkat çekmek', 'dikkatini dağıtmak'],
  hatıra: ['hatıra biriktirmek', 'hatırasını yaşatmak'],
  cesaret: ['cesaret etmek', 'cesaret vermek', 'cesaretini toplamak'],
  sabır: ['sabır göstermek', 'sabrı taşmak', 'sabırla beklemek'],
  merhamet: ['merhamet etmek', 'merhamet duymak'],
  özlem: ['özlem duymak', 'özlemini gidermek'],
  pişmanlık: ['pişmanlık duymak', 'pişman olmak'],
  aşk: ['aşık olmak', 'aşk acısı'],
  hüzün: ['hüzne kapılmak', 'derin bir hüzün'],
  şeref: ['şeref duymak', 'şeref sözü'],
  ayıp: ['ayıp etmek', 'ayıp olmak'],
  kusur: ['kusura bakmamak', 'kusur bulmak'],

  /* ---------------- society, law, politics ---------------- */

  hak: ['hak etmek', 'hakkını aramak', 'hak ihlali'],
  yasa: ['yasa çıkarmak', 'yasayı uygulamak', 'yasaya aykırı'],
  kanun: ['kanun çıkarmak', 'kanuna uymak', 'kanun önünde eşitlik'],
  dava: ['dava açmak', 'davayı kazanmak', 'davadan vazgeçmek'],
  ceza: ['ceza vermek', 'ceza almak', 'para cezası'],
  delil: ['delil sunmak', 'delil yetersizliği'],
  itiraz: ['itiraz etmek', 'itirazı reddetmek'],
  seçim: ['seçime katılmak', 'seçim kazanmak', 'erken seçim'],
  demokrasi: ['demokrasiyi güçlendirmek', 'demokratik seçim'],
  göç: ['göç etmek', 'göç dalgası', 'zorunlu göç'],
  eşitsizlik: ['eşitsizliği azaltmak', 'gelir eşitsizliği'],
  yoksulluk: ['yoksullukla mücadele', 'yoksulluk sınırı'],
  istihdam: ['istihdam yaratmak', 'istihdam oranı'],
  dayanışma: ['dayanışma göstermek', 'toplumsal dayanışma'],
  ayrımcılık: ['ayrımcılık yapmak', 'ayrımcılığa uğramak'],
  kimlik: ['kimlik göstermek', 'kültürel kimlik'],
  müdahale: ['müdahale etmek', 'erken müdahale'],
  tedbir: ['tedbir almak', 'tedbiri kaldırmak'],
  yetki: ['yetki vermek', 'yetkiyi devretmek', 'yetki aşımı'],
  hizmet: ['hizmet vermek', 'hizmetten yararlanmak', 'kamu hizmeti'],
  talep: ['talepte bulunmak', 'talebi karşılamak', 'yüksek talep'],
  kabul: ['kabul etmek', 'kabul görmek'],

  /* ---------------- environment ---------------- */

  çevre: ['çevreyi korumak', 'çevre kirliliği', 'çevre dostu'],
  enerji: ['enerji harcamak', 'enerji tasarrufu', 'yenilenebilir enerji'],
  atık: ['atık üretmek', 'atığı geri dönüştürmek'],
  deprem: ['deprem olmak', 'depreme dayanıklı'],
  kirlilik: ['kirliliği azaltmak', 'hava kirliliği'],
  iklim: ['iklim değişikliği', 'iklime uyum sağlamak'],

  /* ---------------- media and technology ---------------- */

  haber: ['haber vermek', 'haber almak', 'son dakika haberi'],
  yayın: ['yayın yapmak', 'canlı yayın', 'yayına girmek'],
  reklam: ['reklam yapmak', 'reklam vermek'],
  yorum: ['yorum yapmak', 'yorumu silmek'],
  içerik: ['içerik üretmek', 'içerik paylaşmak'],
  paylaşım: ['paylaşım yapmak', 'paylaşımı silmek'],
  bildirim: ['bildirim almak', 'bildirimleri kapatmak'],
  güvenlik: ['güvenliği sağlamak', 'güvenlik açığı', 'veri güvenliği'],
  gizlilik: ['gizlilik ayarları', 'gizliliği ihlal etmek'],
  şifre: ['şifre belirlemek', 'şifreyi değiştirmek', 'güçlü şifre'],
  bağlantı: ['bağlantı kurmak', 'bağlantı kopmak', 'internet bağlantısı'],
  uygulama: ['uygulama indirmek', 'uygulamayı güncellemek'],
  güncelleme: ['güncelleme yapmak', 'güvenlik güncellemesi'],
  cihaz: ['cihazı kullanmak', 'akıllı cihaz'],

  /* ---------------- relationships and daily life ---------------- */

  ilişki: ['ilişki kurmak', 'ilişkiyi sürdürmek', 'ilişkiyi bitirmek'],
  arkadaşlık: ['arkadaşlık kurmak', 'arkadaşlığı sürdürmek'],
  düğün: ['düğün yapmak', 'düğüne gitmek'],
  nişan: ['nişan takmak', 'nişan atmak'],
  evlilik: ['evlilik teklifi', 'evlilik yıldönümü'],
  ziyaret: ['ziyaret etmek', 'ziyarete gitmek'],
  davet: ['davet etmek', 'daveti kabul etmek'],
  hediye: ['hediye almak', 'hediye vermek', 'hediye paketi'],
  ihtiyaç: ['ihtiyaç duymak', 'ihtiyacı karşılamak', 'acil ihtiyaç'],
  fark: ['fark etmek', 'fark yaratmak', 'aradaki fark'],
  değer: ['değer vermek', 'değer kazanmak', 'değerini bilmek'],
  durum: ['durumu değerlendirmek', 'acil durum', 'duruma göre'],
  olay: ['olay çıkarmak', 'olayı aydınlatmak'],
  süre: ['süre vermek', 'süreyi uzatmak', 'süre dolmak'],
  miktar: ['miktarı belirlemek', 'yeterli miktar'],
  kalite: ['kaliteyi artırmak', 'yüksek kalite'],
  avantaj: ['avantaj sağlamak', 'avantajdan yararlanmak'],
  seçenek: ['seçenek sunmak', 'seçenekleri değerlendirmek'],
  kapsam: ['kapsamını genişletmek', 'kapsam dışı'],
  denge: ['denge kurmak', 'dengeyi korumak', 'iş-yaşam dengesi'],
  öncelik: ['öncelik vermek', 'önceliği belirlemek'],
  kaza: ['kaza yapmak', 'kaza geçirmek', 'trafik kazası'],
  tehlike: ['tehlikeye atmak', 'tehlike altında', 'tehlikeyi göze almak'],
  /* ---------------- verbs that need an object to mean anything ---------------- */

  düşünmek: ['iyi düşünmek', 'bir daha düşünmek', 'düşünüp taşınmak'],
  inanmak: ['inanmak zor', 'gözlerine inanamamak', 'sözüne inanmak'],
  unutmak: ['adını unutmak', 'unutup gitmek', 'unutulmaz'],
  hatırlamak: ['yanlış hatırlamak', 'hatırladığım kadarıyla'],
  anlatmak: ['derdini anlatmak', 'baştan anlatmak', 'anlatıp durmak'],
  'açıklamak': ['sebebini açıklamak', 'kamuoyuna açıklamak', 'ayrıntılı açıklamak'],
  'gelişmek': ['hızla gelişmek', 'olaylar gelişmek'],
  'başarmak': ['başarmak için çalışmak', 'sonunda başarmak'],
  kaybetmek: ['zaman kaybetmek', 'umudunu kaybetmek', 'maçı kaybetmek'],
  'katılmak': ['toplantıya katılmak', 'fikre katılmak', 'yarışmaya katılmak'],
  'sağlamak': ['fayda sağlamak', 'güvenliği sağlamak', 'katılım sağlamak'],
  artmak: ['hızla artmak', 'talep artmak'],
  azalmak: ['giderek azalmak', 'talep azalmak'],
  kurmak: ['şirket kurmak', 'cümle kurmak', 'hayal kurmak', 'ilişki kurmak'],
  korumak: ['sağlığını korumak', 'çevreyi korumak', 'sırrı korumak'],
  'vazgeçmek': ['fikrinden vazgeçmek', 'kolay kolay vazgeçmemek'],
  'alışmak': ['iklime alışmak', 'yeni işe alışmak'],
  'davranmak': ['dikkatli davranmak', 'soğuk davranmak', 'adil davranmak'],
  engellemek: ['yayılmasını engellemek', 'girişini engellemek'],
  ilgilenmek: ['konuyla ilgilenmek', 'müşteriyle ilgilenmek'],
  'önermek': ['çözüm önermek', 'aday önermek'],
  'kabul etmek': ['teklifi kabul etmek', 'hatayı kabul etmek', 'şartları kabul etmek'],
  reddetmek: ['teklifi reddetmek', 'kesinlikle reddetmek'],
  'fark etmek': ['farkına varmak', 'hemen fark etmek', 'fark etmez'],
  savunmak: ['görüşünü savunmak', 'tezini savunmak', 'hakkını savunmak'],
  eleştirmek: ['sert eleştirmek', 'açıkça eleştirmek'],
  vurgulamak: ['önemini vurgulamak', 'özellikle vurgulamak'],
  'değerlendirmek': ['fırsatı değerlendirmek', 'başvuruyu değerlendirmek'],
  'gerçekleştirmek': ['hayalini gerçekleştirmek', 'projeyi gerçekleştirmek'],
  etkilemek: ['olumsuz etkilemek', 'derinden etkilemek'],
  kapsamak: ['geniş bir alanı kapsamak', 'kapsam dışı kalmak'],
  'üstlenmek': ['sorumluluğu üstlenmek', 'görevi üstlenmek', 'masrafı üstlenmek'],
  sınırlamak: ['harcamayı sınırlamak', 'yetkiyi sınırlamak'],
  genişletmek: ['kapsamı genişletmek', 'ufkunu genişletmek'],
  yansıtmak: ['gerçeği yansıtmak', 'görüşünü yansıtmak'],
  'kaçınmak': ['tartışmadan kaçınmak', 'riskten kaçınmak'],
  kanıtlamak: ['iddiasını kanıtlamak', 'kendini kanıtlamak'],
  'sürdürmek': ['çalışmaları sürdürmek', 'hayatını sürdürmek'],
  yönlendirmek: ['müşteriyi yönlendirmek', 'tartışmayı yönlendirmek'],

  /* ---------------- money and business ---------------- */

  ekonomi: ['ekonomi büyümek', 'ekonomiyi canlandırmak', 'serbest ekonomi'],
  faiz: ['faiz oranı', 'faiz artırmak', 'faiz indirimi'],
  girişim: ['girişimde bulunmak', 'yeni bir girişim'],
  borsa: ['borsaya girmek', 'borsada işlem görmek'],
  hisse: ['hisse almak', 'hisse senedi', 'hisse değeri'],
  durgunluk: ['ekonomik durgunluk', 'durgunluğa girmek'],
  'gümrük': ['gümrükten geçmek', 'gümrük vergisi'],
  pazarlama: ['pazarlama stratejisi', 'dijital pazarlama'],
  tedarik: ['tedarik etmek', 'tedarik zinciri'],
  ticaret: ['ticaret yapmak', 'dış ticaret', 'serbest ticaret'],
  sanayi: ['ağır sanayi', 'sanayi bölgesi'],
  servet: ['servet edinmek', 'servetini kaybetmek'],
  menfaat: ['menfaat sağlamak', 'ortak menfaat', 'menfaat çatışması'],
  'mülk': ['mülk edinmek', 'mülk sahibi'],
  emlak: ['emlak fiyatları', 'emlak vergisi'],
  'inşaat': ['inşaat halinde', 'inşaat sektörü'],
  fayda: ['fayda sağlamak', 'faydası dokunmak', 'karşılıklı fayda'],
  'maliye': ['maliye politikası', 'Maliye Bakanlığı'],

  /* ---------------- state and society ---------------- */

  devlet: ['devlet kurmak', 'devlet dairesi', 'devlet desteği'],
  'hükümet': ['hükümet kurmak', 'hükümeti düşürmek', 'hükümet açıklaması'],
  halk: ['halkın desteği', 'halka açık', 'halk oylaması'],
  millet: ['millet iradesi', 'milletçe'],
  meclis: ['meclise sunmak', 'meclisten geçmek', 'meclis kararı'],
  idare: ['idare etmek', 'idare amiri'],
  'nüfus': ['nüfus artışı', 'nüfus sayımı', 'nüfus yoğunluğu'],
  'yargı': ['yargıya başvurmak', 'yargı kararı', 'bağımsız yargı'],
  'savcı': ['savcı soruşturma açmak', 'başsavcı'],
  'sanık': ['sanık ifadesi', 'sanığı savunmak'],
  'tanık': ['tanık dinlemek', 'tanıklık etmek', 'görgü tanığı'],
  'yürürlük': ['yürürlüğe girmek', 'yürürlükten kaldırmak'],
  'mülteci': ['mülteci kampı', 'mülteci statüsü'],
  emniyet: ['emniyet kemeri', 'emniyet tedbiri'],
  asker: ['askere gitmek', 'asker ocağı'],
  silah: ['silah kullanmak', 'silah bırakmak', 'silahlı çatışma'],
  'şiddet': ['şiddet uygulamak', 'şiddete başvurmak', 'aile içi şiddet'],
  memur: ['devlet memuru', 'memur olmak'],
  mahremiyet: ['mahremiyeti korumak', 'özel hayatın mahremiyeti'],

  /* ---------------- technology ---------------- */

  teknoloji: ['teknolojiyi kullanmak', 'ileri teknoloji', 'teknoloji şirketi'],
  bilgisayar: ['bilgisayar kullanmak', 'bilgisayarı açmak', 'dizüstü bilgisayar'],
  internet: ['internete girmek', 'internet bağlantısı', 'internetten almak'],
  'yazılım': ['yazılım geliştirmek', 'yazılım güncellemesi'],
  dosya: ['dosya açmak', 'dosyayı kaydetmek', 'dosya paylaşmak'],
  ekran: ['ekrana bakmak', 'ekran görüntüsü', 'ekranı paylaşmak'],
  'paylaşmak': ['gönderi paylaşmak', 'ekranı paylaşmak', 'dertlerini paylaşmak'],
  indirmek: ['dosya indirmek', 'uygulama indirmek'],
  'yapay zekâ': ['yapay zekâ modeli', 'yapay zekâ kullanmak'],
  'kullanıcı': ['kullanıcı adı', 'kullanıcı deneyimi', 'aktif kullanıcı'],
  'şarj': ['şarj etmek', 'şarjı bitmek', 'şarj aleti'],
  'gönderi': ['gönderi paylaşmak', 'gönderiyi silmek'],
  'beğeni': ['beğeni almak', 'beğeni toplamak'],
  'takipçi': ['takipçi kazanmak', 'takipçi sayısı'],
  'tarayıcı': ['tarayıcıyı açmak', 'tarayıcı geçmişi'],
  sunucu: ['sunucuya bağlanmak', 'sunucu hatası'],
  'etkileşim': ['etkileşime girmek', 'etkileşim oranı'],
  'yüklemek': ['dosya yüklemek', 'programı yüklemek'],
  'tıklamak': ['bağlantıya tıklamak', 'çift tıklamak'],
  kaydetmek: ['dosyayı kaydetmek', 'not kaydetmek'],
  silmek: ['dosyayı silmek', 'mesajı silmek'],
  güncellemek: ['uygulamayı güncellemek', 'bilgileri güncellemek'],

  /* ---------------- feelings and character ---------------- */

  'hayal kırıklığı': ['hayal kırıklığına uğramak', 'büyük bir hayal kırıklığı'],
  rahatlama: ['rahatlama hissetmek', 'derin bir rahatlama'],
  'şaşırmak': ['çok şaşırmak', 'şaşırıp kalmak'],
  utanmak: ['utanıp kızarmak', 'utanmadan söylemek'],
  'güvenmek': ['kendine güvenmek', 'sözüne güvenmek'],
  his: ['his uyandırmak', 'garip bir his', 'hislerini gizlemek'],
  'hafıza': ['hafızasında kalmak', 'hafızayı güçlendirmek', 'hafıza kaybı'],
  'zekâ': ['zekâ testi', 'keskin zekâ'],
  ahlak: ['ahlak kuralları', 'iş ahlakı'],
  terbiye: ['terbiye görmek', 'terbiyesizlik etmek'],
  'şefkat': ['şefkat göstermek', 'anne şefkati'],
  keder: ['keder içinde', 'kedere boğulmak'],
  azim: ['azim göstermek', 'azimle çalışmak'],
  kader: ['kadere inanmak', 'kaderin cilvesi'],
  bereket: ['bereket getirmek', 'bolluk ve bereket'],
  'hürmet': ['hürmet göstermek', 'hürmeten'],
  tabiat: ['tabiat şartları', 'insan tabiatı'],

  /* ---------------- university and school ---------------- */

  'üniversite': ['üniversiteye girmek', 'üniversiteyi kazanmak', 'üniversite sınavı'],
  'fakülte': ['fakülteye kaydolmak', 'tıp fakültesi'],
  lisans: ['lisans eğitimi', 'lisans mezunu'],
  doktora: ['doktora yapmak', 'doktora tezi'],
  'dönem': ['dönem sonu', 'güz dönemi', 'dönem ödevi'],
  yurt: ['yurtta kalmak', 'öğrenci yurdu'],
  final: ['finale girmek', 'final sınavı'],
  staj: ['staj yapmak', 'zorunlu staj'],
  mezuniyet: ['mezuniyet töreni', 'mezuniyet tezi'],
  'devamsızlık': ['devamsızlıktan kalmak', 'devamsızlık sınırı'],

  /* ---------------- people and relationships ---------------- */

  dostluk: ['dostluk kurmak', 'dostluğu bozmak'],
  boşanma: ['boşanma davası', 'boşanma kararı'],
  'ayrılık': ['ayrılık acısı', 'ayrılığa dayanmak'],
  sevgili: ['sevgilisiyle ayrılmak', 'eski sevgili'],
  'tanışmak': ['tanışmak istemek', 'yeni insanlarla tanışmak'],
  'görüşmek': ['yüz yüze görüşmek', 'yarın görüşmek'],
  evlenmek: ['evlenme teklifi', 'genç yaşta evlenmek'],
  'nişanlanmak': ['nişanlanıp evlenmek'],
  'kıskanmak': ['delice kıskanmak', 'kardeşini kıskanmak'],
  'küsmek': ['küsüp gitmek', 'birbirine küsmek'],
  'barışmak': ['barışıp anlaşmak', 'kavga edip barışmak'],

  /* ---------------- media ---------------- */

  gazete: ['gazete okumak', 'gazetede çıkmak', 'günlük gazete'],
  dergi: ['dergi çıkarmak', 'aylık dergi'],
  kanal: ['kanal değiştirmek', 'haber kanalı'],
  'röportaj': ['röportaj yapmak', 'röportaj vermek'],
  muhabir: ['muhabir göndermek', 'savaş muhabiri'],
  'manşet': ['manşete taşımak', 'manşetten vermek'],
  duyuru: ['duyuru yapmak', 'duyuruyu paylaşmak'],
  'yayımlamak': ['makale yayımlamak', 'kitap yayımlamak'],
  sahne: ['sahneye çıkmak', 'sahne almak', 'son sahne'],
  oyuncu: ['baş oyuncu', 'oyuncu kadrosu'],
  'yönetmen': ['yönetmen koltuğu', 'ödüllü yönetmen'],
  senaryo: ['senaryo yazmak', 'en kötü senaryo'],

  /* ---------------- health ---------------- */

  ameliyat: ['ameliyat olmak', 'ameliyata girmek', 'acil ameliyat'],
  'beslenme': ['dengeli beslenme', 'beslenme alışkanlığı'],
  'bağımlılık': ['bağımlılık yapmak', 'bağımlılıktan kurtulmak'],
  'iyileşme': ['iyileşme süreci', 'hızlı iyileşme'],
  'bağışıklık': ['bağışıklık sistemi', 'bağışıklığı güçlendirmek'],
  'virüs': ['virüs kapmak', 'virüs yayılmak'],
  'zayıflamak': ['hızla zayıflamak', 'beş kilo zayıflamak'],
  mide: ['midesi bulanmak', 'mide ağrısı', 'mide bulantısı'],
  karantina: ['karantinaya girmek', 'karantinada kalmak'],
  hijyen: ['hijyen kurallarına uymak', 'kişisel hijyen'],
  terapi: ['terapiye gitmek', 'terapi görmek'],
  depresyon: ['depresyona girmek', 'depresyon tedavisi'],

  /* ---------------- nature ---------------- */

  'doğa': ['doğayı korumak', 'doğa yürüyüşü'],
  orman: ['orman yangını', 'ormanı korumak'],
  nehir: ['nehir kenarı', 'nehir taşmak'],
  'göl': ['göl kenarında', 'tuz gölü'],
  'ağaç': ['ağaç dikmek', 'ağaç gölgesi'],
  toprak: ['toprağı sürmek', 'verimli toprak', 'toprağa vermek'],
  sel: ['sel baskını', 'sel felaketi'],
  kuraklık: ['kuraklık yaşanmak', 'şiddetli kuraklık'],
  'tür': ['nesli tükenen tür', 'yeni bir tür'],
  saha: ['sahaya çıkmak', 'saha çalışması'],
  turnuva: ['turnuvaya katılmak', 'turnuvayı kazanmak'],
  madalya: ['madalya kazanmak', 'altın madalya'],
  'koşu': ['koşuya çıkmak', 'sabah koşusu'],
  'yüzme': ['yüzme kursu', 'yüzme havuzu'],

  /* ---------------- law and administration ---------------- */

  hukuk: ['hukuk devleti', 'hukuka aykırı', 'hukuk fakültesi'],
  adalet: ['adalet aramak', 'adaleti sağlamak', 'Adalet Bakanlığı'],
  'hâkim': ['hâkim karar vermek', 'hâkim önüne çıkmak'],
  vekil: ['vekil tayin etmek', 'milletvekili'],
  mesuliyet: ['mesuliyet almak', 'mesuliyet sahibi'],
  vesika: ['vesika düzenlemek', 'vesikalık fotoğraf'],
  imza: ['imza atmak', 'imza toplamak', 'imza yetkisi'],
  teslim: ['teslim etmek', 'teslim almak', 'teslim tarihi'],

  /* ---------------- academic Ottoman register ---------------- */

  ilim: ['ilim öğrenmek', 'ilim adamı'],
  tecrübe: ['tecrübe kazanmak', 'acı tecrübe', 'tecrübeye dayanmak'],
  tahlil: ['tahlil yaptırmak', 'kan tahlili'],
  'münakaşa': ['münakaşa etmek', 'münakaşaya girmek'],
  usul: ['usule uygun', 'usul hatası'],
  kaide: ['kaideye uymak', 'genel kaide'],
  maksat: ['maksadı aşmak', 'asıl maksat'],
  gaye: ['gaye edinmek', 'nihai gaye'],
  vasıta: ['vasıta olmak', 'ulaşım vasıtası'],
  malumat: ['malumat sahibi', 'malumat vermek'],
  tesir: ['tesir etmek', 'tesiri altında kalmak'],
  tespit: ['tespit etmek', 'tespitte bulunmak'],
  'tesadüf': ['tesadüf eseri', 'tesadüfe bağlamak'],

  /* ---------------- house and daily objects ---------------- */

  koltuk: ['koltuğa oturmak', 'koltuk takımı'],
  'yastık': ['yastığa başını koymak', 'yastık kılıfı'],
  merdiven: ['merdiven çıkmak', 'merdivenden inmek'],
  'asansör': ['asansöre binmek', 'asansör bozuk'],
  balkon: ['balkona çıkmak', 'balkondan bakmak'],
  musluk: ['musluğu açmak', 'musluk damlamak'],
  ampul: ['ampulü değiştirmek', 'ampul yanmak'],
  priz: ['prize takmak', 'priz bozuk'],
  'battaniye': ['battaniye örtmek', 'kalın battaniye'],
  emlakçı: ['emlakçıya gitmek', 'emlakçıyla anlaşmak'],
  garaj: ['garaja park etmek', 'kapalı garaj'],
  'kapıcı': ['kapıcıya haber vermek', 'apartman kapıcısı'],

  /* ---------------- grammar words used in class ---------------- */

  rakam: ['rakamla yazmak', 'resmî rakamlar'],
  fiil: ['fiil çekimi', 'fiil kökü'],
  'sıfat': ['sıfat tamlaması', 'niteleme sıfatı'],
  misal: ['misal vermek', 'misal olarak'],
  sayfa: ['sayfayı çevirmek', 'ön sayfa'],
  nokta: ['noktayı koymak', 'önemli bir nokta', 'nokta atışı'],
  'şekil': ['şekil vermek', 'bu şekilde', 'şekil değiştirmek'],

  /* ---------------- body ---------------- */

  sinir: ['sinir olmak', 'sinirleri bozulmak', 'sinir sistemi'],
  'akciğer': ['akciğer kanseri', 'akciğer kapasitesi'],
  kas: ['kas geliştirmek', 'kas ağrısı'],
  organ: ['organ nakli', 'organ bağışı'],
  doku: ['doku örneği', 'bağ dokusu'],

  /* ---------------- literature and art ---------------- */

  edebiyat: ['edebiyat okumak', 'çağdaş edebiyat'],
  'şiir': ['şiir yazmak', 'şiir okumak', 'şiir kitabı'],
  'şair': ['büyük şair', 'şair ruhlu'],
  'hikâye': ['hikâye anlatmak', 'kısa hikâye', 'uzun hikâye'],
  sanat: ['sanat eseri', 'sanat yapmak', 'güzel sanatlar'],
  resim: ['resim yapmak', 'resim sergisi'],
  mimari: ['mimari tarz', 'mimari eser'],
  'tercüme': ['tercüme etmek', 'tercüme eser'],
  lisan: ['lisan öğrenmek', 'yabancı lisan'],

  /* ---------------- work ---------------- */

  'şirket': ['şirket kurmak', 'şirkette çalışmak', 'şirket sahibi'],
  'maaş': ['maaş almak', 'maaş zammı', 'maaşa zam yapmak'],
  mesai: ['mesai saatleri', 'fazla mesai', 'mesaiye kalmak'],
  'kazanç': ['kazanç sağlamak', 'net kazanç'],
  emek: ['emek vermek', 'emeği geçmek', 'emek yoğun'],
  'istifa etmek': ['istifasını sunmak', 'görevinden istifa etmek'],
  vazife: ['vazifesini yapmak', 'vazife bilinci'],
  tesis: ['tesis kurmak', 'sosyal tesis'],
  'mühür': ['mühür basmak', 'mühür vurmak'],

  /* ---------------- Phase 7: the verbs that need an object ---------------- */

  'değişmek': ['fikir değişmek', 'hava değişmek', 'bir şey değişmemek'],
  'karar vermek': ['hemen karar vermek', 'birlikte karar vermek'],
  'tercih etmek': ['yürümeyi tercih etmek', 'sessizliği tercih etmek'],
  'gerçekleşmek': ['hayali gerçekleşmek', 'plan gerçekleşmek'],
  'karşılaştırmak': ['fiyatları karşılaştırmak', 'iki metni karşılaştırmak'],
  'teşekkür etmek': ['içtenlikle teşekkür etmek', 'ayrıca teşekkür etmek'],
  'şikâyet etmek': ['gürültüden şikâyet etmek', 'resmen şikâyet etmek'],
  'tartışmak': ['konuyu tartışmak', 'uzun uzun tartışmak', 'açıkça tartışmak'],
  'dile getirmek': ['endişelerini dile getirmek', 'talebini dile getirmek'],
  'bahsetmek': ['bundan bahsetmek', 'kısaca bahsetmek'],
  'söz etmek': ['söz etmeye değer', 'hiç söz etmemek'],
  'değinmek': ['konuya değinmek', 'kısaca değinmek'],
  'neden olmak': ['kazaya neden olmak', 'gecikmeye neden olmak'],
  'sebep olmak': ['zarara sebep olmak', 'karışıklığa sebep olmak'],
  kaynaklanmak: ['ihmalden kaynaklanmak', 'yanlış anlaşılmadan kaynaklanmak'],
  'sonuçlanmak': ['anlaşmayla sonuçlanmak', 'başarısızlıkla sonuçlanmak'],
  etkilenmek: ['karardan etkilenmek', 'olumsuz etkilenmek'],
  ilgilendirmek: ['hepimizi ilgilendirmek', 'doğrudan ilgilendirmek'],
  'içermek': ['üç bölüm içermek', 'risk içermek'],
  'oluşmak': ['beş kişiden oluşmak', 'iki aşamadan oluşmak'],
  'meydana gelmek': ['kaza meydana gelmek', 'değişiklik meydana gelmek'],
  'sahip olmak': ['deneyime sahip olmak', 'hakka sahip olmak'],
  'ihtiyaç duymak': ['desteğe ihtiyaç duymak', 'zamana ihtiyaç duymak'],
  'yönetmek': ['toplantıyı yönetmek', 'ekibi yönetmek', 'krizi yönetmek'],
  planlamak: ['tatili planlamak', 'önceden planlamak'],
  'hazırlanmak': ['sınava hazırlanmak', 'yolculuğa hazırlanmak'],
  ilerlemek: ['hızla ilerlemek', 'adım adım ilerlemek'],
  'varsaymak': ['doğru varsaymak', 'aksini varsaymak'],
  'ileri sürmek': ['iddia ileri sürmek', 'gerekçe ileri sürmek'],
  'çürütmek': ['iddiayı çürütmek', 'tezi çürütmek'],
  'yol açmak': ['soruna yol açmak', 'tartışmaya yol açmak'],
  'teşvik etmek': ['katılımı teşvik etmek', 'yatırımı teşvik etmek'],
  'tahmin etmek': ['sonucu tahmin etmek', 'yaklaşık tahmin etmek'],
  raporlamak: ['aylık raporlamak', 'sonuçları raporlamak'],
  kolaylaştırmak: ['işlemi kolaylaştırmak', 'erişimi kolaylaştırmak'],

  /* ---------------- Phase 7: abstract nouns ---------------- */

  'gelişme': ['gelişme kaydetmek', 'son gelişmeler', 'olumlu gelişme'],
  'değişiklik': ['değişiklik yapmak', 'köklü değişiklik'],
  'koşul': ['koşul öne sürmek', 'çalışma koşulları', 'koşulsuz'],
  'gerçek': ['gerçeği söylemek', 'gerçekle yüzleşmek', 'gerçek dışı'],
  'imkân': ['imkân tanımak', 'imkân bulmak', 'imkânsız hâle gelmek'],
  'eğilim': ['eğilim göstermek', 'genel eğilim', 'artış eğilimi'],
  'istisna': ['istisna tanımak', 'istisnasız', 'kural dışı istisna'],
  'ayrıntı': ['ayrıntıya girmek', 'ayrıntılı bilgi', 'küçük bir ayrıntı'],
  'katkı': ['katkı sağlamak', 'katkıda bulunmak', 'katkı payı'],
  'süreç': ['süreci başlatmak', 'süreci hızlandırmak', 'uzun bir süreç'],
  'yaklaşım': ['yeni bir yaklaşım', 'yaklaşım benimsemek'],
  kapasite: ['kapasiteyi artırmak', 'tam kapasite', 'üretim kapasitesi'],
  'baskı': ['baskı yapmak', 'baskı altında kalmak', 'kamuoyu baskısı'],
  'güvence': ['güvence altına almak', 'iş güvencesi'],
  netice: ['netice almak', 'netice itibarıyla'],
  mesafe: ['mesafe koymak', 'mesafeli davranmak', 'uzun mesafe'],
  taraf: ['taraf tutmak', 'iki taraf', 'taraf olmak'],
  dezavantaj: ['dezavantaj yaratmak', 'avantaj ve dezavantaj'],

  /* ---------------- Phase 7: measure and standard ---------------- */

  kriter: ['kriter belirlemek', 'kriteri karşılamak', 'seçim kriterleri'],
  'gösterge': ['gösterge niteliğinde', 'ekonomik göstergeler'],
  'bağlam': ['bağlamdan koparmak', 'tarihsel bağlam', 'bu bağlamda'],
  'çıkarım': ['çıkarım yapmak', 'mantıksal çıkarım'],
  'örneklem': ['örneklem seçmek', 'örneklem büyüklüğü'],
  'değişken': ['bağımsız değişken', 'değişkeni kontrol etmek'],
  'geçerlilik': ['geçerlilik süresi', 'geçerliliğini yitirmek'],
  'güvenilirlik': ['güvenilirliği test etmek', 'güvenilirlik düzeyi'],
  'olgu': ['olguyu açıklamak', 'toplumsal olgu'],
  yorumlamak: ['sonucu yorumlamak', 'yanlış yorumlamak'],
  'sınırlılık': ['çalışmanın sınırlılıkları'],
  'hipotez': ['hipotez kurmak', 'hipotezi test etmek'],
  istatistik: ['istatistik tutmak', 'resmî istatistikler'],
  'ölçüm': ['ölçüm yapmak', 'ölçüm hatası'],
  'kuram': ['kuram geliştirmek', 'kuramsal çerçeve'],
  'evrim': ['evrim geçirmek', 'evrim teorisi'],
  'madde': ['madde eklemek', 'kimyasal madde', 'yasa maddesi'],
  'element': ['kimyasal element', 'element tablosu'],

  /* ---------------- Phase 7: adjectives ---------------- */

  'önemli': ['önemli bir konu', 'önemli ölçüde', 'daha da önemlisi'],
  'gerekli': ['gerekli önlem', 'gerekli görmek', 'gerekli belgeler'],
  'mümkün': ['mümkün olmak', 'mümkün mertebe', 'mümkün olduğunca'],
  'imkânsız': ['imkânsız hâle gelmek', 'neredeyse imkânsız'],
  'karmaşık': ['karmaşık bir sorun', 'karmaşık yapı'],
  'yeterli': ['yeterli bilgi', 'yeterli görmek', 'yeterli olmamak'],
  'güvenilir': ['güvenilir kaynak', 'güvenilir bir insan'],
  'yaygın': ['yaygın olarak', 'yaygın bir inanış', 'yaygınlaşmak'],
  'etkili': ['etkili bir yöntem', 'etkili olmak', 'etkili konuşma'],
  'verimli': ['verimli çalışmak', 'verimli toprak'],
  'kararlı': ['kararlı durmak', 'kararlı bir tutum'],
  'esnek': ['esnek çalışma', 'esnek olmak'],
  'katı': ['katı kurallar', 'katı davranmak'],
  'anlamlı': ['anlamlı bir fark', 'istatistiksel olarak anlamlı'],
  'geçerli': ['geçerli sebep', 'geçerli bir bilet'],
  'kapsamlı': ['kapsamlı bir çalışma', 'kapsamlı değişiklik'],
  'yüzeysel': ['yüzeysel bir bakış', 'yüzeysel kalmak'],
  'nesnel': ['nesnel ölçüt', 'nesnel değerlendirme'],
  'öznel': ['öznel yorum', 'öznel bir bakış'],
  'makul': ['makul bir süre', 'makul fiyat'],
  'olağanüstü': ['olağanüstü hâl', 'olağanüstü bir başarı'],
  'titiz': ['titiz çalışmak', 'titiz bir inceleme'],

  /* ---------------- Phase 7: civic and institutional ---------------- */

  'muhalefet': ['muhalefet partisi', 'muhalefet etmek'],
  'seçmen': ['seçmen kütüğü', 'seçmen davranışı'],
  sendika: ['sendikaya üye olmak', 'sendika temsilcisi'],
  skandal: ['skandal patlamak', 'yolsuzluk skandalı'],
  yolsuzluk: ['yolsuzluk iddiası', 'yolsuzlukla mücadele'],
  'şeffaflık': ['şeffaflık ilkesi', 'şeffaflığı artırmak'],
  'algı': ['algı yaratmak', 'algı yönetimi', 'kamuoyu algısı'],
  toplum: ['toplumu ilgilendirmek', 'sivil toplum', 'toplumsal cinsiyet'],
  kamuoyu: ['kamuoyu oluşturmak', 'kamuoyu araştırması'],
  siyaset: ['siyasete atılmak', 'siyaset yapmak'],
  'kalkınma': ['sürdürülebilir kalkınma', 'kalkınma planı'],
  'kuşak': ['genç kuşak', 'kuşak çatışması'],
  egemenlik: ['egemenlik hakkı', 'ulusal egemenlik'],
  meşruiyet: ['meşruiyet kazanmak', 'meşruiyeti sorgulamak'],
  'özerklik': ['özerklik tanımak', 'mali özerklik'],
  'bağımsızlık': ['bağımsızlık ilan etmek', 'yargı bağımsızlığı'],
  ideoloji: ['ideoloji üretmek', 'ideolojik bakış'],
  vatan: ['vatan sevgisi', 'vatana dönmek'],
  hakikat: ['hakikati aramak', 'acı hakikat'],
  'zulüm': ['zulüm görmek', 'zulme uğramak'],

  /* ---------------- Phase 7: work and paperwork ---------------- */

  'kuruluş': ['kuruluş yılı', 'sivil toplum kuruluşu'],
  'şube': ['şube açmak', 'şube müdürü'],
  yetkili: ['yetkiliyle görüşmek', 'yetkili makam'],
  'görevli': ['görevli memur', 'nöbetçi görevli'],
  temsilci: ['temsilci atamak', 'bölge temsilcisi'],
  'sözcü': ['sözcü açıklama yapmak', 'parti sözcüsü'],
  evrak: ['evrak hazırlamak', 'evrak eksiği'],
  'prosedür': ['prosedürü işletmek', 'standart prosedür'],
  'dilek': ['dilek dilemek', 'iyi dilekler'],
  'arşiv': ['arşive kaldırmak', 'arşiv taraması'],
  'katılımcı': ['katılımcı sayısı', 'katılımcı listesi'],
  'işveren': ['işveren sorumluluğu', 'işveren vekili'],
  'çalışan': ['çalışan memnuniyeti', 'tam zamanlı çalışan'],
  personel: ['personel alımı', 'personel eğitimi'],
  pozisyon: ['pozisyon açmak', 'açık pozisyon'],
  unvan: ['unvan almak', 'akademik unvan'],
  emekli: ['emekli olmak', 'emekli maaşı'],
  'meslektaş': ['meslektaş dayanışması'],

  /* ---------------- Phase 7: personality ---------------- */

  'cömert': ['cömert davranmak', 'cömert bir insan'],
  cimri: ['cimrilik etmek'],
  kibar: ['kibar davranmak', 'kibar bir dil'],
  'utangaç': ['utangaç bir çocuk'],
  'çalışkan': ['çalışkan öğrenci', 'çalışkan bir ekip'],
  tembel: ['tembellik etmek'],
  bencil: ['bencil davranmak'],
  'alçakgönüllü': ['alçakgönüllü olmak'],
  kibirli: ['kibirli davranmak'],
  'hırslı': ['hırslı bir insan'],
  'inatçı': ['inatçılık etmek'],
  'düşünceli': ['düşünceli davranmak'],
  samimi: ['samimi olmak', 'samimi bir dost'],
  'duyarlı': ['duyarlı davranmak', 'çevreye duyarlı'],
  'anlayış': ['anlayış göstermek', 'anlayışla karşılamak'],
  'hoşgörü': ['hoşgörü göstermek'],
  'sadakat': ['sadakat göstermek'],
  samimiyet: ['samimiyetle söylemek'],

  /* ---------------- Phase 7: emotions ---------------- */

  'endişe': ['endişe duymak', 'endişe verici', 'endişeleri gidermek'],
  'suçluluk': ['suçluluk duygusu', 'suçluluk hissetmek'],
  'kıskançlık': ['kıskançlık krizi'],
  'sevgi': ['sevgi göstermek', 'sevgi beslemek', 'sevgiyle yaklaşmak'],
  'gerginlik': ['gerginliği azaltmak', 'gerginlik tırmanmak'],
  'yorgunluk': ['yorgunluk atmak', 'yorgunluk belirtisi'],
  'şaşkınlık': ['şaşkınlık yaratmak', 'şaşkınlıkla karşılamak'],
  'heves': ['heves etmek', 'hevesi kaçmak'],
  'irade': ['irade göstermek', 'siyasi irade'],
  'kararsız': ['kararsız kalmak'],
  'umutsuz': ['umutsuzluğa kapılmak'],
  'minnettar': ['minnettar kalmak'],

  /* ---------------- Phase 7: money ---------------- */

  'yatırımcı': ['yatırımcı çekmek', 'yabancı yatırımcı'],
  lojistik: ['lojistik destek', 'lojistik sorun'],
  'altyapı': ['altyapı yatırımı', 'altyapı çalışması'],
  prim: ['prim almak', 'satış primi'],
  ikramiye: ['ikramiye dağıtmak', 'bayram ikramiyesi'],
  'tüccar': ['tüccar zihniyeti'],
  iktisat: ['iktisat okumak', 'iktisat politikası'],

  /* ---------------- Phase 7: law ---------------- */

  anayasa: ['anayasa değişikliği', 'anayasaya aykırı'],
  'yönetmelik': ['yönetmelik çıkarmak', 'yönetmeliğe uygun'],
  mahkeme: ['mahkemeye başvurmak', 'mahkeme kararı'],
  avukat: ['avukat tutmak', 'avukatla görüşmek'],
  'yükümlülük': ['yükümlülüğünü yerine getirmek', 'yasal yükümlülük'],
  'ihlal': ['ihlal etmek', 'hak ihlali'],
  'şahit': ['şahitlik etmek', 'şahit göstermek'],
  hiyerarşi: ['katı hiyerarşi', 'hiyerarşik yapı'],
  'şema': ['şema çizmek', 'organizasyon şeması'],

  /* ---------------- Phase 7: literary register ---------------- */

  'yalnızlık': ['yalnızlık çekmek', 'yalnızlığa alışmak'],
  gurbet: ['gurbete çıkmak', 'gurbet elde'],
  'üslup': ['üslup sahibi', 'anlatım üslubu'],
  'anlatıcı': ['birinci tekil anlatıcı'],
  kurgu: ['kurgu dışı', 'kurgusal metin'],
  dize: ['dize kurmak', 'ilk dize'],
  deneme: ['deneme yazmak', 'deneme türü'],
  'ahenk': ['ahenk sağlamak', 'ses ahengi'],
  'övgü': ['övgü almak', 'övgüyle söz etmek'],
  benzetme: ['benzetme yapmak'],
  ironi: ['ironi yapmak', 'acı bir ironi'],
  'önerme': ['önerme kurmak', 'doğru önerme'],
  'tenkit': ['tenkit etmek'],
  'tevazu': ['tevazu göstermek'],
  ihtiyat: ['ihtiyatlı olmak', 'ihtiyatı elden bırakmamak'],
  'bariz': ['bariz bir fark'],
  'seçkin': ['seçkin bir çevre'],

  /* ================================================================== */
  /* Phase 8 — A1/A2, where coverage was 9% and 19%                      */
  /* ================================================================== */

  /* ---- the core verbs: what they actually combine with ---- */

  'olmak': ['hasta olmak', 'doktor olmak', 'geç olmak', 'ne oldu'],
  'yapmak': ['yemek yapmak', 'ödev yapmak', 'spor yapmak', 'alışveriş yapmak'],
  'gitmek': ['okula gitmek', 'işe gitmek', 'yürüyerek gitmek'],
  'gelmek': ['eve gelmek', 'geç gelmek', 'aklına gelmek'],
  'almak': ['ders almak', 'nefes almak', 'hediye almak', 'izin almak'],
  'vermek': ['ders vermek', 'sözü vermek', 'ara vermek'],
  'görmek': ['rüya görmek', 'zarar görmek', 'iyi görmek'],
  'bakmak': ['pencereden bakmak', 'çocuğa bakmak', 'saate bakmak'],
  'bilmek': ['yolu bilmek', 'cevabı bilmek', 'Türkçe bilmek'],
  'istemek': ['su istemek', 'yardım istemek', 'izin istemek'],
  'sevmek': ['çok sevmek', 'müzik sevmek'],
  'içmek': ['çay içmek', 'su içmek', 'sigara içmek'],
  'okumak': ['kitap okumak', 'üniversitede okumak', 'yüksek sesle okumak'],
  'yazmak': ['mektup yazmak', 'not yazmak', 'ödev yazmak'],
  'konuşmak': ['Türkçe konuşmak', 'telefonda konuşmak', 'açık konuşmak'],
  'dinlemek': ['müzik dinlemek', 'ders dinlemek', 'dikkatle dinlemek'],
  'anlamak': ['yanlış anlamak', 'iyi anlamak'],
  'söylemek': ['doğruyu söylemek', 'şarkı söylemek', 'yalan söylemek'],
  'çalışmak': ['çok çalışmak', 'sınava çalışmak', 'şirkette çalışmak'],
  'oturmak': ['sandalyeye oturmak', 'evde oturmak'],
  'kalkmak': ['erken kalkmak', 'yataktan kalkmak'],
  'uyumak': ['erken uyumak', 'derin uyumak'],
  'yürümek': ['hızlı yürümek', 'yürüyüşe çıkmak'],
  'beklemek': ['sırada beklemek', 'biraz beklemek'],
  'başlamak': ['derse başlamak', 'işe başlamak', 'yeni başlamak'],
  'bitirmek': ['işi bitirmek', 'okulu bitirmek'],
  'yaşamak': ['İstanbul’da yaşamak', 'mutlu yaşamak'],
  'bulmak': ['iş bulmak', 'çözüm bulmak', 'zaman bulmak'],
  'getirmek': ['su getirmek', 'yanında getirmek'],
  'sormak': ['soru sormak', 'yol sormak', 'fiyat sormak'],
  'durmak': ['ayakta durmak', 'bir dakika durmak'],
  'duymak': ['ses duymak', 'haber duymak'],
  'açmak': ['kapıyı açmak', 'ışığı açmak', 'hesap açmak'],
  'kapatmak': ['kapıyı kapatmak', 'telefonu kapatmak'],
  'giymek': ['ceket giymek', 'ayakkabı giymek'],
  'yatmak': ['erken yatmak', 'hastaneye yatmak'],
  'demek': ['ne demek', 'yani demek', 'öyle demek'],
  'öğretmek': ['Türkçe öğretmek', 'ders öğretmek'],
  'cevaplamak': ['soruyu cevaplamak', 'kısaca cevaplamak'],
  'yardım etmek': ['yardım etmek istemek', 'birine yardım etmek'],

  /* ---- A2 verb pairs, taught through what they take ---- */

  'taşımak': ['eşya taşımak', 'sorumluluk taşımak'],
  'temizlemek': ['evi temizlemek', 'iyice temizlemek'],
  'dokunmak': ['eliyle dokunmak', 'cama dokunmak'],
  'korkmak': ['köpekten korkmak', 'çok korkmak'],
  'gülmek': ['yüksek sesle gülmek', 'birine gülmek'],
  'kızmak': ['birine kızmak', 'çok kızmak'],
  'üzülmek': ['çok üzülmek', 'haberi duyup üzülmek'],
  'bağırmak': ['yüksek sesle bağırmak', 'birine bağırmak'],
  'uçmak': ['uçakla uçmak', 'yükseğe uçmak'],
  'yüzmek': ['denizde yüzmek', 'havuzda yüzmek'],
  'satmak': ['ucuza satmak', 'ev satmak'],
  'denemek': ['bir kere denemek', 'elbise denemek'],
  'binmek': ['otobüse binmek', 'ata binmek'],
  'inmek': ['otobüsten inmek', 'aşağı inmek'],
  'gezmek': ['şehri gezmek', 'müze gezmek'],
  'özlemek': ['ailesini özlemek', 'çok özlemek'],

  /* ---- food: what you do with it ---- */

  ekmek: ['ekmek almak', 'taze ekmek', 'ekmek kesmek'],
  peynir: ['beyaz peynir', 'peynir ekmek'],
  yumurta: ['yumurta pişirmek', 'haşlanmış yumurta'],
  et: ['et yemek', 'kırmızı et', 'et suyu'],
  tavuk: ['tavuk çorbası', 'tavuk pişirmek'],
  'balık': ['balık tutmak', 'balık pişirmek', 'taze balık'],
  'çorba': ['çorba içmek', 'mercimek çorbası'],
  salata: ['salata yapmak', 'mevsim salatası'],
  meyve: ['meyve yemek', 'taze meyve', 'meyve suyu'],
  sebze: ['sebze yemeği', 'taze sebze'],
  elma: ['elma yemek', 'kırmızı elma'],
  domates: ['domates almak', 'domates salatası'],
  patates: ['patates kızartması', 'patates soymak'],
  'şeker': ['şeker koymak', 'şekersiz kahve'],
  tuz: ['tuz atmak', 'tuzsuz yemek'],
  zeytin: ['siyah zeytin', 'zeytin yemek'],
  'kahvaltı': ['kahvaltı yapmak', 'kahvaltı hazırlamak'],
  'çay': ['çay demlemek', 'çay içmek', 'bir bardak çay'],
  kahve: ['kahve içmek', 'Türk kahvesi', 'kahve yapmak'],
  su: ['su içmek', 'bir bardak su', 'su dökmek'],
  'süt': ['süt içmek', 'sıcak süt'],

  /* ---- places: what you do there ---- */

  ev: ['eve gitmek', 'ev tutmak', 'evde kalmak'],
  okul: ['okula gitmek', 'okulu bitirmek'],
  hastane: ['hastaneye gitmek', 'hastanede yatmak'],
  eczane: ['eczaneden almak', 'nöbetçi eczane'],
  market: ['markete gitmek', 'marketten almak'],
  banka: ['bankaya gitmek', 'banka hesabı'],
  otel: ['otelde kalmak', 'otel odası'],
  lokanta: ['lokantada yemek', 'lokantaya gitmek'],
  'havalimanı': ['havalimanına gitmek', 'havalimanında beklemek'],
  sokak: ['sokakta yürümek', 'ara sokak'],
  cadde: ['ana cadde', 'caddeden geçmek'],
  meydan: ['meydanda buluşmak', 'meydana çıkmak'],
  park: ['parkta oynamak', 'parka gitmek'],
  deniz: ['denize girmek', 'deniz kenarı'],
  'dağ': ['dağa çıkmak', 'dağ havası'],
  'şehir': ['şehir merkezi', 'büyük şehir'],
  'köy': ['köyde yaşamak', 'köye dönmek'],
  'ülke': ['ülkeye girmek', 'komşu ülke'],

  /* ---- adjectives: the nouns they actually modify ---- */

  'büyük': ['büyük şehir', 'büyük sorun', 'büyük fark'],
  'küçük': ['küçük çocuk', 'küçük bir sorun'],
  yeni: ['yeni bir şey', 'yepyeni', 'yeni başlamak'],
  eski: ['eski arkadaş', 'eski model'],
  'iyi': ['iyi insan', 'iyi günler', 'iyi olmak'],
  'kötü': ['kötü haber', 'kötü hissetmek'],
  'güzel': ['güzel bir gün', 'çok güzel'],
  uzun: ['uzun süre', 'uzun yol', 'uzun boylu'],
  'kısa': ['kısa süre', 'kısa saç', 'kısaca'],
  kolay: ['kolay gelsin', 'çok kolay'],
  zor: ['zor bir soru', 'zor durum', 'zorla'],
  'sıcak': ['sıcak hava', 'sıcak su', 'sıcak karşılamak'],
  'soğuk': ['soğuk hava', 'soğuk su', 'soğuk davranmak'],
  'hızlı': ['hızlı yürümek', 'hızlı tren'],
  'yavaş': ['yavaş yavaş', 'yavaş konuşmak'],
  temiz: ['temiz hava', 'temiz tutmak'],
  kirli: ['kirli çamaşır', 'kirli hava'],
  dolu: ['dolu otobüs', 'programı dolu'],
  'boş': ['boş yer', 'boş vakit', 'boşuna'],
  'açık': ['açık hava', 'açık konuşmak', 'kapı açık'],
  'kapalı': ['kapalı kapı', 'kapalı hava'],
  mutlu: ['mutlu olmak', 'mutlu yıllar'],
  'üzgün': ['üzgün görünmek', 'çok üzgün'],
  yorgun: ['yorgun düşmek', 'çok yorgun'],
  'aç': ['aç kalmak', 'çok aç'],
  hasta: ['hasta olmak', 'hasta bakmak'],
  ucuz: ['ucuza almak', 'çok ucuz'],
  'pahalı': ['pahalı olmak', 'çok pahalı'],
  'yakın': ['yakın arkadaş', 'yakında', 'eve yakın'],
  uzak: ['uzak durmak', 'çok uzak'],
  'doğru': ['doğru cevap', 'doğru söylemek', 'doğruca'],
  'yanlış': ['yanlış anlamak', 'yanlış numara'],

  /* ---- time ---- */

  zaman: ['zaman geçmek', 'zaman ayırmak', 'o zaman'],
  saat: ['saat kaç', 'saat başı', 'saatlerce'],
  'gün': ['gün geçmek', 'her gün', 'gün boyu'],
  hafta: ['gelecek hafta', 'hafta sonu'],
  ay: ['gelecek ay', 'ay başı'],
  'yıl': ['geçen yıl', 'yıl sonu', 'yıllarca'],
  sabah: ['sabah erken', 'sabaha karşı'],
  'akşam': ['akşam yemeği', 'akşam üstü'],
  gece: ['gece yarısı', 'gece boyu', 'iyi geceler'],
  erken: ['erken kalkmak', 'erken gelmek'],
  'geç': ['geç kalmak', 'geç saatte'],
  dakika: ['bir dakika', 'son dakika'],
  vakit: ['vakit ayırmak', 'vakit geçirmek', 'vaktinde'],

  /* ---- family and people ---- */

  aile: ['aile kurmak', 'geniş aile'],
  anne: ['anne olmak', 'anne baba'],
  baba: ['baba olmak', 'babaanne'],
  'kardeş': ['kardeş olmak', 'küçük kardeş'],
  'çocuk': ['çocuk sahibi olmak', 'küçük çocuk'],
  insan: ['insan hakları', 'iyi bir insan'],
  'arkadaş': ['arkadaş olmak', 'yakın arkadaş', 'arkadaş edinmek'],
  komşu: ['komşu ülke', 'yan komşu'],
  'öğrenci': ['öğrenci olmak', 'başarılı öğrenci'],
  'öğretmen': ['öğretmen olmak', 'sınıf öğretmeni'],
  doktor: ['doktora gitmek', 'doktor olmak'],
  misafir: ['misafir ağırlamak', 'misafir gelmek'],
  isim: ['isim vermek', 'ismi geçmek'],
  'yaş': ['yaş günü', 'kaç yaşında'],
  meslek: ['meslek sahibi', 'mesleğiniz ne'],

  /* ---- house and objects ---- */

  oda: ['oda tutmak', 'tek kişilik oda'],
  mutfak: ['mutfakta yemek yapmak', 'açık mutfak'],
  'kapı': ['kapıyı açmak', 'kapıyı çalmak', 'kapı önü'],
  pencere: ['pencereyi açmak', 'pencereden bakmak'],
  masa: ['masaya oturmak', 'masayı toplamak'],
  yatak: ['yatağa girmek', 'yatak odası'],
  anahtar: ['anahtarı kaybetmek', 'yedek anahtar'],
  telefon: ['telefon etmek', 'telefonu açmak', 'cep telefonu'],
  para: ['para kazanmak', 'para harcamak', 'para biriktirmek'],
  araba: ['araba kullanmak', 'arabaya binmek'],
  yol: ['yol sormak', 'yola çıkmak', 'yolu bulmak'],
  'iş': ['iş bulmak', 'işe gitmek', 'iş yapmak'],
  kitap: ['kitap okumak', 'kitap yazmak'],
  kalem: ['kalem almak', 'kurşun kalem'],
  soru: ['soru sormak', 'soru cevaplamak', 'zor soru'],
  cevap: ['cevap vermek', 'doğru cevap'],
  ders: ['ders çalışmak', 'ders almak', 'ders vermek'],
  hayat: ['hayat kurmak', 'hayatını kazanmak'],

  /* ---- body ---- */

  'baş': ['başı ağrımak', 'baş üstüne'],
  'göz': ['göz atmak', 'gözü kalmak', 'göze çarpmak'],
  el: ['el yıkamak', 'elini sıkmak', 'el ele'],
  ayak: ['ayakta durmak', 'ayak uydurmak'],
  'diş': ['diş fırçalamak', 'diş ağrısı'],
  'dil': ['dil öğrenmek', 'ana dil', 'dili dönmek'],
  kalp: ['kalp kırmak', 'kalbi çarpmak'],

  /* ---- A2 everyday ---- */

  'alışveriş': ['alışveriş yapmak', 'alışveriş listesi'],
  fiyat: ['fiyat sormak', 'fiyat artmak', 'uygun fiyat'],
  'müşteri': ['müşteri memnuniyeti', 'sadık müşteri'],
  'sağlık': ['sağlık ocağı', 'sağlığa zararlı'],
  'hastalık': ['hastalık geçirmek', 'bulaşıcı hastalık'],
  'ağrı': ['ağrı kesici', 'başı ağrımak'],
  'ateş': ['ateşi çıkmak', 'ateş ölçmek'],
  'ilaç': ['ilaç kullanmak', 'ilaç yazmak'],
  'hava durumu': ['hava durumuna bakmak'],
  'yağmur': ['yağmur yağmak', 'yağmura yakalanmak'],
  kar: ['kar yağmak', 'kar erimek'],
  'rüzgâr': ['rüzgâr esmek', 'sert rüzgâr'],
  seyahat: ['seyahat etmek', 'iş seyahati'],
  tatil: ['tatile çıkmak', 'yaz tatili'],
  bilet: ['bilet almak', 'gidiş dönüş bilet'],
  bavul: ['bavul hazırlamak', 'bavul taşımak'],
  harita: ['haritaya bakmak', 'yol haritası'],
  otobüs: ['otobüse binmek', 'otobüs durağı'],
  taksi: ['taksi çağırmak', 'taksiye binmek'],
  tren: ['trene binmek', 'tren istasyonu'],
  'uçak': ['uçağa binmek', 'uçak bileti'],
  trafik: ['trafiğe takılmak', 'trafik ışığı'],
  duygu: ['duygu paylaşmak', 'duygusal'],
  mutluluk: ['mutluluk duymak', 'mutluluk vermek'],
  'üzüntü': ['üzüntü duymak', 'derin üzüntü'],
  korku: ['korku duymak', 'korkuya kapılmak'],
  akıl: ['akıl vermek', 'aklında tutmak', 'akıllıca'],
  'rüya': ['rüya görmek', 'rüyada görmek'],
  hata: ['hata yapmak', 'hatayı düzeltmek', 'büyük hata'],
  'sır': ['sır tutmak', 'sır vermek'],
  keyif: ['keyif almak', 'keyfi yerinde'],
  sohbet: ['sohbet etmek', 'keyifli sohbet'],
  'sınav': ['sınava girmek', 'sınavı geçmek', 'sınava çalışmak'],
  not: ['not almak', 'not vermek', 'yüksek not'],
  'ödev': ['ödev yapmak', 'ödev vermek'],
  'sözlük': ['sözlüğe bakmak', 'sözlükten aramak'],
  'sınıf': ['sınıfta kalmak', 'sınıf arkadaşı'],

};
