import type { SentencePack } from '@/types/content';
import { b, p } from './shared/helpers';

/**
 * Functional sentence packs: the language of doing things to each other.
 *
 * The earlier sentence files are organised by *situation* (the pharmacy, the
 * municipality) and by *grammar* (relative clauses, converbs). This one is
 * organised by **communicative function** — asking, refusing, correcting,
 * emphasising — because that is the axis a student actually chooses along.
 * Nobody thinks "I need a converb"; they think "I need to disagree politely".
 *
 * Every pack here is also a workout for the function words added this phase.
 * The question particle `mı/mi/mu/mü` appears in almost every question pack,
 * `en` and `daha` carry the comparison pack, `eğer`/`ise` the conditionals,
 * `oysa`/`üstelik` the contrast — so the words and the sentences reinforce
 * each other rather than sitting in separate silos.
 */
export const FUNCTIONAL_SENTENCES: SentencePack[] = [
  /* ================================ A1 ================================ */
  {
    id: 'fn-a1-yesno',
    level: 'a1',
    order: 180,
    title: 'Evet / Hayır Soruları',
    titleI18n: b('أسئلة نعم/لا', 'پرسیاری بەڵێ/نەخێر'),
    focus: b(
      'أداة الاستفهام mı/mi/mu/mü منفصلة وتتبع انسجام الحركات. لا تغيير في ترتيب الكلمات.',
      'ئامرازی پرسیار mı/mi/mu/mü جیایە و هارمۆنی پەیڕەو دەکات.',
    ),
    sentences: [
      p('Türk müsün?', 'TÜRK mü-SÜN', 'هل أنت تركي؟', 'تۆ تورکیت؟'),
      p('Bu senin mi?', 'BU se-NİN mi', 'هل هذا لك؟', 'ئەمە هی تۆیە؟'),
      p('Çay var mı?', 'ÇAY VAR mı', 'هل يوجد شاي؟', 'چای هەیە؟'),
      p('Anladın mı?', 'an-la-DIN mı', 'هل فهمت؟', 'تێگەیشتیت؟'),
      p('Burası boş mu?', 'bu-ra-SI BOŞ mu', 'هل هذا المكان فارغ؟', 'ئێرە بەتاڵە؟'),
      p('Yorgun musun?', 'yor-GUN mu-SUN', 'هل أنت متعب؟', 'ماندوویت؟'),
      p('Doğru mu söylüyorsun?', 'doğ-RU MU söy-lü-yor-SUN', 'هل تقول الصحيح؟', 'ڕاست دەڵێیت؟'),
      p('Hazır mısınız?', 'ha-ZIR mı-sı-NIZ', 'هل أنتم جاهزون؟', 'ئامادەن؟'),
    ],
  },
  {
    id: 'fn-a1-answer',
    level: 'a1',
    order: 181,
    title: 'Kısa Cevaplar',
    titleI18n: b('الأجوبة القصيرة', 'وەڵامی کورت'),
    focus: b(
      'التركية تجيب بتكرار الفعل لا بـ«نعم» وحدها — «Geldin mi? — Geldim.»',
      'تورکی بە دووبارەکردنەوەی کردار وەڵام دەداتەوە.',
    ),
    sentences: [
      p('Evet, öyle.', 'e-VET öy-LE', 'نعم، هكذا.', 'بەڵێ، وایە.'),
      p('Hayır, değil.', 'ha-YIR de-ĞİL', 'لا، ليس كذلك.', 'نەخێر، وا نییە.'),
      p('Evet, biliyorum.', 'e-VET bi-li-yo-RUM', 'نعم، أعرف.', 'بەڵێ، دەزانم.'),
      p('Hayır, bilmiyorum.', 'ha-YIR bil-mi-yo-RUM', 'لا، لا أعرف.', 'نەخێر، نازانم.'),
      p('Tabii ki.', 'ta-Bİ-i ki', 'بالتأكيد.', 'بێگومان.'),
      p('Maalesef hayır.', 'ma-a-le-SEF ha-YIR', 'للأسف لا.', 'بەداخەوە نەخێر.'),
      p('Sanmıyorum.', 'san-mı-yo-RUM', 'لا أظنّ.', 'وا نازانم.'),
      p('Bilmiyorum, emin değilim.', 'bil-mi-yo-RUM e-MİN de-ği-LİM', 'لا أعرف، لست متأكّداً.', 'نازانم، دڵنیا نیم.'),
    ],
  },
  {
    id: 'fn-a1-thanks',
    level: 'a1',
    order: 182,
    title: 'Teşekkür ve Özür',
    titleI18n: b('الشكر والاعتذار', 'سوپاس و داوای لێبوردن'),
    focus: b(
      'صيغ ثابتة تُحفظ كما هي. لاحظ أن الردّ على الشكر ليس «شكراً» بل «rica ederim».',
      'شێوەی جێگیر کە وەک خۆی لەبەر دەکرێن.',
    ),
    sentences: [
      p('Çok teşekkür ederim.', 'ÇOK te-şek-KÜR e-de-RİM', 'شكراً جزيلاً.', 'زۆر سوپاس.'),
      p('Rica ederim.', 'ri-CA e-de-RİM', 'عفواً، لا شكر على واجب.', 'شایانی نییە.'),
      p('Sağ ol, çok naziksin.', 'SAĞ ol ÇOK na-zik-SİN', 'سلمت، أنت لطيف جداً.', 'سوپاس، زۆر بەڕێزیت.'),
      p('Özür dilerim, hata benim.', 'ö-ZÜR di-le-RİM ha-TA be-NİM', 'أعتذر، الخطأ خطئي.', 'ببوورە، هەڵەکە هی منە.'),
      p('Kusura bakma.', 'ku-su-RA bak-MA', 'المعذرة، لا تؤاخذني.', 'ببوورە.'),
      p('Önemli değil.', 'ö-nem-Lİ de-ĞİL', 'لا يهمّ.', 'گرنگ نییە.'),
      p('Estağfurullah.', 'es-tağ-fu-rul-LAH', 'العفو (رداً على مديح).', 'شایانی نییە.'),
      p('Yardımın için sağ ol.', 'yar-dı-MIN i-ÇİN SAĞ ol', 'شكراً على مساعدتك.', 'سوپاس بۆ یارمەتیت.'),
    ],
  },
  {
    id: 'fn-a1-request',
    level: 'a1',
    order: 183,
    title: 'Rica Etmek',
    titleI18n: b('الطلب بلطف', 'داواکردن بە ڕەوشتەوە'),
    focus: b(
      'سلّم الأدب: -sana (عامّي) < -ir misin (مهذّب) < -ir misiniz (رسمي).',
      'پلەبەندی ڕەوشت: -sana < -ir misin < -ir misiniz.',
    ),
    sentences: [
      p('Bir bardak su alabilir miyim?', 'bir bar-DAK SU a-la-bi-LİR mi-YİM', 'هل يمكنني كوب ماء؟', 'دەتوانم گڵاسێک ئاو وەربگرم؟'),
      p('Kapıyı kapatır mısın?', 'ka-pı-YI ka-pa-TIR mı-SIN', 'هل تغلق الباب؟', 'دەرگاکە دادەخەیت؟'),
      p('Biraz yardım eder misiniz?', 'bi-RAZ yar-DIM e-DER mi-si-NİZ', 'هل تساعدونني قليلاً؟', 'کەمێک یارمەتیم دەدەن؟'),
      p('Lütfen bir dakika bekleyin.', 'lüt-FEN bir da-ki-KA bek-le-YİN', 'من فضلكم انتظروا دقيقة.', 'تکایە خولەکێک چاوەڕێ بکەن.'),
      p('Şunu tutar mısın?', 'şu-NU tu-TAR mı-SIN', 'هل تمسك هذا؟', 'ئەمە دەگریت؟'),
      p('Rica etsem tekrar eder misiniz?', 'ri-CA et-SEM tek-RAR e-DER mi-si-NİZ', 'لو سمحت هل تعيد؟', 'داوات لێدەکەم دووبارەی بکەیتەوە؟'),
      p('Müsait misiniz?', 'mü-sa-İT mi-si-NİZ', 'هل أنتم متفرّغون؟', 'بەردەستن؟'),
      p('Bir şey sorabilir miyim?', 'bir ŞEY so-ra-bi-LİR mi-YİM', 'هل أسأل شيئاً؟', 'دەتوانم شتێک بپرسم؟'),
    ],
  },
  /* ================================ A2 ================================ */
  {
    id: 'fn-a2-accept',
    level: 'a2',
    order: 184,
    title: 'Kabul Etmek',
    titleI18n: b('القبول والموافقة', 'قبووڵکردن'),
    focus: b(
      'الموافقة التركية دافئة: قلّما يُقال «evet» وحدها؛ يُضاف تعبير ودّي.',
      'ڕازیبوونی تورکی گەرمە: تەنها «evet» کەم دەوترێت.',
    ),
    sentences: [
      p('Tabii, memnuniyetle.', 'ta-Bİ-i mem-nu-ni-yet-LE', 'بالتأكيد، بكل سرور.', 'بێگومان، بە خۆشحاڵییەوە.'),
      p('Olur, neden olmasın?', 'o-LUR NE-den ol-ma-SIN', 'حسناً، ولمَ لا؟', 'دەبێت، بۆچی نا؟'),
      p('Benim için uygun.', 'be-NİM i-ÇİN uy-GUN', 'مناسب بالنسبة لي.', 'بۆ من گونجاوە.'),
      p('Kesinlikle katılıyorum.', 'ke-sin-lik-LE ka-tı-lı-yo-RUM', 'أوافق تماماً.', 'بە تەواوی ڕازیم.'),
      p('Haklısın, öyle yapalım.', 'hak-lı-SIN öy-LE ya-pa-LIM', 'أنت محقّ، لنفعل ذلك.', 'ڕاست دەکەیت، وا بکەین.'),
      p('Bence de iyi fikir.', 'ben-CE DE i-Yİ fi-KİR', 'برأيي أيضاً فكرة جيدة.', 'بە بۆچوونی منیش بیرۆکەیەکی باشە.'),
      p('Anlaştık o zaman.', 'an-laş-TIK O za-MAN', 'اتّفقنا إذاً.', 'ڕێککەوتین کەواتە.'),
      p('Elbette, sorun değil.', 'el-bet-TE so-RUN de-ĞİL', 'بالطبع، لا مشكلة.', 'بێگومان، کێشە نییە.'),
    ],
  },
  {
    id: 'fn-a2-prefer',
    level: 'a2',
    order: 185,
    title: 'Tercih Belirtmek',
    titleI18n: b('التعبير عن التفضيل', 'دەربڕینی هەڵبژاردە'),
    focus: b(
      'المقارنة بـ «daha» والتفضيل بـ «en» — الصفة نفسها لا تتغيّر أبداً.',
      'بەراورد بە «daha» و هەرە بە «en».',
    ),
    sentences: [
      p('Ben çayı tercih ederim.', 'BEN ça-YI ter-CİH e-de-RİM', 'أنا أفضّل الشاي.', 'من چای هەڵدەبژێرم.'),
      p('Bu daha güzel.', 'BU da-HA gü-ZEL', 'هذا أجمل.', 'ئەمە جوانترە.'),
      p('En sevdiğim renk mavi.', 'EN sev-di-ĞİM RENK ma-Vİ', 'لوني المفضّل الأزرق.', 'ڕەنگی دڵخوازم شینە.'),
      p('Otobüs yerine metroyu tercih ederim.', 'o-to-BÜS ye-ri-NE met-ro-YU ter-CİH e-de-RİM', 'أفضّل المترو بدل الحافلة.', 'لەبری پاس، مەترۆ هەڵدەبژێرم.'),
      p('Bence bu daha uygun.', 'ben-CE BU da-HA uy-GUN', 'برأيي هذا أنسب.', 'بە بۆچوونی من ئەمە گونجاوترە.'),
      p('Hangisi daha iyi sence?', 'han-gi-Sİ da-HA i-Yİ sen-CE', 'أيّهما أفضل برأيك؟', 'بە بۆچوونی تۆ کامیان باشترە؟'),
      p('İkisi de olur, fark etmez.', 'i-ki-Sİ DE o-LUR FARK et-MEZ', 'كلاهما مناسب، لا فرق.', 'هەردووکیان دەبێت، جیاوازی نییە.'),
      p('En azından bunu deneyelim.', 'EN a-zın-DAN bu-NU de-ne-ye-LİM', 'على الأقل لنجرّب هذا.', 'لانی کەم ئەمە تاقی بکەینەوە.'),
    ],
  },
  {
    id: 'fn-a2-emphasis',
    level: 'a2',
    order: 186,
    title: 'Vurgulamak',
    titleI18n: b('التوكيد', 'جەختکردن'),
    focus: b(
      'التوكيد التركي بالكلمة لا بالنبرة: bile · hem de · özellikle · asla.',
      'جەختکردنی تورکی بە وشەیە نەک بە دەنگ.',
    ),
    sentences: [
      p('Adını bile bilmiyorum.', 'a-dı-NI bi-LE bil-mi-yo-RUM', 'لا أعرف حتى اسمه.', 'تەنانەت ناویشی نازانم.'),
      p('Çalışıyor, hem de çok iyi.', 'ça-lı-şı-YOR HEM de ÇOK i-Yİ', 'يعمل، بل ويعمل جيداً جداً.', 'کار دەکات، هەروەها زۆر باشیش.'),
      p('Özellikle bunu istiyorum.', 'ö-zel-lik-LE bu-NU is-ti-yo-RUM', 'أريد هذا تحديداً.', 'بە تایبەتی ئەمەم دەوێت.'),
      p('Asla kabul etmem.', 'as-LA ka-BUL et-MEM', 'لن أقبل أبداً.', 'هەرگیز قبووڵ ناکەم.'),
      p('Gerçekten çok yoruldum.', 'ger-çek-TEN ÇOK yo-rul-DUM', 'تعبت حقاً كثيراً.', 'بەڕاستی زۆر ماندوو بووم.'),
      p('Kesinlikle haklısın.', 'ke-sin-lik-LE hak-lı-SIN', 'أنت محقّ تماماً.', 'بە تەواوی ڕاست دەکەیت.'),
      p('Tam da bunu söyleyecektim.', 'TAM DA bu-NU söy-le-ye-cek-TİM', 'كنت سأقول هذا بالضبط.', 'هەر ئەمەم دەگوت.'),
      p('En önemlisi sağlık.', 'EN ö-nem-li-Sİ sağ-LIK', 'الأهمّ هو الصحّة.', 'گرنگترین شت تەندروستییە.'),
    ],
  },
  {
    id: 'fn-a2-topic',
    level: 'a2',
    order: 187,
    title: 'Konu Değiştirmek',
    titleI18n: b('تغيير الموضوع', 'گۆڕینی بابەت'),
    focus: b(
      'عبارات الانتقال: bu arada · sahi · neyse · aklıma gelmişken.',
      'دەستەواژەی گواستنەوە: bu arada · neyse.',
    ),
    sentences: [
      p('Bu arada, seni sormak istiyordum.', 'BU a-ra-DA se-Nİ sor-MAK is-ti-yor-DUM', 'بالمناسبة، كنت أريد السؤال عنك.', 'بەم بۆنەیەوە، دەمویست پرسیارت لێبکەم.'),
      p('Neyse, konuyu değiştirelim.', 'ney-SE ko-nu-YU de-ğiş-ti-re-LİM', 'على كل حال، لنغيّر الموضوع.', 'بەهەرحاڵ، بابەتەکە بگۆڕین.'),
      p('Sahi, dün ne oldu?', 'sa-Hİ DÜN NE ol-DU', 'صحيح، ماذا حدث أمس؟', 'ڕاستە، دوێنێ چی ڕوویدا؟'),
      p('Aklıma gelmişken, yarın müsait misin?', 'ak-lı-MA gel-miş-KEN ya-RIN mü-sa-İT mi-SİN', 'بما أنه خطر ببالي، هل أنت متفرّغ غداً؟', 'کە بەبیرم هاتەوە، سبەینێ بەردەستیت؟'),
      p('Bir de şunu sormak istiyorum.', 'bir DE şu-NU sor-MAK is-ti-yo-RUM', 'وأريد أن أسأل هذا أيضاً.', 'ئەمەشم دەوێت بپرسم.'),
      p('Konuyu açmışken söyleyeyim.', 'ko-nu-YU aç-mış-KEN söy-le-ye-YİM', 'بما أننا فتحنا الموضوع، دعني أقول.', 'کە بابەتەکەم کردەوە، با بیڵێم.'),
      p('Az önce ne diyordun?', 'AZ ön-CE NE di-yor-DUN', 'ماذا كنت تقول قبل قليل؟', 'کەمێک پێشتر چیت دەگوت؟'),
      p('Nerede kalmıştık?', 'ne-re-DE kal-mış-TIK', 'أين توقّفنا؟', 'لە کوێ وەستابووین؟'),
    ],
  },
  /* ================================ B1 ================================ */
  {
    id: 'fn-b1-clarify',
    level: 'b1',
    order: 188,
    title: 'Açıklama İstemek',
    titleI18n: b('طلب التوضيح والإيضاح', 'داوای ڕوونکردنەوە'),
    focus: b(
      'إعادة الصياغة للتأكّد: «yani … demek istiyorsunuz» — أهمّ مهارة في اجتماع.',
      'دووبارە دانانەوە بۆ دڵنیابوون.',
    ),
    sentences: [
      p('Yani şunu mu demek istiyorsunuz?', 'ya-Nİ şu-NU MU de-MEK is-ti-yor-su-NUZ', 'أي هل تقصدون هذا؟', 'واتە مەبەستتان ئەمەیە؟'),
      p('Tam olarak ne kastediyorsunuz?', 'TAM o-la-RAK NE kas-te-di-yor-su-NUZ', 'ماذا تقصدون بالضبط؟', 'بە تەواوی مەبەستتان چییە؟'),
      p('Bir örnekle açıklar mısınız?', 'bir ör-nek-LE a-çık-LAR mı-sı-NIZ', 'هل توضّحون بمثال؟', 'بە نموونەیەک ڕوونی دەکەنەوە؟'),
      p('Doğru anladıysam, öyle diyorsunuz.', 'doğ-RU an-la-dıy-SAM öy-LE di-yor-su-NUZ', 'إن فهمت صحيحاً فأنتم تقولون ذلك.', 'ئەگەر ڕاست تێگەیشتبم، وا دەڵێن.'),
      p('Bu noktayı biraz açabilir miyiz?', 'BU nok-ta-YI bi-RAZ a-ça-bi-LİR mi-YİZ', 'هل نوضّح هذه النقطة قليلاً؟', 'دەتوانین ئەم خاڵە کەمێک بکەینەوە؟'),
      p('Kusura bakmayın, takip edemedim.', 'ku-su-RA bak-ma-YIN ta-KİP e-de-me-DİM', 'المعذرة، لم أستطع المتابعة.', 'ببوورن، نەمتوانی بەدوایدا بچم.'),
      p('Yazılı olarak alabilir miyim?', 'ya-zı-LI o-la-RAK a-la-bi-LİR mi-YİM', 'هل آخذها كتابةً؟', 'دەتوانم بە نووسراوی وەریبگرم؟'),
      p('Anlaşıldı, teşekkürler.', 'an-la-şıl-DI te-şek-kür-LER', 'فُهم، شكراً.', 'تێگەیشتم، سوپاس.'),
    ],
  },
  {
    id: 'fn-b1-condition',
    level: 'b1',
    order: 189,
    title: 'Şart ve Sonuç',
    titleI18n: b('الشرط والنتيجة', 'مەرج و ئەنجام'),
    focus: b(
      'الشرط في اللاحقة -sa/-se، و«eğer» اختيارية. النتيجة تأتي بعده.',
      'مەرج لە پاشگری -sa/-se دایە و «eğer» ئارەزوومەندانەیە.',
    ),
    sentences: [
      p('Eğer yağmur yağarsa gitmeyiz.', 'E-ğer yağ-MUR ya-ğar-SA git-me-YİZ', 'إن أمطرت فلن نذهب.', 'ئەگەر باران ببارێت ناچین.'),
      p('Vaktin varsa bir kahve içelim.', 'vak-TİN var-SA bir kah-VE i-çe-LİM', 'إن كان لديك وقت فلنشرب قهوة.', 'ئەگەر کاتت هەیە قاوەیەک بخۆینەوە.'),
      p('Erken gelirsen yer bulursun.', 'er-KEN ge-lir-SEN YER bu-lur-SUN', 'إن جئت مبكراً ستجد مكاناً.', 'ئەگەر زوو بێیت شوێن دەدۆزیتەوە.'),
      p('Çalışmazsan sınavı geçemezsin.', 'ça-lış-maz-SAN sı-na-VI ge-çe-mez-SİN', 'إن لم تذاكر فلن تنجح.', 'ئەگەر نەخوێنیت لە تاقیکردنەوە دەرناچیت.'),
      p('İstersen sana yardım edebilirim.', 'is-ter-SEN sa-NA yar-DIM e-de-bi-li-RİM', 'إن أردت أستطيع مساعدتك.', 'ئەگەر بتەوێت دەتوانم یارمەتیت بدەم.'),
      p('Bu şartla kabul ediyorum.', 'BU şart-LA ka-BUL e-di-yo-RUM', 'أقبل بهذا الشرط.', 'بەم مەرجە قبووڵی دەکەم.'),
      p('Aksi hâlde başka çare kalmaz.', 'ak-Sİ hâl-DE baş-KA ça-RE kal-MAZ', 'وإلا فلن يبقى حلّ آخر.', 'ئەگەرنا چارەیەکی تر نامێنێت.'),
      p('Yeter ki zamanında haber ver.', 'ye-TER Kİ za-ma-nın-DA ha-BER ver', 'يكفي أن تخبرني في الوقت المناسب.', 'بەسە کە لە کاتی خۆیدا ئاگادارم بکەیتەوە.'),
    ],
  },
  {
    id: 'fn-b1-explain',
    level: 'b1',
    order: 190,
    title: 'Gerekçe Vermek',
    titleI18n: b('إعطاء المبرّرات', 'هۆکار خستنەڕوو'),
    focus: b(
      'خمس طرق للسبب مرتّبة من العامّي إلى الرسمي: çünkü · -dığı için · yüzünden · dolayı · nedeniyle.',
      'پێنج ڕێگای هۆکار لە قسەییەوە بۆ فەرمی.',
    ),
    sentences: [
      p('Katılamadım çünkü toplantım vardı.', 'ka-tı-la-ma-DIM ÇÜN-kü top-lan-TIM var-DI', 'لم أستطع المشاركة لأن لديّ اجتماعاً.', 'نەمتوانی بەشدار بم چونکە کۆبوونەوەم هەبوو.'),
      p('Trafik olduğu için geciktim.', 'tra-FİK ol-du-ĞU i-ÇİN ge-cik-TİM', 'تأخّرت بسبب وجود ازدحام.', 'بەهۆی هاتوچۆوە دواکەوتم.'),
      p('Hastalık yüzünden okula gidemedi.', 'has-ta-LIK yü-zün-DEN o-ku-LA gi-de-me-Dİ', 'لم يستطع الذهاب للمدرسة بسبب المرض.', 'بەهۆی نەخۆشییەوە نەیتوانی بچێتە قوتابخانە.'),
      p('Yoğunluktan dolayı ertelendi.', 'yo-ğun-luk-TAN do-la-YI er-te-len-Dİ', 'أُجّل بسبب الازدحام.', 'بەهۆی قەرەباڵغییەوە دواخرا.'),
      p('Bu nedenle karar değişti.', 'BU ne-den-LE ka-RAR de-ğiş-Tİ', 'لهذا السبب تغيّر القرار.', 'بەم هۆیەوە بڕیارەکە گۆڕا.'),
      p('Sebebini açıklayabilir misiniz?', 'se-be-bi-Nİ a-çık-la-ya-bi-LİR mi-si-NİZ', 'هل توضّحون السبب؟', 'دەتوانن هۆکارەکەی ڕوون بکەنەوە؟'),
      p('Senin sayende hallettik.', 'se-NİN sa-yen-DE hal-let-TİK', 'حللناها بفضلك.', 'بەهۆی تۆوە چارەسەرمان کرد.'),
      p('Bunun bir açıklaması olmalı.', 'bu-NUN bir a-çık-la-ma-SI ol-ma-LI', 'لا بدّ أن لهذا تفسيراً.', 'دەبێت ڕوونکردنەوەیەکی هەبێت.'),
    ],
  },
  {
    id: 'fn-b1-correct',
    level: 'b1',
    order: 191,
    title: 'Düzeltmek',
    titleI18n: b('التصحيح', 'ڕاستکردنەوە'),
    focus: b(
      '⚠️ التركية تصحّح المعلومة لا الشخص: «bilgi yanlış» أهذب من «yanılıyorsun».',
      '⚠️ تورکی زانیاری ڕاست دەکاتەوە نەک کەسەکە.',
    ),
    sentences: [
      p('Sanırım küçük bir yanlışlık var.', 'sa-nı-RIM kü-ÇÜK bir yan-lış-LIK var', 'أظنّ أن هناك خطأً صغيراً.', 'وابزانم هەڵەیەکی بچووک هەیە.'),
      p('Aslında biraz farklı.', 'as-lın-DA bi-RAZ fark-LI', 'في الحقيقة الأمر مختلف قليلاً.', 'لە ڕاستیدا کەمێک جیاوازە.'),
      p('Yanlış hatırlamıyorsam öyle değildi.', 'yan-LIŞ ha-tır-la-mı-yor-SAM öy-LE de-ğil-Dİ', 'إن لم تخنّي الذاكرة لم يكن كذلك.', 'ئەگەر هەڵە لەبیرم نەبێت وا نەبوو.'),
      p('Düzeltmek isterim: tarih değişti.', 'dü-zelt-MEK is-te-RİM ta-RİH de-ğiş-Tİ', 'أودّ التصحيح: تغيّر التاريخ.', 'دەمەوێت ڕاستی بکەمەوە: بەروارەکە گۆڕا.'),
      p('Pardon, ben yanlış söyledim.', 'par-DON BEN yan-LIŞ söy-le-DİM', 'عذراً، أنا قلت خطأً.', 'ببوورە، من هەڵە گوتم.'),
      p('Doğrusu şöyle olmalı.', 'doğ-ru-SU şöy-LE ol-ma-LI', 'الصحيح ينبغي أن يكون هكذا.', 'ڕاستەکەی دەبێت وا بێت.'),
      p('Bu bilgi güncel değil.', 'BU bil-Gİ gün-CEL de-ĞİL', 'هذه المعلومة ليست محدّثة.', 'ئەم زانیارییە نوێ نییە.'),
      p('Kaynağı kontrol etmekte fayda var.', 'kay-na-ĞI kon-TROL et-mek-TE fay-DA var', 'من المفيد التحقّق من المصدر.', 'سوودی هەیە سەرچاوەکە بپشکنرێت.'),
    ],
  },
  /* ================================ B2 ================================ */
  {
    id: 'fn-b2-disagree',
    level: 'b2',
    order: 192,
    title: 'Nazikçe Karşı Çıkmak',
    titleI18n: b('الاعتراض بلباقة', 'ناڕەزایی بە ڕەوشتەوە'),
    focus: b(
      'البنية الثلاثية: إقرار، ثم «ancak»، ثم التحفّظ. الاعتراض المباشر يُقرأ عدائياً.',
      'پێکهاتەی سێیانە: دانپێدانان، «ancak»، پاشان مەرج.',
    ),
    sentences: [
      p('Haklısınız, ancak bir noktada ayrılıyoruz.', 'hak-lı-sı-NIZ an-CAK bir nok-ta-DA ay-rı-lı-yo-RUZ', 'أنتم محقّون، لكننا نختلف في نقطة.', 'ڕاست دەکەن، بەڵام لە خاڵێکدا جیاوازین.'),
      p('Buna tam olarak katılamıyorum.', 'bu-NA TAM o-la-RAK ka-tı-la-mı-yo-RUM', 'لا أستطيع الاتّفاق تماماً على هذا.', 'ناتوانم بە تەواوی لەگەڵ ئەمەدا ڕازی بم.'),
      p('Farklı düşünüyorum, izin verirseniz.', 'fark-LI dü-şü-nü-yo-RUM i-ZİN ve-rir-se-NİZ', 'أفكّر بشكل مختلف، إن سمحتم.', 'بە جیاواز بیر دەکەمەوە، ئەگەر ڕێگە بدەن.'),
      p('Bu konuda çekincelerim var.', 'BU ko-nu-DA çe-kin-ce-le-RİM var', 'لديّ تحفّظات في هذا الأمر.', 'لەم بارەیەوە مەرجم هەیە.'),
      p('Oysa veriler başka bir şey söylüyor.', 'OY-sa ve-ri-LER baş-KA bir ŞEY söy-lü-YOR', 'بينما تقول البيانات شيئاً آخر.', 'بەڵام داتاکان شتێکی تر دەڵێن.'),
      p('Üstelik maliyeti de yüksek.', 'ÜS-te-lik ma-li-ye-Tİ DE yük-SEK', 'وفوق ذلك تكلفته عالية.', 'سەرەڕای ئەوەش تێچووەکەی بەرزە.'),
      p('Yine de sizi anlıyorum.', 'Yİ-ne DE si-Zİ an-lı-yo-RUM', 'ومع ذلك أفهمكم.', 'لەگەڵ ئەوەشدا لێتان تێدەگەم.'),
      p('Belki bir orta yol bulabiliriz.', 'bel-Kİ bir or-TA YOL bu-la-bi-li-RİZ', 'ربّما نجد حلاً وسطاً.', 'لەوانەیە ڕێگایەکی ناوەند بدۆزینەوە.'),
    ],
  },
  {
    id: 'fn-b2-compare',
    level: 'b2',
    order: 193,
    title: 'Karşılaştırma Dili',
    titleI18n: b('لغة المقارنة', 'زمانی بەراورد'),
    focus: b(
      'أدوات المقارنة الرسمية: kıyasla · oranla · aksine · buna karşılık.',
      'ئامرازی بەراوردی فەرمی: kıyasla · oranla · aksine.',
    ),
    sentences: [
      p('Geçen yıla kıyasla durum daha iyi.', 'ge-ÇEN yı-LA kı-yas-LA du-RUM da-HA i-Yİ', 'الوضع أفضل مقارنةً بالعام الماضي.', 'بەراورد بە پار دۆخەکە باشترە.'),
      p('Diğerlerine oranla çok hızlı.', 'di-ğer-le-ri-NE o-ran-LA ÇOK hız-LI', 'سريع جداً بالنسبة للآخرين.', 'بەراورد بە ئەوانی تر زۆر خێرایە.'),
      p('Aksine, sonuç beklenenden iyi çıktı.', 'ak-si-NE so-NUÇ bek-le-nen-DEN i-Yİ çık-TI', 'على العكس، جاءت النتيجة أفضل من المتوقّع.', 'بەپێچەوانەوە، ئەنجامەکە لە چاوەڕوانکراو باشتر بوو.'),
      p('Buna karşılık riski de yüksek.', 'bu-NA kar-şı-LIK ris-Kİ DE yük-SEK', 'في المقابل مخاطرته عالية أيضاً.', 'لە بەرامبەردا مەترسییەکەشی بەرزە.'),
      p('İkisi arasında ciddi bir fark yok.', 'i-ki-Sİ a-ra-sın-DA cid-Dİ bir FARK yok', 'لا فرق جوهري بينهما.', 'جیاوازییەکی جدی لە نێوانیاندا نییە.'),
      p('En az onun kadar önemli.', 'EN AZ o-NUN ka-DAR ö-nem-Lİ', 'مهمّ بقدره على الأقل.', 'لانی کەم بەقەد ئەو گرنگە.'),
      p('Bir yandan ucuz, öte yandan dayanıksız.', 'bir yan-DAN u-CUZ ö-TE yan-DAN da-ya-nık-SIZ', 'رخيص من ناحية، وغير متين من ناحية أخرى.', 'لەلایەکەوە هەرزانە، لەلایەکی ترەوە بەهێز نییە.'),
      p('Bu açıdan bakınca farklı görünüyor.', 'BU a-çı-DAN ba-kın-CA fark-LI gö-rü-nü-YOR', 'من هذه الزاوية يبدو مختلفاً.', 'لەم گۆشەیەوە جیاواز دیارە.'),
    ],
  },
  {
    id: 'fn-b2-conclude',
    level: 'b2',
    order: 194,
    title: 'Toparlamak',
    titleI18n: b('الختم والتلخيص', 'کۆکردنەوە'),
    focus: b(
      'إغلاق الحديث: özetle · sonuç olarak · kısacası · son olarak.',
      'داخستنی قسە: özetle · sonuç olarak · kısacası.',
    ),
    sentences: [
      p('Özetle, üç seçeneğimiz var.', 'ö-zet-LE ÜÇ se-çe-ne-ği-MİZ var', 'باختصار، لدينا ثلاثة خيارات.', 'بە کورتی، سێ هەڵبژاردەمان هەیە.'),
      p('Sonuç olarak karar sizin.', 'so-NUÇ o-la-RAK ka-RAR si-ZİN', 'في النهاية القرار قراركم.', 'لە ئەنجامدا بڕیارەکە هی ئێوەیە.'),
      p('Kısacası, zamanımız kalmadı.', 'kı-sa-ca-SI za-ma-nı-MIZ kal-ma-DI', 'باختصار، لم يبقَ لنا وقت.', 'بە کورتی، کاتمان نەماوە.'),
      p('Son olarak bir şey eklemek istiyorum.', 'SON o-la-RAK bir ŞEY ek-le-MEK is-ti-yo-RUM', 'أخيراً أودّ إضافة شيء.', 'لە کۆتاییدا دەمەوێت شتێک زیاد بکەم.'),
      p('Demek ki yöntemi değiştirmeliyiz.', 'de-MEK Kİ yön-te-Mİ de-ğiş-tir-me-li-YİZ', 'إذاً علينا تغيير الطريقة.', 'واتە دەبێت میتۆدەکە بگۆڕین.'),
      p('Bu konuyu burada kapatalım.', 'BU ko-nu-YU bu-ra-DA ka-pa-ta-LIM', 'لنغلق هذا الموضوع هنا.', 'با ئەم بابەتە لێرە دابخەین.'),
      p('Herkese katkısı için teşekkür ederim.', 'her-ke-SE kat-kı-SI i-ÇİN te-şek-KÜR e-de-RİM', 'أشكر الجميع على مساهمتهم.', 'سوپاس بۆ هەمووان بۆ بەشدارییان.'),
      p('Detayları yarın konuşuruz.', 'de-tay-la-RI ya-RIN ko-nu-şu-RUZ', 'سنتحدّث عن التفاصيل غداً.', 'سبەینێ باسی وردەکارییەکان دەکەین.'),
    ],
  },
  /* ================================ C1 ================================ */
  {
    id: 'fn-c1-hedge',
    level: 'c1',
    order: 195,
    title: 'İhtiyatlı İfade',
    titleI18n: b('التحفّظ في العبارة', 'وریایی لە دەربڕیندا'),
    focus: b(
      'التحوّط الأكاديمي: التركية تخفّف بالفعل («görünüyor», «olabilir») لا بالظرف وحده.',
      'وریایی ئەکادیمی: تورکی بە کردار نەرم دەکات.',
    ),
    sentences: [
      p('Bu bulgu kesin bir sonuç sayılmaz.', 'BU bul-GU ke-SİN bir so-NUÇ sa-yıl-MAZ', 'لا تُعدّ هذه النتيجة قاطعة.', 'ئەم دۆزینەوەیە ئەنجامێکی دڵنیا نییە.'),
      p('Verilerin sınırlı olduğunu belirtmek gerekir.', 've-ri-le-RİN sı-nır-LI ol-du-ğu-NU be-lirt-MEK ge-re-KİR', 'ينبغي الإشارة إلى محدودية البيانات.', 'پێویستە ئاماژە بە سنووردارییی داتاکان بکرێت.'),
      p('Bu, en azından kısmen doğru görünüyor.', 'BU EN a-zın-DAN kıs-MEN doğ-RU gö-rü-nü-YOR', 'يبدو هذا صحيحاً جزئياً على الأقل.', 'ئەمە لانی کەم بەشێک ڕاست دیارە.'),
      p('Genellemek için henüz erken.', 'ge-nel-le-MEK i-ÇİN he-NÜZ er-KEN', 'ما زال مبكراً للتعميم.', 'هێشتا زووە بۆ گشتاندن.'),
      p('Alternatif açıklamalar göz ardı edilemez.', 'al-ter-na-TİF a-çık-la-ma-LAR GÖZ ar-DI e-di-le-MEZ', 'لا يمكن تجاهل تفسيرات بديلة.', 'ڕوونکردنەوەی جێگرەوە پشتگوێ ناخرێن.'),
      p('Söz konusu ilişki zayıf olabilir.', 'SÖZ ko-nu-SU i-liş-Kİ za-YIF o-la-bi-LİR', 'قد تكون العلاقة المعنية ضعيفة.', 'لەوانەیە پەیوەندییەکە لاواز بێت.'),
      p('Bu yorumu ihtiyatla karşılamak gerekir.', 'BU yo-ru-MU ih-ti-yat-LA kar-şı-la-MAK ge-re-KİR', 'ينبغي تلقّي هذا التفسير بحذر.', 'پێویستە بەم لێکدانەوەیە بە وریاییەوە هەڵسوکەوت بکرێت.'),
      p('İleri çalışmalar bunu netleştirebilir.', 'i-le-Rİ ça-lış-ma-LAR bu-NU net-leş-ti-re-bi-LİR', 'قد توضّح دراسات لاحقة هذا.', 'توێژینەوەی داهاتوو دەکرێت ئەمە ڕوون بکاتەوە.'),
    ],
  },
  {
    id: 'fn-c1-partial',
    level: 'c1',
    order: 196,
    title: 'Kısmen Katılmak',
    titleI18n: b('الاتّفاق الجزئي', 'ڕازیبوونی بەشەکی'),
    focus: b(
      'أدقّ مهارة في النقاش: القبول المشروط الذي يترك الباب مفتوحاً.',
      'وردترین توانا لە گفتوگۆدا: قبووڵکردنی مەرجدار.',
    ),
    sentences: [
      p('Bu tespite kısmen katılıyorum.', 'BU tes-pi-TE kıs-MEN ka-tı-lı-yo-RUM', 'أتّفق جزئياً مع هذا الاستنتاج.', 'بەشێک لەم دیاریکردنە ڕازیم.'),
      p('Genel çerçeveye evet, ayrıntılara hayır.', 'ge-NEL çer-çe-ve-YE e-VET ay-rın-tı-la-RA ha-YIR', 'نعم للإطار العام، لا للتفاصيل.', 'بەڵێ بۆ چوارچێوەی گشتی، نەخێر بۆ وردەکارییەکان.'),
      p('Öncülü kabul ediyorum, sonucu değil.', 'ön-cü-LÜ ka-BUL e-di-yo-RUM so-nu-CU de-ĞİL', 'أقبل المقدّمة لا النتيجة.', 'پێشەکییەکە قبووڵ دەکەم، نەک ئەنجامەکە.'),
      p('Belli koşullarda geçerli olabilir.', 'bel-Lİ ko-şul-lar-DA ge-çer-Lİ o-la-bi-LİR', 'قد يصحّ في ظروف معيّنة.', 'لە هەندێک بارودۆخدا دەکرێت ڕاست بێت.'),
      p('Bu argümanın gücünü kabul etmeliyim.', 'BU ar-gü-ma-NIN gü-cü-NÜ ka-BUL et-me-li-YİM', 'عليّ الإقرار بقوّة هذه الحجّة.', 'دەبێت دان بە هێزی ئەم بەڵگەیەدا بنێم.'),
      p('Yine de bir çekincem var.', 'Yİ-ne DE bir çe-kin-CEM var', 'ومع ذلك لديّ تحفّظ.', 'لەگەڵ ئەوەشدا مەرجێکم هەیە.'),
      p('Tartışmayı ilerletmek adına kabul edelim.', 'tar-tış-ma-YI i-ler-let-MEK a-dı-NA ka-BUL e-de-LİM', 'لنقبل بها من أجل تقدّم النقاش.', 'بۆ بەرەوپێشبردنی گفتوگۆ با قبووڵی بکەین.'),
      p('Bu noktada mutabıkız.', 'BU nok-ta-DA mu-ta-bı-KIZ', 'نحن متّفقون في هذه النقطة.', 'لەم خاڵەدا ڕێککەوتووین.'),
    ],
  },
];
