import type { SentencePack } from '@/types/content';
import { b, p } from '../shared/helpers';

/**
 * A1 sentence packs. Each pack is a FUNCTION (introducing yourself, ordering
 * food) rather than a grammar point, because that is how a beginner actually
 * needs sentences: ready to use, whole.
 */
export const A1_SENTENCES: SentencePack[] = [
  {
    id: 'a1-sent-intro',
    level: 'a1',
    order: 1,
    title: 'Kendini Tanıtma',
    titleI18n: b('التعريف بالنفس', 'خۆناساندن'),
    focus: b('أول ما ستقوله لأي تركي تقابله.', 'یەکەم شت کە بە هەر تورکێک دەیڵێیت کە دەیبینیت.'),
    sentences: [
      p('Merhaba, benim adım Karwan.', 'mer-ha-BA be-NİM a-DIM kar-VAN', 'مرحباً، اسمي كاروان.', 'سڵاو، ناوی من کاروانە.'),
      p('Ben Iraklıyım.', 'BEN ı-rak-LI-yım', 'أنا عراقي.', 'من عێراقیم.'),
      p('Erbil’den geliyorum.', 'er-BİL-den ge-li-YO-rum', 'أنا قادم من أربيل.', 'لە هەولێرەوە هاتووم.'),
      p('Yirmi beş yaşındayım.', 'yir-mi BEŞ ya-şın-da-YIM', 'عمري خمسة وعشرون عاماً.', 'تەمەنم بیست و پێنج ساڵە.'),
      p('Öğrenciyim.', 'öö-ren-Cİ-yim', 'أنا طالب.', 'قوتابیم.'),
      p('Türkçe öğreniyorum.', 'türk-ÇE öö-re-ni-YO-rum', 'أنا أتعلّم التركية.', 'فێری تورکی دەبم.'),
      p('Ailemle birlikte yaşıyorum.', 'a-i-lem-LE bir-lik-TE ya-şı-YO-rum', 'أعيش مع عائلتي.', 'لەگەڵ خێزانەکەم دەژیم.'),
      p('Ana dilim Kürtçe ve Arapça biliyorum.', 'a-NA di-LİM kürt-ÇE ve a-rap-ÇA bi-li-YO-rum', 'لغتي الأم الكردية وأعرف العربية.', 'زمانی دایکم کوردییە و عەرەبیش دەزانم.'),
      p('Tanıştığımıza memnun oldum.', 'ta-nış-tı-ı-mı-ZA mem-NUN ol-dum', 'سررت بالتعرّف عليك.', 'خۆشحاڵم بە ناسینت.'),
      p('Sizin adınız ne?', 'si-ZİN a-dı-NIZ NE', 'ما اسمك حضرتك؟', 'ناوی جەنابت چییە؟'),
    ],
  },
  {
    id: 'a1-sent-questions',
    level: 'a1',
    order: 2,
    title: 'Temel Sorular',
    titleI18n: b('الأسئلة الأساسية', 'پرسیارە بنەڕەتییەکان'),
    focus: b('عشرة أسئلة تنقذك في أي موقف.', 'دە پرسیار کە لە هەر دۆخێکدا فریات دەکەون.'),
    sentences: [
      p('Bu ne?', 'BU NE', 'ما هذا؟', 'ئەمە چییە؟'),
      p('Bu ne kadar?', 'BU ne ka-DAR', 'بكم هذا؟', 'ئەمە چەندە؟'),
      p('Saat kaç?', 'sa-AT KAÇ', 'كم الساعة؟', 'کاتژمێر چەندە؟'),
      p('Tuvalet nerede?', 'tu-va-LET ne-re-DE', 'أين الحمّام؟', 'تەوالێت لە کوێیە؟'),
      p('Nereye gidiyorsun?', 'ne-re-YE gi-di-yor-sun', 'إلى أين تذهب؟', 'بۆ کوێ دەچیت؟'),
      p('Ne zaman geliyorsun?', 'ne za-MAN ge-li-yor-sun', 'متى ستأتي؟', 'کەی دێیت؟'),
      p('Neden geç kaldın?', 'ne-DEN GEÇ kal-dın', 'لماذا تأخّرت؟', 'بۆچی درەنگ کەوتیت؟'),
      p('Bu nasıl?', 'BU na-SIL', 'كيف هذا؟', 'ئەمە چۆنە؟'),
      p('Kim geldi?', 'KİM gel-Dİ', 'من جاء؟', 'کێ هات؟'),
      p('Yardım eder misiniz?', 'yar-DIM e-DER mi-si-niz', 'هل تساعدني من فضلك؟', 'یارمەتیم دەدەیت؟'),
      p('Anlamadım, tekrar eder misiniz?', 'an-la-ma-DIM tek-RAR e-DER mi-si-niz', 'لم أفهم، هل تعيد؟', 'تێنەگەیشتم، دووبارەی دەکەیتەوە؟'),
      p('Türkçe biliyor musunuz?', 'türk-ÇE bi-li-YOR mu-su-nuz', 'هل تعرفون التركية؟', 'تورکی دەزانن؟'),
    ],
  },
  {
    id: 'a1-sent-negative',
    level: 'a1',
    order: 3,
    title: 'Olumsuz Cümleler',
    titleI18n: b('الجمل المنفية', 'ڕستە نەرێنییەکان'),
    focus: b('كيف تقول "لا" بكل أشكالها.', 'چۆن بە هەموو شێوەکانی "نا" بڵێیت.'),
    sentences: [
      p('Ben öğretmen değilim.', 'BEN öö-ret-MEN de-i-LİM', 'أنا لست معلّماً.', 'من مامۆستا نیم.'),
      p('Bu doğru değil.', 'BU do-RU de-İL', 'هذا ليس صحيحاً.', 'ئەمە ڕاست نییە.'),
      p('Param yok.', 'pa-RAM YOK', 'ليس لديّ نقود.', 'پارەم نییە.'),
      p('Bugün vaktim yok.', 'bu-GÜN vak-TİM YOK', 'ليس لديّ وقت اليوم.', 'ئەمڕۆ کاتم نییە.'),
      p('Anlamıyorum.', 'an-la-mı-YO-rum', 'لا أفهم.', 'تێناگەم.'),
      p('Türkçe konuşmuyorum, sadece öğreniyorum.', 'türk-ÇE ko-nuş-mu-YO-rum sa-de-DJE öö-re-ni-YO-rum', 'لا أتحدّث التركية، أنا أتعلّم فقط.', 'تورکی قسە ناکەم، تەنها فێر دەبم.'),
      p('Et yemiyorum.', 'ET ye-mi-YO-rum', 'لا آكل اللحم.', 'گۆشت ناخۆم.'),
      p('Hayır, teşekkürler.', 'ha-YIR te-şek-kür-LER', 'لا، شكراً.', 'نەخێر، سوپاس.'),
      p('Onu tanımıyorum.', 'o-NU ta-nı-mı-YO-rum', 'لا أعرفه.', 'نایناسم.'),
      p('Burada sigara içilmez.', 'bu-ra-DA si-ga-RA i-çil-MEZ', 'ممنوع التدخين هنا.', 'لێرە جگەرەکێشان قەدەغەیە.'),
    ],
  },
  {
    id: 'a1-sent-daily',
    level: 'a1',
    order: 4,
    title: 'Günlük Rutin',
    titleI18n: b('الروتين اليومي', 'ڕۆتینی ڕۆژانە'),
    focus: b('احكِ يومك من الصباح إلى المساء.', 'ڕۆژەکەت بگێڕەوە لە بەیانییەوە تا ئێوارە.'),
    sentences: [
      p('Sabah yedide kalkıyorum.', 'sa-BAH ye-di-DE kal-kı-YO-rum', 'أستيقظ الساعة السابعة صباحاً.', 'بەیانی حەوت هەڵدەستم.'),
      p('Kahvaltı yapıyorum.', 'kah-val-TI ya-pı-YO-rum', 'أتناول الفطور.', 'نانی بەیانی دەخۆم.'),
      p('Sonra okula gidiyorum.', 'son-RA o-ku-LA gi-di-YO-rum', 'ثم أذهب إلى المدرسة.', 'پاشان دەچمە قوتابخانە.'),
      p('Öğlen arkadaşlarımla yemek yiyorum.', 'öö-LEN ar-ka-daş-la-rım-LA ye-MEK yi-YO-rum', 'أتناول الغداء مع أصدقائي ظهراً.', 'نیوەڕۆ لەگەڵ هاوڕێکانم نان دەخۆم.'),
      p('Akşam eve dönüyorum.', 'ak-ŞAM e-VE dö-nü-YO-rum', 'أعود إلى البيت مساءً.', 'ئێوارە دەگەڕێمەوە ماڵ.'),
      p('Biraz dinleniyorum.', 'bi-RAZ din-le-ni-YO-rum', 'أستريح قليلاً.', 'کەمێک پشوو دەدەم.'),
      p('Ders çalışıyorum.', 'DERS ça-lı-şı-YO-rum', 'أدرس.', 'وانە دەخوێنم.'),
      p('Gece on birde yatıyorum.', 'ge-DJE on bir-DE ya-tı-YO-rum', 'أنام الساعة الحادية عشرة ليلاً.', 'شەو یازدە دەنووم.'),
      p('Hafta sonu genelde dinleniyorum.', 'haf-TA so-NU ge-nel-DE din-le-ni-YO-rum', 'عادةً أستريح في عطلة نهاية الأسبوع.', 'کۆتایی هەفتە بەگشتی پشوو دەدەم.'),
    ],
  },
  {
    id: 'a1-sent-cafe',
    level: 'a1',
    order: 5,
    title: 'Kafede ve Lokantada',
    titleI18n: b('في المقهى والمطعم', 'لە قاوەخانە و چێشتخانە'),
    focus: b('اطلب طعامك وادفع الحساب بثقة.', 'خواردنەکەت داوا بکە و حسابەکە بدە بە دڵنیاییەوە.'),
    sentences: [
      p('Bir çay lütfen.', 'bir ÇAY lüt-FEN', 'شاياً واحداً من فضلك.', 'چایەک تکایە.'),
      p('Menüyü alabilir miyim?', 'me-nü-YÜ a-la-bi-LİR mi-yim', 'هل يمكنني الحصول على القائمة؟', 'دەتوانم مێنیوەکە وەربگرم؟'),
      p('Ne tavsiye edersiniz?', 'NE tav-si-YE e-der-si-niz', 'بماذا تنصحون؟', 'چی پێشنیار دەکەن؟'),
      p('Bu ne kadar acı?', 'BU ne ka-DAR a-DJI', 'ما مدى حرارة هذا (حرّيته)؟', 'ئەمە چەند تیژە؟'),
      p('Etsiz bir şey var mı?', 'et-SİZ bir ŞEY var MI', 'هل يوجد شيء بلا لحم؟', 'شتێکی بێ گۆشت هەیە؟'),
      p('Hesap lütfen.', 'he-SAP lüt-FEN', 'الحساب من فضلك.', 'حساب تکایە.'),
      p('Kartla ödeyebilir miyim?', 'kart-LA ö-de-ye-bi-LİR mi-yim', 'هل يمكنني الدفع بالبطاقة؟', 'دەتوانم بە کارت پارە بدەم؟'),
      p('Çok lezzetliydi, teşekkürler.', 'ÇOK lez-zet-liy-Dİ te-şek-kür-LER', 'كان لذيذاً جداً، شكراً.', 'زۆر خۆش بوو، سوپاس.'),
      p('Afiyet olsun.', 'a-fi-YET ol-SUN', 'بالهناء والشفاء.', 'نۆشی گیانت.'),
    ],
  },
];
