import type { VocabItem } from '@/types/content';
import { b, pack, sense, w } from '../shared/helpers';

/**
 * A1 vocabulary - the ~250 words a beginner needs before anything else.
 * Grouped by category; `pack()` stamps category, level and part of speech.
 */

const greetings = pack('greetings', 'a1', 'phrase', [
  w('Merhaba', 'mer-ha-BA', 'مرحباً', 'سڵاو', ['Merhaba, ben Ali.', 'mer-ha-BA ben a-Lİ', 'مرحباً، أنا علي.', 'سڵاو، من عەلیم.']),
  w('Selam', 'se-LAM', 'أهلاً (غير رسمي)', 'سڵاو (نافەرمی)', ['Selam, nasılsın?', 'se-LAM na-sıl-SIN', 'أهلاً، كيف حالك؟', 'سڵاو، چۆنی؟']),
  w('Günaydın', 'gü-nay-DIN', 'صباح الخير', 'بەیانیت باش', ['Günaydın anne!', 'gü-nay-DIN an-NE', 'صباح الخير يا أمي!', 'بەیانیت باش دایە!']),
  w('İyi günler', 'i-Yİ gün-LER', 'نهارك سعيد', 'ڕۆژباش', ['İyi günler, buyurun.', 'i-Yİ gün-LER bu-yu-RUN', 'نهارك سعيد، تفضل.', 'ڕۆژباش، فەرموو.']),
  w('İyi akşamlar', 'i-Yİ ak-şam-LAR', 'مساء الخير', 'ئێوارەباش', ['İyi akşamlar efendim.', 'i-Yİ ak-şam-LAR e-fen-DİM', 'مساء الخير سيدي.', 'ئێوارەباش گەورەم.']),
  w('İyi geceler', 'i-Yİ ge-dje-LER', 'تصبح على خير', 'شەوباش', ['İyi geceler, yarın görüşürüz.', 'i-Yİ ge-dje-LER ya-RIN gö-rü-şü-RÜZ', 'تصبح على خير، نلتقي غداً.', 'شەوباش، سبەینێ دەبینینەوە.']),
  w('Hoş geldiniz', 'HOŞ gel-di-niz', 'أهلاً وسهلاً بكم', 'بەخێربێن', ['Evimize hoş geldiniz.', 'e-vi-mi-ZE HOŞ gel-di-niz', 'أهلاً بكم في بيتنا.', 'بۆ ماڵەکەمان بەخێربێن.']),
  w('Hoş bulduk', 'HOŞ bul-duk', 'أهلاً بك (ردّ على الترحيب)', 'خۆشحاڵین (وەڵامی بەخێرهاتن)', ['Hoş bulduk, teşekkürler.', 'HOŞ bul-duk te-şek-kür-LER', 'أهلاً بك، شكراً.', 'خۆشحاڵین، سوپاس.']),
  w('Nasılsın?', 'na-sıl-SIN', 'كيف حالك؟', 'چۆنی؟', ['Merhaba, nasılsın?', 'mer-ha-BA na-sıl-SIN', 'مرحباً، كيف حالك؟', 'سڵاو، چۆنی؟']),
  w('İyiyim', 'i-Yİ-yim', 'أنا بخير', 'باشم', ['İyiyim, sen nasılsın?', 'i-Yİ-yim SEN na-sıl-SIN', 'أنا بخير، وأنت؟', 'باشم، تۆ چۆنی؟']),
  w('Teşekkür ederim', 'te-şek-KÜR e-de-rim', 'شكراً لك', 'سوپاست دەکەم', ['Yardımın için teşekkür ederim.', 'yar-dı-MIN i-ÇİN te-şek-KÜR e-de-rim', 'شكراً لك على مساعدتك.', 'سوپاست دەکەم بۆ یارمەتیت.']),
  w('Sağ ol', 'SA-ol', 'شكراً (ودّي)', 'دەستخۆش', ['Sağ ol kardeşim.', 'SA-ol kar-de-ŞİM', 'شكراً يا أخي.', 'دەستخۆش برام.']),
  w('Rica ederim', 'ri-DJA e-de-rim', 'عفواً / على الرحب والسعة', 'شایانی نییە', ['Rica ederim, önemli değil.', 'ri-DJA e-de-rim ö-nem-Lİ de-İL', 'عفواً، لا يهم.', 'شایانی نییە، گرنگ نییە.']),
  w('Lütfen', 'lüt-FEN', 'من فضلك', 'تکایە', ['Lütfen bir bardak su.', 'lüt-FEN bir bar-DAK SU', 'كوب ماء من فضلك.', 'تکایە پەرداخێک ئاو.']),
  w('Affedersiniz', 'af-fe-der-si-NİZ', 'عذراً / اسمح لي', 'ببوورە', ['Affedersiniz, saat kaç?', 'af-fe-der-si-NİZ sa-AT KAÇ', 'عذراً، كم الساعة؟', 'ببوورە، کاتژمێر چەندە؟']),
  w('Özür dilerim', 'ö-ZÜR di-le-rim', 'أعتذر / آسف', 'داوای لێبوردن دەکەم', ['Geciktim, özür dilerim.', 'ge-dijk-TİM ö-ZÜR di-le-rim', 'تأخرت، أعتذر.', 'درەنگ کەوتم، داوای لێبوردن دەکەم.']),
  w('Görüşürüz', 'gö-rü-şü-RÜZ', 'إلى اللقاء', 'دیدارمان', ['Yarın görüşürüz!', 'ya-RIN gö-rü-şü-RÜZ', 'نلتقي غداً!', 'سبەینێ دەبینینەوە!']),
  w('Hoşça kal', 'hoş-ÇA KAL', 'مع السلامة (يقولها المغادر)', 'خوات لەگەڵ (ئەوەی دەڕوات دەیڵێت)', ['Hoşça kal, kendine iyi bak.', 'hoş-ÇA KAL ken-di-NE i-Yİ BAK', 'مع السلامة، اعتنِ بنفسك.', 'خوات لەگەڵ، ئاگات لە خۆت بێت.']),
  w('Güle güle', 'gü-LE gü-LE', 'مع السلامة (يقولها الباقي)', 'بەخێر بڕۆ (ئەوەی دەمێنێتەوە دەیڵێت)', ['Güle güle, yine bekleriz.', 'gü-LE gü-LE yi-NE bek-le-RİZ', 'مع السلامة، ننتظرك ثانيةً.', 'بەخێر بڕۆ، دیسان چاوەڕێت دەکەین.']),
  w('Evet', 'e-VET', 'نعم', 'بەڵێ', ['Evet, doğru.', 'e-VET do-RU', 'نعم، صحيح.', 'بەڵێ، ڕاستە.']),
  w('Hayır', 'ha-YIR', 'لا', 'نەخێر', ['Hayır, teşekkürler.', 'ha-YIR te-şek-kür-LER', 'لا، شكراً.', 'نەخێر، سوپاس.']),
  w('Tamam', 'ta-MAM', 'حسناً / اتفقنا', 'باشە', ['Tamam, anladım.', 'ta-MAM an-la-DIM', 'حسناً، فهمت.', 'باشە، تێگەیشتم.']),
  w('Buyurun', 'bu-yu-RUN', 'تفضّل', 'فەرموو', ['Buyurun, oturun lütfen.', 'bu-yu-RUN o-tu-RUN lüt-FEN', 'تفضل، اجلس من فضلك.', 'فەرموو، تکایە دابنیشە.']),
  w('Memnun oldum', 'mem-NUN ol-dum', 'تشرفت بمعرفتك', 'خۆشحاڵ بووم بە ناسینت', ['Tanıştığımıza memnun oldum.', 'ta-nış-tı-ı-mı-ZA mem-NUN ol-dum', 'سررت بالتعرف عليك.', 'خۆشحاڵم بە ناسینت.']),
]);

const family = pack('family', 'a1', 'noun', [
  w('aile', 'a-i-LE', 'عائلة', 'خێزان', ['Ailem İstanbul’da yaşıyor.', 'a-i-LEM is-tan-BUL-da ya-şı-YOR', 'عائلتي تعيش في إسطنبول.', 'خێزانەکەم لە ئەستەنبوڵ دەژی.']),
  w('anne', 'an-NE', 'أم', 'دایک', ['Annem çok iyi yemek yapar.', 'an-NEM ÇOK i-Yİ ye-MEK ya-PAR', 'أمي تطبخ جيداً جداً.', 'دایکم زۆر باش خواردن دروست دەکات.']),
  w('baba', 'ba-BA', 'أب', 'باوک', ['Babam öğretmen.', 'ba-BAM öö-ret-MEN', 'أبي معلّم.', 'باوکم مامۆستایە.']),
  w('kardeş', 'kar-DEŞ', 'أخ أو أخت', 'خوشک یان برا', ['İki kardeşim var.', 'i-Kİ kar-de-ŞİM VAR', 'لديّ أخوان.', 'دوو خوشک و برام هەیە.']),
  w('abi', 'a-Bİ', 'أخ أكبر', 'برای گەورە', ['Abim üniversitede okuyor.', 'a-BİM ü-ni-ver-si-te-DE o-ku-YOR', 'أخي الأكبر يدرس في الجامعة.', 'برا گەورەکەم لە زانکۆ دەخوێنێت.']),
  w('abla', 'ab-LA', 'أخت كبرى', 'خوشکی گەورە', ['Ablam evli.', 'ab-LAM ev-Lİ', 'أختي الكبرى متزوجة.', 'خوشکە گەورەکەم هاوسەرداریە.']),
  w('oğul', 'o-UL', 'ابن', 'کوڕ', ['Oğlu beş yaşında.', 'o-LU BEŞ ya-şın-DA', 'ابنه في الخامسة من عمره.', 'کوڕەکەی پێنج ساڵانە.']),
  w('kız', 'KIZ', 'بنت / ابنة', 'کچ', ['Kızım okula gidiyor.', 'kı-ZIM o-ku-LA gi-di-YOR', 'ابنتي تذهب إلى المدرسة.', 'کچەکەم دەچێتە قوتابخانە.']),
  w('çocuk', 'ço-DJUK', 'طفل', 'منداڵ', ['Çocuklar bahçede oynuyor.', 'ço-djuk-LAR bah-çe-DE oy-nu-YOR', 'الأطفال يلعبون في الحديقة.', 'منداڵەکان لە باخچەکە یاری دەکەن.']),
  w('dede', 'de-DE', 'جدّ', 'باپیر', ['Dedem seksen yaşında.', 'de-DEM sek-SEN ya-şın-DA', 'جدي في الثمانين.', 'باپیرم هەشتا ساڵانە.']),
  w('büyükanne', 'bü-yük-an-NE', 'جدّة', 'داپیر', ['Büyükannem köyde oturuyor.', 'bü-yük-an-NEM köy-DE o-tu-ru-YOR', 'جدتي تسكن في القرية.', 'داپیرم لە گوند دەژی.']),
  w('amca', 'am-DJA', 'عمّ', 'مام', ['Amcam doktor.', 'am-DJAM dok-TOR', 'عمي طبيب.', 'مامم پزیشکە.']),
  w('dayı', 'da-YI', 'خال', 'خاڵ', ['Dayım Ankara’da çalışıyor.', 'da-YIM an-ka-RA-da ça-lı-şı-YOR', 'خالي يعمل في أنقرة.', 'خاڵم لە ئەنقەرە کار دەکات.']),
  w('hala', 'ha-LA', 'عمّة (أخت الأب)', 'پوورە (خوشکی باوک)', ['Halam bize geldi.', 'ha-LAM bi-ZE gel-Dİ', 'جاءت عمتي إلينا.', 'پوورەم هاتە لامان.']),
  w('teyze', 'tey-ZE', 'خالة (أخت الأم)', 'پوور (خوشکی دایک)', ['Teyzem çok tatlı bir insan.', 'tey-ZEM ÇOK tat-LI bir in-SAN', 'خالتي إنسانة لطيفة جداً.', 'پوورم مرۆڤێکی زۆر شیرینە.']),
  w('eş', 'EŞ', 'زوج أو زوجة', 'هاوسەر', ['Eşimle birlikte geldik.', 'e-şim-LE bir-lik-TE gel-DİK', 'جئنا معاً أنا وزوجي.', 'لەگەڵ هاوسەرەکەم پێکەوە هاتین.']),
  w('koca', 'ko-DJA', 'زوج', 'مێرد', ['Kocası mühendis.', 'ko-dja-SI mü-hen-DİS', 'زوجها مهندس.', 'مێردەکەی ئەندازیارە.']),
  w('torun', 'to-RUN', 'حفيد', 'نەوە', ['Üç torunu var.', 'ÜÇ to-ru-NU VAR', 'لديه ثلاثة أحفاد.', 'سێ نەوەی هەیە.']),
  w('akraba', 'ak-ra-BA', 'قريب / نسيب', 'خزم', ['Akrabalarımız Bursa’da.', 'ak-ra-ba-la-rı-MIZ bur-SA-da', 'أقاربنا في بورصة.', 'خزمەکانمان لە بوورسان.']),
  w('yeğen', 'ye-EN', 'ابن أو ابنة الأخ/الأخت', 'برازا / خوشکەزا', ['Yeğenim bugün doğdu.', 'ye-e-NİM bu-GÜN do-DU', 'وُلد ابن أخي اليوم.', 'برازاکەم ئەمڕۆ لەدایک بوو.']),
]);

const people = pack('people', 'a1', 'noun', [
  w('insan', 'in-SAN', 'إنسان', 'مرۆڤ', ['O çok iyi bir insan.', 'O ÇOK i-Yİ bir in-SAN', 'هو إنسان طيب جداً.', 'ئەو مرۆڤێکی زۆر باشە.']),
  w('adam', 'a-DAM', 'رجل', 'پیاو', ['Kapıda bir adam var.', 'ka-pı-DA bir a-DAM VAR', 'يوجد رجل عند الباب.', 'لە دەرگاکە پیاوێک هەیە.']),
  w('kadın', 'ka-DIN', 'امرأة', 'ژن', ['O kadın benim öğretmenim.', 'O ka-DIN be-NİM öö-ret-me-NİM', 'تلك المرأة معلّمتي.', 'ئەو ژنە مامۆستاکەمە.']),
  w('erkek', 'er-KEK', 'ذكر / رجل', 'نێر / پیاو', ['Erkek kardeşim var.', 'er-KEK kar-de-ŞİM VAR', 'لديّ أخ.', 'برام هەیە.']),
  w('arkadaş', 'ar-ka-DAŞ', 'صديق', 'هاوڕێ', ['En iyi arkadaşım Ahmet.', 'EN i-Yİ ar-ka-da-ŞIM ah-MET', 'أفضل أصدقائي أحمد.', 'باشترین هاوڕێم ئەحمەدە.']),
  w('komşu', 'kom-ŞU', 'جار', 'دراوسێ', ['Komşumuz çok yardımsever.', 'kom-şu-MUZ ÇOK yar-dım-se-VER', 'جارنا كثير المساعدة.', 'دراوسێکەمان زۆر یارمەتیدەرە.']),
  w('öğrenci', 'öö-ren-DJİ', 'طالب', 'قوتابی', ['Ben bir öğrenciyim.', 'BEN bir öö-ren-Cİ-yim', 'أنا طالب.', 'من قوتابیم.']),
  w('öğretmen', 'öö-ret-MEN', 'معلّم', 'مامۆستا', ['Öğretmenimiz çok sabırlı.', 'öö-ret-me-ni-MİZ ÇOK sa-bır-LI', 'معلّمنا صبور جداً.', 'مامۆستاکەمان زۆر ئارامە.']),
  w('doktor', 'dok-TOR', 'طبيب', 'پزیشک', ['Doktora gitmem lazım.', 'dok-to-RA git-MEM la-ZIM', 'يجب أن أذهب إلى الطبيب.', 'پێویستە بچمە لای پزیشک.']),
  w('misafir', 'mi-sa-FİR', 'ضيف', 'میوان', ['Bugün misafirimiz var.', 'bu-GÜN mi-sa-fi-ri-MİZ VAR', 'لدينا ضيوف اليوم.', 'ئەمڕۆ میوانمان هەیە.']),
  w('genç', 'GENÇ', 'شاب / يافع', 'گەنج', ['Genç bir öğretmen.', 'GENÇ bir öö-ret-MEN', 'معلّم شاب.', 'مامۆستایەکی گەنج.']),
  w('yaşlı', 'yaş-LI', 'مُسنّ', 'بەتەمەن', ['Yaşlı adama yardım ettim.', 'yaş-LI a-da-MA yar-DIM et-tim', 'ساعدت الرجل المسنّ.', 'یارمەتی پیاوە بەتەمەنەکەم دا.']),
  w('isim', 'i-SİM', 'اسم', 'ناو', ['İsminiz ne?', 'is-mi-NİZ NE', 'ما اسمك؟', 'ناوت چییە؟']),
  w('yaş', 'YAŞ', 'عُمر / سنة (من العمر)', 'تەمەن', ['Kaç yaşındasın?', 'KAÇ ya-şın-da-SIN', 'كم عمرك؟', 'تەمەنت چەندە؟']),
  w('meslek', 'mes-LEK', 'مهنة', 'پیشە', ['Mesleğiniz nedir?', 'mes-le-i-NİZ ne-DİR', 'ما مهنتك؟', 'پیشەکەت چییە؟']),
]);


const numberWords = pack('numbers', 'a1', 'number', [
  w('bir', 'BİR', 'واحد', 'یەک', ['Bir bardak çay lütfen.', 'bir bar-DAK ÇAY lüt-FEN', 'كوب شاي واحد من فضلك.', 'پەرداخێک چا تکایە.']),
  w('iki', 'i-Kİ', 'اثنان', 'دوو', ['İki kardeşim var.', 'i-Kİ kar-de-ŞİM VAR', 'لديّ أخوان.', 'دوو خوشک و برام هەیە.']),
  w('üç', 'ÜÇ', 'ثلاثة', 'سێ', ['Üç gün sonra geliyorum.', 'ÜÇ GÜN son-RA ge-li-YO-rum', 'سآتي بعد ثلاثة أيام.', 'دوای سێ ڕۆژ دێم.']),
  w('dört', 'DÖRT', 'أربعة', 'چوار', ['Dört mevsim var.', 'DÖRT mev-SİM VAR', 'هناك أربعة فصول.', 'چوار وەرز هەیە.']),
  w('beş', 'BEŞ', 'خمسة', 'پێنج', ['Beş dakika bekle.', 'BEŞ da-ki-KA bek-LE', 'انتظر خمس دقائق.', 'پێنج خولەک چاوەڕێ بکە.']),
  w('altı', 'al-TI', 'ستة', 'شەش', ['Saat altıda buluşalım.', 'sa-AT al-tı-DA bu-lu-şa-LIM', 'لنلتقِ الساعة السادسة.', 'کاتژمێر شەش یەکتر ببینین.']),
  w('yedi', 'ye-Dİ', 'سبعة', 'حەوت', ['Haftada yedi gün var.', 'haf-ta-DA ye-Dİ GÜN VAR', 'في الأسبوع سبعة أيام.', 'لە هەفتەیەکدا حەوت ڕۆژ هەیە.']),
  w('sekiz', 'se-KİZ', 'ثمانية', 'هەشت', ['Ders sekizde başlıyor.', 'DERS se-kiz-DE baş-lı-YOR', 'يبدأ الدرس في الثامنة.', 'وانەکە کاتژمێر هەشت دەست پێدەکات.']),
  w('dokuz', 'do-KUZ', 'تسعة', 'نۆ', ['Dokuz yaşındayım.', 'do-KUZ ya-şın-da-YIM', 'عمري تسع سنوات.', 'تەمەنم نۆ ساڵە.']),
  w('on', 'ON', 'عشرة', 'دە', ['On kelime öğrendim.', 'ON ke-li-ME öö-ren-DİM', 'تعلّمت عشر كلمات.', 'دە وشەم فێربوو.']),
  w('yirmi', 'yir-Mİ', 'عشرون', 'بیست', ['Yirmi lira verdim.', 'yir-Mİ li-RA ver-DİM', 'دفعت عشرين ليرة.', 'بیست لیرەم دا.']),
  w('otuz', 'o-TUZ', 'ثلاثون', 'سی', ['Otuz derece sıcak.', 'o-TUZ de-re-DJE sı-DJAK', 'الحرارة ثلاثون درجة.', 'گەرمی سی پلەیە.']),
  w('yüz', 'YÜZ', 'مئة', 'سەد', ['Yüz kişi geldi.', 'YÜZ ki-Şİ gel-Dİ', 'جاء مئة شخص.', 'سەد کەس هات.']),
  w('bin', 'BİN', 'ألف', 'هەزار', ['Bin lira ödedim.', 'BİN li-RA ö-de-DİM', 'دفعت ألف ليرة.', 'هەزار لیرەم دا.']),
  w('milyon', 'mil-YON', 'مليون', 'ملیۆن', ['Bir milyon insan yaşıyor.', 'bir mil-YON in-SAN ya-şı-YOR', 'يعيش مليون شخص.', 'یەک ملیۆن کەس دەژی.']),
  w('sıfır', 'sı-FIR', 'صفر', 'سفر', ['Sıcaklık sıfır derece.', 'sı-djak-LIK sı-FIR de-re-DJE', 'الحرارة صفر درجة.', 'پلەی گەرمی سفرە.']),
  w('birinci', 'bi-rin-DJİ', 'الأول', 'یەکەم', ['Birinci kattayım.', 'bi-rin-DJİ kat-ta-YIM', 'أنا في الطابق الأول.', 'لە نهۆمی یەکەمم.'], 'adjective'),
  w('ikinci', 'i-kin-DJİ', 'الثاني', 'دووەم', ['İkinci sırada bekliyorum.', 'i-kin-DJİ sı-ra-DA bek-li-YO-rum', 'أنتظر في المركز الثاني.', 'لە ڕیزی دووەمدا چاوەڕوانم.'], 'adjective'),
  w('yarım', 'ya-RIM', 'نصف', 'نیو', ['Yarım saat sonra gel.', 'ya-RIM sa-AT son-RA GEL', 'تعال بعد نصف ساعة.', 'دوای نیو کاتژمێر وەرە.'], 'adjective'),
  w('çeyrek', 'çey-REK', 'ربع', 'چارەگ', ['Saat üçe çeyrek var.', 'sa-AT ü-ÇE çey-REK VAR', 'الساعة الثالثة إلا ربعاً.', 'چارەگ بۆ سێ.']),
]);

const colors = pack('colors', 'a1', 'adjective', [
  w('renk', 'RENK', 'لون', 'ڕەنگ', ['En sevdiğin renk ne?', 'EN sev-di-İN RENK NE', 'ما لونك المفضل؟', 'خۆشەویسترین ڕەنگت چییە؟']),
  w('kırmızı', 'kır-mı-ZI', 'أحمر', 'سوور', ['Kırmızı bir elbise aldım.', 'kır-mı-ZI bir el-bi-SE al-DIM', 'اشتريت فستاناً أحمر.', 'کراسێکی سوورم کڕی.']),
  w('mavi', 'ma-Vİ', 'أزرق', 'شین', ['Deniz çok mavi.', 'de-NİZ ÇOK ma-Vİ', 'البحر أزرق جداً.', 'دەریا زۆر شینە.']),
  w('yeşil', 'ye-ŞİL', 'أخضر', 'سەوز', ['Yeşil ışık yandı.', 'ye-ŞİL ı-ŞIK yan-DI', 'أضاء الضوء الأخضر.', 'ڕووناکی سەوز هەڵگیرسا.']),
  w('sarı', 'sa-RI', 'أصفر', 'زەرد', ['Sarı bir taksi geldi.', 'sa-RI bir tak-Sİ gel-Dİ', 'جاءت سيارة أجرة صفراء.', 'تاکسییەکی زەرد هات.']),
  w('siyah', 'si-YAH', 'أسود', 'ڕەش', ['Siyah çanta senin mi?', 'si-YAH çan-TA se-NİN mi', 'هل الحقيبة السوداء لك؟', 'جانتا ڕەشەکە هی تۆیە؟']),
  w('beyaz', 'be-YAZ', 'أبيض', 'سپی', ['Beyaz gömlek giydi.', 'be-YAZ göm-LEK giy-Dİ', 'ارتدى قميصاً أبيض.', 'کراسێکی سپی لەبەرکرد.']),
  w('turuncu', 'tu-run-DJU', 'برتقالي', 'پرتەقاڵی', ['Turuncu çok canlı bir renk.', 'tu-run-DJU ÇOK djan-LI bir RENK', 'البرتقالي لون حيوي جداً.', 'پرتەقاڵی ڕەنگێکی زۆر زیندووە.']),
  w('mor', 'MOR', 'بنفسجي', 'مۆر', ['Mor çiçekleri seviyorum.', 'MOR çi-çek-le-Rİ se-vi-YO-rum', 'أحب الزهور البنفسجية.', 'گوڵە مۆرەکانم خۆشدەوێت.']),
  w('pembe', 'pem-BE', 'وردي', 'پەمەیی', ['Pembe bir defter aldı.', 'pem-BE bir def-TER al-DI', 'اشترى دفتراً وردياً.', 'دەفتەرێکی پەمەیی کڕی.']),
  w('kahverengi', 'kah-ve-ren-Gİ', 'بنّي', 'قاوەیی', ['Kahverengi gözleri var.', 'kah-ve-ren-Gİ göz-le-Rİ VAR', 'لديه عينان بنيتان.', 'چاوی قاوەیی هەیە.']),
  w('gri', 'GRİ', 'رمادي', 'خۆڵەمێشی', ['Bugün hava gri.', 'bu-GÜN ha-VA GRİ', 'الجو رمادي اليوم.', 'ئەمڕۆ کەشوهەوا خۆڵەمێشییە.']),
  w('lacivert', 'la-dji-VERT', 'كحلي', 'شینی تۆخ', ['Lacivert takım elbise.', 'la-dji-VERT ta-KIM el-bi-SE', 'بدلة كحلية.', 'جلێکی شینی تۆخ.']),
]);

const days = pack('days', 'a1', 'noun', [
  w('Pazartesi', 'pa-zar-te-Sİ', 'الاثنين', 'دووشەممە', ['Pazartesi işe gidiyorum.', 'pa-zar-te-Sİ i-ŞE gi-di-YO-rum', 'يوم الاثنين أذهب إلى العمل.', 'دووشەممە دەچمە سەر کار.']),
  w('Salı', 'sa-LI', 'الثلاثاء', 'سێشەممە', ['Salı günü dersim var.', 'sa-LI gü-NÜ der-SİM VAR', 'لديّ درس يوم الثلاثاء.', 'ڕۆژی سێشەممە وانەم هەیە.']),
  w('Çarşamba', 'çar-şam-BA', 'الأربعاء', 'چوارشەممە', ['Çarşamba pazarı kuruluyor.', 'çar-şam-BA pa-za-RI ku-ru-lu-YOR', 'يُقام سوق الأربعاء.', 'بازاڕی چوارشەممە دادەنرێت.']),
  w('Perşembe', 'per-şem-BE', 'الخميس', 'پێنجشەممە', ['Perşembe akşamı boşum.', 'per-şem-BE ak-şa-MI bo-ŞUM', 'أنا فارغ مساء الخميس.', 'ئێوارەی پێنجشەممە بەتاڵم.']),
  w('Cuma', 'dju-MA', 'الجمعة', 'هەینی', ['Cuma günü camiye gideriz.', 'dju-MA gü-NÜ dja-mi-YE gi-de-RİZ', 'نذهب إلى المسجد يوم الجمعة.', 'ڕۆژی هەینی دەچینە مزگەوت.']),
  w('Cumartesi', 'dju-mar-te-Sİ', 'السبت', 'شەممە', ['Cumartesi tatil.', 'dju-mar-te-Sİ ta-TİL', 'السبت عطلة.', 'شەممە پشووە.']),
  w('Pazar', 'pa-ZAR', 'الأحد', 'یەکشەممە', ['Pazar günü dinleniyorum.', 'pa-ZAR gü-NÜ din-le-ni-YO-rum', 'أستريح يوم الأحد.', 'ڕۆژی یەکشەممە پشوو دەدەم.']),
  w('hafta içi', 'haf-TA i-çi', 'أيام العمل / وسط الأسبوع', 'ناوەڕاستی هەفتە', ['Hafta içi çok meşgulüm.', 'haf-TA i-Çİ ÇOK meş-gu-LÜM', 'أنا مشغول جداً في أيام الأسبوع.', 'ناوەڕاستی هەفتە زۆر سەرقاڵم.']),
  w('hafta sonu', 'haf-TA so-nu', 'عطلة نهاية الأسبوع', 'کۆتایی هەفتە', ['Hafta sonu ne yapıyorsun?', 'haf-TA so-NU NE ya-pı-yor-sun', 'ماذا تفعل في عطلة نهاية الأسبوع؟', 'کۆتایی هەفتە چی دەکەیت؟']),
]);

const months = pack('months', 'a1', 'noun', [
  w('Ocak', 'o-DJAK', 'يناير / كانون الثاني', 'کانوونی دووەم'),
  w('Şubat', 'şu-BAT', 'فبراير / شباط', 'شوبات'),
  w('Mart', 'MART', 'مارس / آذار', 'ئازار'),
  w('Nisan', 'ni-SAN', 'أبريل / نيسان', 'نیسان'),
  w('Mayıs', 'ma-YIS', 'مايو / أيار', 'ئایار'),
  w('Haziran', 'ha-zi-RAN', 'يونيو / حزيران', 'حوزەیران'),
  w('Temmuz', 'tem-MUZ', 'يوليو / تموز', 'تەمموز'),
  w('Ağustos', 'a-us-TOS', 'أغسطس / آب', 'ئاب'),
  w('Eylül', 'ey-LÜL', 'سبتمبر / أيلول', 'ئەیلوول'),
  w('Ekim', 'e-KİM', 'أكتوبر / تشرين الأول', 'تشرینی یەکەم'),
  w('Kasım', 'ka-SIM', 'نوفمبر / تشرين الثاني', 'تشرینی دووەم'),
  w('Aralık', 'a-ra-LIK', 'ديسمبر / كانون الأول', 'کانوونی یەکەم'),
  w('mevsim', 'mev-SİM', 'فصل (من فصول السنة)', 'وەرز', ['Dört mevsim var.', 'DÖRT mev-SİM VAR', 'هناك أربعة فصول.', 'چوار وەرز هەیە.']),
  w('ilkbahar', 'ilk-ba-HAR', 'الربيع', 'بەهار', ['İlkbaharda çiçekler açar.', 'ilk-ba-har-DA çi-çek-LER a-ÇAR', 'تتفتح الأزهار في الربيع.', 'لە بەهاردا گوڵەکان دەکرێنەوە.']),
  w('yaz', 'YAZ', 'الصيف', 'هاوین', ['Yazın denize gideriz.', 'ya-ZIN de-ni-ZE gi-de-RİZ', 'نذهب إلى البحر في الصيف.', 'لە هاویندا دەچینە دەریا.']),
  w('sonbahar', 'son-ba-HAR', 'الخريف', 'پاییز', ['Sonbaharda yapraklar döküldü.', 'son-ba-har-DA yap-rak-LAR dö-kül-DÜ', 'تساقطت الأوراق في الخريف.', 'لە پاییزدا گەڵاکان وەریان کرد.']),
  w('kış', 'KIŞ', 'الشتاء', 'زستان', ['Kışın çok kar yağar.', 'kı-ŞIN ÇOK KAR ya-AR', 'يتساقط الثلج كثيراً في الشتاء.', 'لە زستاندا زۆر بەفر دەبارێت.']),
]);

const time = pack('time', 'a1', 'noun', [
  w('zaman', 'za-MAN', 'وقت / زمن', 'کات', ['Zamanım yok.', 'za-ma-NIM YOK', 'ليس لديّ وقت.', 'کاتم نییە.']),
  w('saat', 'sa-AT', 'ساعة', 'کاتژمێر', ['Saat kaç?', 'sa-AT KAÇ', 'كم الساعة؟', 'کاتژمێر چەندە؟']),
  w('gün', 'GÜN', 'يوم', 'ڕۆژ', ['Güzel bir gün.', 'gü-ZEL bir GÜN', 'يوم جميل.', 'ڕۆژێکی جوان.']),
  w('hafta', 'haf-TA', 'أسبوع', 'هەفتە', ['Gelecek hafta görüşelim.', 'ge-le-DJEK haf-TA gö-rü-şe-LİM', 'لنلتقِ الأسبوع القادم.', 'هەفتەی داهاتوو یەکتر ببینین.']),
  w('ay', 'AY', 'شهر / قمر', 'مانگ', ['Bu ay çok çalıştım.', 'BU AY ÇOK ça-lış-TIM', 'عملت كثيراً هذا الشهر.', 'ئەم مانگە زۆر کارم کرد.']),
  w('yıl', 'YIL', 'سنة', 'ساڵ', ['İki yıldır Türkçe öğreniyorum.', 'i-Kİ yıl-DIR türk-ÇE öö-re-ni-YO-rum', 'أتعلم التركية منذ سنتين.', 'دوو ساڵە فێری تورکی دەبم.']),
  w('bugün', 'bu-GÜN', 'اليوم', 'ئەمڕۆ', ['Bugün hava güzel.', 'bu-GÜN ha-VA gü-ZEL', 'الجو جميل اليوم.', 'ئەمڕۆ کەشوهەوا جوانە.']),
  w('yarın', 'ya-RIN', 'غداً', 'سبەینێ', ['Yarın sınavım var.', 'ya-RIN sı-na-VIM VAR', 'لديّ امتحان غداً.', 'سبەینێ تاقیکردنەوەم هەیە.']),
  w('dün', 'DÜN', 'أمس', 'دوێنێ', ['Dün sinemaya gittik.', 'DÜN si-ne-ma-YA git-TİK', 'ذهبنا إلى السينما أمس.', 'دوێنێ چووینە سینەما.']),
  w('şimdi', 'şim-Dİ', 'الآن', 'ئێستا', ['Şimdi meşgulüm.', 'şim-Dİ meş-gu-LÜM', 'أنا مشغول الآن.', 'ئێستا سەرقاڵم.']),
  w('sonra', 'son-RA', 'بعد / لاحقاً', 'دواتر', ['Sonra konuşuruz.', 'son-RA ko-nu-şu-RUZ', 'سنتحدث لاحقاً.', 'دواتر قسە دەکەین.']),
  w('önce', 'ön-DJE', 'قبل', 'پێشتر', ['Yemekten önce ellerini yıka.', 'ye-mek-TEN ön-DJE el-le-ri-Nİ yı-KA', 'اغسل يديك قبل الطعام.', 'پێش خواردن دەستەکانت بشۆ.']),
  w('sabah', 'sa-BAH', 'صباح', 'بەیانی', ['Sabah erken kalkarım.', 'sa-BAH er-KEN kal-ka-RIM', 'أستيقظ باكراً في الصباح.', 'بەیانی زوو هەڵدەستم.']),
  w('öğle', 'öö-LE', 'ظهر', 'نیوەڕۆ', ['Öğlen yemek yeriz.', 'öö-LEN ye-MEK ye-RİZ', 'نأكل الطعام ظهراً.', 'نیوەڕۆ نان دەخۆین.']),
  w('akşam', 'ak-ŞAM', 'مساء', 'ئێوارە', ['Akşam eve dönerim.', 'ak-ŞAM e-VE dö-ne-RİM', 'أعود إلى البيت مساءً.', 'ئێوارە دەگەڕێمەوە ماڵ.']),
  w('gece', 'ge-DJE', 'ليل', 'شەو', ['Gece geç yattım.', 'ge-DJE GEÇ yat-TIM', 'نمت متأخراً ليلاً.', 'شەو درەنگ نووستم.']),
  w('erken', 'er-KEN', 'مبكّراً', 'زوو', ['Çok erken geldin.', 'ÇOK er-KEN gel-DİN', 'جئت مبكراً جداً.', 'زۆر زوو هاتیت.']),
  w('geç', 'GEÇ', 'متأخّراً', 'درەنگ', ['Geç kaldım, özür dilerim.', 'GEÇ kal-DIM ö-ZÜR di-le-rim', 'تأخرت، أعتذر.', 'درەنگ کەوتم، ببوورە.']),
  w('her gün', 'her GÜN', 'كل يوم', 'هەموو ڕۆژێک', ['Her gün ders çalışırım.', 'her GÜN DERS ça-lı-şı-RIM', 'أدرس كل يوم.', 'هەموو ڕۆژێک وانە دەخوێنم.']),
  w('bazen', 'ba-ZEN', 'أحياناً', 'هەندێک جار', ['Bazen çay içerim.', 'ba-ZEN ÇAY i-çe-RİM', 'أشرب الشاي أحياناً.', 'هەندێک جار چا دەخۆمەوە.']),
  w('her zaman', 'her za-MAN', 'دائماً', 'هەمیشە', ['Her zaman yardım eder.', 'her za-MAN yar-DIM e-DER', 'يساعد دائماً.', 'هەمیشە یارمەتی دەدات.']),
  w('hiçbir zaman', 'hiç-BİR za-man', 'أبداً / في أي وقت', 'هەرگیز', ['Hiçbir zaman unutmam.', 'hiç-BİR za-MAN u-nut-MAM', 'لن أنسى أبداً.', 'هەرگیز لەبیری ناکەم.']),
]);

const food = pack('food', 'a1', 'noun', [
  w('yemek', 'ye-MEK', 'طعام / وجبة', 'خواردن', ['Yemek çok lezzetli.', 'ye-MEK ÇOK lez-zet-Lİ', 'الطعام لذيذ جداً.', 'خواردنەکە زۆر خۆشە.']),
  w('ekmek', 'ek-MEK', 'خبز', 'نان', ['Fırından ekmek aldım.', 'fı-rın-DAN ek-MEK al-DIM', 'اشتريت خبزاً من المخبز.', 'لە نانەواخانە نانم کڕی.']),
  w('peynir', 'pey-NİR', 'جبن', 'پەنیر', ['Kahvaltıda peynir yerim.', 'kah-val-tı-DA pey-NİR ye-rim', 'آكل الجبن في الفطور.', 'لە نانی بەیانیدا پەنیر دەخۆم.']),
  w('yumurta', 'yu-mur-TA', 'بيض', 'هێلکە', ['İki yumurta lütfen.', 'i-Kİ yu-mur-TA lüt-FEN', 'بيضتان من فضلك.', 'دوو هێلکە تکایە.']),
  w('et', 'ET', 'لحم', 'گۆشت', ['Kırmızı et yemiyorum.', 'kır-mı-ZI ET ye-mi-YO-rum', 'لا آكل اللحم الأحمر.', 'گۆشتی سوور ناخۆم.']),
  w('tavuk', 'ta-VUK', 'دجاج', 'مریشک', ['Tavuklu pilav sevdim.', 'ta-vuk-LU pi-LAV sev-DİM', 'أحببت الأرز بالدجاج.', 'برنجی مریشکم پێ خۆش بوو.']),
  w('balık', 'ba-LIK', 'سمك', 'ماسی', ['Balık ekmek yiyelim.', 'ba-LIK ek-MEK yi-ye-LİM', 'لنأكل سندويشة السمك.', 'با ماسی و نان بخۆین.']),
  w('pirinç', 'pi-RİNÇ', 'أرز (حبّاً)', 'برنج', ['Bir kilo pirinç aldım.', 'bir Kİ-lo pi-RİNÇ al-DIM', 'اشتريت كيلو أرز.', 'کیلۆیەک برنجم کڕی.']),
  w('çorba', 'çor-BA', 'شوربة', 'شۆربا', ['Mercimek çorbası içtim.', 'mer-dji-MEK çor-ba-SI iç-TİM', 'شربت شوربة العدس.', 'شۆربای نیسکم خواردەوە.']),
  w('salata', 'sa-la-TA', 'سلطة', 'زەڵاتە', ['Yanında salata var mı?', 'ya-nın-DA sa-la-TA var MI', 'هل معه سلطة؟', 'لەگەڵیدا زەڵاتە هەیە؟']),
  w('meyve', 'mey-VE', 'فاكهة', 'میوە', ['Her gün meyve yerim.', 'her GÜN mey-VE ye-rim', 'آكل الفاكهة كل يوم.', 'هەموو ڕۆژێک میوە دەخۆم.']),
  w('sebze', 'seb-ZE', 'خضار', 'سەوزە', ['Sebzeler çok taze.', 'seb-ze-LER ÇOK ta-ZE', 'الخضار طازجة جداً.', 'سەوزەکان زۆر تازەن.']),
  w('elma', 'el-MA', 'تفاح', 'سێو', ['Kırmızı elma istiyorum.', 'kır-mı-ZI el-MA is-ti-YO-rum', 'أريد تفاحة حمراء.', 'سێوی سوورم دەوێت.']),
  w('portakal', 'por-ta-KAL', 'برتقال', 'پرتەقاڵ', ['Portakal suyu sever misin?', 'por-ta-KAL su-YU se-VER mi-sin', 'هل تحب عصير البرتقال؟', 'ئاوی پرتەقاڵت خۆشدەوێت؟']),
  w('muz', 'MUZ', 'موز', 'مۆز', ['Çocuklar muzu çok sever.', 'ço-djuk-LAR mu-ZU ÇOK se-VER', 'الأطفال يحبون الموز كثيراً.', 'منداڵان زۆر مۆزیان خۆشدەوێت.']),
  w('karpuz', 'kar-PUZ', 'بطيخ', 'شووتی', ['Yazın karpuz yeriz.', 'ya-ZIN kar-PUZ ye-RİZ', 'نأكل البطيخ في الصيف.', 'لە هاویندا شووتی دەخۆین.']),
  w('domates', 'do-ma-TES', 'طماطم', 'تەماتە', ['Salataya domates koy.', 'sa-la-ta-YA do-ma-TES KOY', 'ضع الطماطم في السلطة.', 'تەماتە بخە ناو زەڵاتەکە.']),
  w('salatalık', 'sa-la-ta-LIK', 'خيار', 'خەیار', ['Bir salatalık daha ver.', 'bir sa-la-ta-LIK da-HA VER', 'أعطني خيارة أخرى.', 'خەیارێکی تر بدە.']),
  w('soğan', 'so-AN', 'بصل', 'پیاز', ['Soğan doğradım.', 'so-AN do-ra-DIM', 'قطّعت البصل.', 'پیازم وردکرد.']),
  w('patates', 'pa-ta-TES', 'بطاطا', 'پەتاتە', ['Patates kızartması yaptım.', 'pa-ta-TES kı-zart-ma-SI yap-TIM', 'حضّرت بطاطا مقلية.', 'پەتاتەی برژاوم دروستکرد.']),
  w('tuz', 'TUZ', 'ملح', 'خوێ', ['Yemekte tuz az.', 'ye-mek-TE TUZ AZ', 'الملح قليل في الطعام.', 'خوێ لە خواردنەکەدا کەمە.']),
  w('şeker', 'şe-KER', 'سكر', 'شەکر', ['Çaya şeker koyar mısın?', 'ça-YA şe-KER ko-YAR mı-sın', 'هل تضع سكراً في الشاي؟', 'شەکر دەخەیتە ناو چاکە؟']),
  w('zeytin', 'zey-TİN', 'زيتون', 'زەیتوون', ['Siyah zeytin çok severim.', 'si-YAH zey-TİN ÇOK se-ve-rim', 'أحب الزيتون الأسود كثيراً.', 'زەیتوونی ڕەشم زۆر خۆشدەوێت.']),
  w('tatlı', 'tat-LI', 'حلوى / حلو المذاق', 'شیرینی', ['Tatlı yemek ister misin?', 'tat-LI ye-MEK is-TER mi-sin', 'هل تريد أن تأكل حلوى؟', 'دەتەوێت شیرینی بخۆیت؟']),
  w('kahvaltı', 'kah-val-TI', 'فطور', 'نانی بەیانی', ['Kahvaltı hazır.', 'kah-val-TI ha-ZIR', 'الفطور جاهز.', 'نانی بەیانی ئامادەیە.']),
]);

const drinks = pack('drinks', 'a1', 'noun', [
  w('içecek', 'i-çe-DJEK', 'مشروب', 'خواردنەوە', ['Ne içecek istersiniz?', 'NE i-çe-DJEK is-ter-si-niz', 'ماذا تريدون أن تشربوا؟', 'چ خواردنەوەیەکتان دەوێت؟']),
  w('su', 'SU', 'ماء', 'ئاو', ['Bir bardak su lütfen.', 'bir bar-DAK SU lüt-FEN', 'كوب ماء من فضلك.', 'پەرداخێک ئاو تکایە.']),
  w('çay', 'ÇAY', 'شاي', 'چا', ['Türkler çok çay içer.', 'türk-LER ÇOK ÇAY i-ÇER', 'الأتراك يشربون الشاي كثيراً.', 'تورکەکان زۆر چا دەخۆنەوە.']),
  w('kahve', 'kah-VE', 'قهوة', 'قاوە', ['Türk kahvesi içelim.', 'TÜRK kah-ve-Sİ i-çe-LİM', 'لنشرب القهوة التركية.', 'با قاوەی تورکی بخۆینەوە.']),
  w('süt', 'SÜT', 'حليب', 'شیر', ['Sabahları süt içerim.', 'sa-bah-la-RI SÜT i-çe-rim', 'أشرب الحليب في الصباح.', 'بەیانیان شیر دەخۆمەوە.']),
  w('ayran', 'ay-RAN', 'عيران (لبن مخيض)', 'دەو', ['Yanına ayran alalım.', 'ya-nı-NA ay-RAN a-la-LIM', 'لنأخذ عيران معه.', 'با لەگەڵیدا دەو وەربگرین.']),
  w('meyve suyu', 'mey-VE su-yu', 'عصير فاكهة', 'ئاوی میوە', ['Taze meyve suyu var mı?', 'ta-ZE mey-VE su-YU var MI', 'هل يوجد عصير طازج؟', 'ئاوی میوەی تازە هەیە؟']),
  w('buz', 'BUZ', 'ثلج (مكعبات)', 'سەهۆڵ', ['Buzlu su istiyorum.', 'buz-LU SU is-ti-YO-rum', 'أريد ماءً مثلجاً.', 'ئاوی سارد دەمەوێت.']),
  w('bardak', 'bar-DAK', 'كوب', 'پەرداخ', ['Bardağı kırdım.', 'bar-da-I kır-DIM', 'كسرت الكوب.', 'پەرداخەکەم شکاند.']),
]);

const house = pack('house', 'a1', 'noun', [
  w('ev', 'EV', 'بيت', 'ماڵ', ['Evim okula yakın.', 'e-VİM o-ku-LA ya-KIN', 'بيتي قريب من المدرسة.', 'ماڵەکەم نزیکە لە قوتابخانە.']),
  w('oda', 'o-DA', 'غرفة', 'ژوور', ['Odam çok küçük.', 'o-DAM ÇOK kü-ÇÜK', 'غرفتي صغيرة جداً.', 'ژوورەکەم زۆر بچووکە.']),
  w('mutfak', 'mut-FAK', 'مطبخ', 'چێشتخانە', ['Annem mutfakta.', 'an-NEM mut-fak-TA', 'أمي في المطبخ.', 'دایکم لە چێشتخانەیە.']),
  w('banyo', 'ban-YO', 'حمّام', 'حەمام', ['Banyo nerede?', 'ban-YO ne-re-DE', 'أين الحمام؟', 'حەمام لە کوێیە؟']),
  w('salon', 'sa-LON', 'صالة الجلوس', 'دیوەخان', ['Misafirler salonda.', 'mi-sa-fir-LER sa-lon-DA', 'الضيوف في الصالة.', 'میوانەکان لە دیوەخانن.']),
  w('kapı', 'ka-PI', 'باب', 'دەرگا', ['Kapıyı kapat lütfen.', 'ka-pı-YI ka-PAT lüt-FEN', 'أغلق الباب من فضلك.', 'تکایە دەرگاکە دابخە.']),
  w('pencere', 'pen-dje-RE', 'نافذة', 'پەنجەرە', ['Pencereyi açalım.', 'pen-dje-re-Yİ a-ça-LIM', 'لنفتح النافذة.', 'با پەنجەرەکە بکەینەوە.']),
  w('masa', 'ma-SA', 'طاولة', 'مێز', ['Kitap masanın üstünde.', 'ki-TAP ma-sa-NIN üs-tün-DE', 'الكتاب على الطاولة.', 'کتێبەکە لەسەر مێزەکەیە.']),
  w('sandalye', 'san-dal-YE', 'كرسي', 'کورسی', ['Bir sandalye daha getir.', 'bir san-dal-YE da-HA ge-TİR', 'أحضر كرسياً آخر.', 'کورسییەکی تر بهێنە.']),
  w('yatak', 'ya-TAK', 'سرير', 'قەرەوێڵە', ['Yatağım çok rahat.', 'ya-ta-IM ÇOK ra-HAT', 'سريري مريح جداً.', 'قەرەوێڵەکەم زۆر ئاسوودەیە.']),
  w('dolap', 'do-LAP', 'خزانة', 'دۆڵاب', ['Giysiler dolapta.', 'giy-si-LER do-lap-TA', 'الملابس في الخزانة.', 'جلوبەرگەکان لە دۆڵابەکەن.']),
  w('halı', 'ha-LI', 'سجادة', 'فەرش', ['Türk halısı çok ünlü.', 'TÜRK ha-lı-SI ÇOK ün-LÜ', 'السجاد التركي مشهور جداً.', 'فەرشی تورکی زۆر بەناوبانگە.']),
  w('perde', 'per-DE', 'ستارة', 'پەردە', ['Perdeleri çektim.', 'per-de-le-Rİ çek-TİM', 'أسدلت الستائر.', 'پەردەکانم ڕاکێشا.']),
  w('ayna', 'ay-NA', 'مرآة', 'ئاوێنە', ['Aynaya baktım.', 'ay-na-YA bak-TIM', 'نظرت في المرآة.', 'سەیری ئاوێنەکەم کرد.']),
  w('bahçe', 'bah-ÇE', 'حديقة المنزل', 'باخچە', ['Bahçede çiçek var.', 'bah-çe-DE çi-ÇEK VAR', 'يوجد زهر في الحديقة.', 'لە باخچەکەدا گوڵ هەیە.']),
  w('kat', 'KAT', 'طابق', 'نهۆم', ['Üçüncü katta oturuyorum.', 'ü-çün-DJÜ kat-TA o-tu-ru-YO-rum', 'أسكن في الطابق الثالث.', 'لە نهۆمی سێیەم دەژیم.']),
  w('anahtar', 'a-nah-TAR', 'مفتاح', 'کلیل', ['Anahtarımı kaybettim.', 'a-nah-ta-rı-MI kay-bet-TİM', 'أضعت مفتاحي.', 'کلیلەکەم ون کرد.']),
  w('buzdolabı', 'buz-do-la-BI', 'ثلاجة', 'ساردکەرەوە', ['Süt buzdolabında.', 'SÜT buz-do-la-bın-DA', 'الحليب في الثلاجة.', 'شیرەکە لە ساردکەرەوەکەیە.']),
  w('apartman', 'a-part-MAN', 'عمارة سكنية', 'ئەپارتمان', ['Apartmanımız yeni.', 'a-part-ma-nı-MIZ ye-Nİ', 'عمارتنا جديدة.', 'ئەپارتمانەکەمان نوێیە.']),
  w('kira', 'ki-RA', 'إيجار', 'کرێ', ['Kira çok pahalı.', 'ki-RA ÇOK pa-ha-LI', 'الإيجار غالٍ جداً.', 'کرێکە زۆر گرانە.']),
]);

const body = pack('body', 'a1', 'noun', [
  w('vücut', 'vü-DJUT', 'جسم', 'لەش', ['Vücudum ağrıyor.', 'vü-dju-DUM a-rı-YOR', 'جسمي يؤلمني.', 'لەشم ئازار دەدات.']),
  w('baş', 'BAŞ', 'رأس', 'سەر', ['Başım ağrıyor.', 'ba-ŞIM a-rı-YOR', 'رأسي يؤلمني.', 'سەرم ئازار دەدات.']),
  w('saç', 'SAÇ', 'شعر', 'قژ', ['Saçları çok uzun.', 'saç-la-RI ÇOK u-ZUN', 'شعرها طويل جداً.', 'قژی زۆر درێژە.']),
  w('göz', 'GÖZ', 'عين', 'چاو', ['Gözlerin çok güzel.', 'göz-le-RİN ÇOK gü-ZEL', 'عيناك جميلتان جداً.', 'چاوەکانت زۆر جوانن.']),
  w('kulak', 'ku-LAK', 'أذن', 'گوێ', ['Kulağım duymuyor.', 'ku-la-IM duy-mu-YOR', 'أذني لا تسمع.', 'گوێم نابیستێت.']),
  w('burun', 'bu-RUN', 'أنف', 'لووت', ['Burnum tıkalı.', 'bur-NUM tı-ka-LI', 'أنفي مسدود.', 'لووتم گیراوە.']),
  w('ağız', 'a-IZ', 'فم', 'دەم', ['Ağzını aç lütfen.', 'a-zı-NI AÇ lüt-FEN', 'افتح فمك من فضلك.', 'تکایە دەمت بکەرەوە.']),
  w('diş', 'DİŞ', 'سنّ', 'ددان', ['Dişim ağrıyor.', 'di-ŞİM a-rı-YOR', 'سنّي يؤلمني.', 'ددانم ئازار دەدات.']),
  w('dil', 'DİL', 'لسان / لغة', 'زمان', ['Türk dili çok güzel.', 'TÜRK di-Lİ ÇOK gü-ZEL', 'اللغة التركية جميلة جداً.', 'زمانی تورکی زۆر جوانە.']),
  w('el', 'EL', 'يد', 'دەست', ['Ellerini yıka.', 'el-le-ri-Nİ yı-KA', 'اغسل يديك.', 'دەستەکانت بشۆ.']),
  w('parmak', 'par-MAK', 'إصبع', 'پەنجە', ['Parmağımı kestim.', 'par-ma-ı-MI kes-TİM', 'جرحت إصبعي.', 'پەنجەم بڕی.']),
  w('kol', 'KOL', 'ذراع', 'باڵ', ['Kolum kırıldı.', 'ko-LUM kı-rıl-DI', 'انكسرت ذراعي.', 'باڵم شکا.']),
  w('ayak', 'a-YAK', 'قدم', 'پێ', ['Ayaklarım yoruldu.', 'a-yak-la-RIM yo-rul-DU', 'تعبت قدماي.', 'پێیەکانم ماندوو بوون.']),
  w('bacak', 'ba-DJAK', 'ساق', 'قاچ', ['Bacağım ağrıyor.', 'ba-dja-IM a-rı-YOR', 'ساقي تؤلمني.', 'قاچم ئازار دەدات.']),
  w('kalp', 'KALP', 'قلب', 'دڵ', ['Kalbim hızlı atıyor.', 'kal-BİM hız-LI a-tı-YOR', 'قلبي ينبض بسرعة.', 'دڵم بە خێرایی لێدەدات.']),
  w('karın', 'ka-RIN', 'بطن', 'سک', ['Karnım aç.', 'kar-NIM AÇ', 'بطني جائعة.', 'سکم برسییە.']),
  w('sırt', 'SIRT', 'ظهر', 'پشت', ['Sırtım ağrıyor.', 'sır-TIM a-rı-YOR', 'ظهري يؤلمني.', 'پشتم ئازار دەدات.']),
  {
    ...w('yüz', 'YÜZ', 'وجه', 'ڕوو', ['Yüzünü yıkadı.', 'yü-zü-NÜ yı-ka-DI', 'غسل وجهه.', 'ڕووی خۆی شۆرد.']),
    // Inline rather than in the senses overlay: `yüz` is a homonym of the
    // number "hundred", and an overlay keyed by the word would decorate both.
    senses: [
      sense('سطح، وجه الشيء', 'ڕوو',
        ['Suyun yüzünde yağ vardı.', 'su-YUN yü-zün-DE YAĞ var-DI',
          'كان على سطح الماء زيت.', 'ڕۆن لەسەر ڕووی ئاوەکە بوو.']),
    ],
  },
  w('boyun', 'bo-YUN', 'رقبة', 'مل', ['Boynum tutuldu.', 'boy-NUM tu-tul-DU', 'تشنجت رقبتي.', 'ملم گیرا.']),
]);

const animals = pack('animals', 'a1', 'noun', [
  w('hayvan', 'hay-VAN', 'حيوان', 'ئاژەڵ', ['Hayvanları çok severim.', 'hay-van-la-RI ÇOK se-ve-rim', 'أحب الحيوانات كثيراً.', 'ئاژەڵەکانم زۆر خۆشدەوێت.']),
  w('kedi', 'ke-Dİ', 'قطة', 'پشیلە', ['Kedim çok tembel.', 'ke-DİM ÇOK tem-BEL', 'قطتي كسولة جداً.', 'پشیلەکەم زۆر تەمبەڵە.']),
  w('köpek', 'kö-PEK', 'كلب', 'سەگ', ['Köpek havlıyor.', 'kö-PEK hav-lı-YOR', 'الكلب ينبح.', 'سەگەکە دەوەڕێت.']),
  w('kuş', 'KUŞ', 'طائر', 'باڵندە', ['Kuşlar uçuyor.', 'kuş-LAR u-çu-YOR', 'الطيور تطير.', 'باڵندەکان دەفڕن.']),
  w('at', 'AT', 'حصان', 'ئەسپ', ['At çok hızlı koşar.', 'AT ÇOK hız-LI ko-ŞAR', 'الحصان يركض بسرعة.', 'ئەسپ زۆر بە خێرایی ڕادەکات.']),
  w('inek', 'i-NEK', 'بقرة', 'مانگا', ['İnek süt verir.', 'i-NEK SÜT ve-RİR', 'البقرة تعطي الحليب.', 'مانگا شیر دەدات.']),
  w('koyun', 'ko-YUN', 'خروف', 'مەڕ', ['Koyunlar otluyor.', 'ko-yun-LAR ot-lu-YOR', 'الخراف ترعى.', 'مەڕەکان دەلەوەڕێن.']),
  w('aslan', 'as-LAN', 'أسد', 'شێر', ['Aslan ormanın kralıdır.', 'as-LAN or-ma-NIN kra-lı-DIR', 'الأسد ملك الغابة.', 'شێر پاشای دارستانە.']),
  w('kurt', 'KURT', 'ذئب', 'گورگ', ['Kurtlar sürü hâlinde yaşar.', 'kurt-LAR sü-RÜ hâ-lin-DE ya-ŞAR', 'الذئاب تعيش في قطعان.', 'گورگەکان بە کۆمەڵ دەژین.']),
  w('tavşan', 'tav-ŞAN', 'أرنب', 'کەروێشک', ['Tavşan havuç yer.', 'tav-ŞAN ha-VUÇ YER', 'الأرنب يأكل الجزر.', 'کەروێشک گێزەر دەخوات.']),
  w('arı', 'a-RI', 'نحلة', 'هەنگ', ['Arılar bal yapar.', 'a-rı-LAR BAL ya-PAR', 'النحل يصنع العسل.', 'هەنگەکان هەنگوین دروست دەکەن.']),
  w('kelebek', 'ke-le-BEK', 'فراشة', 'پەپوولە', ['Bahçede kelebek var.', 'bah-çe-DE ke-le-BEK VAR', 'يوجد فراشة في الحديقة.', 'لە باخچەکەدا پەپوولە هەیە.']),
  w('yılan', 'yı-LAN', 'أفعى', 'مار', ['Yılandan korkarım.', 'yı-lan-DAN kor-ka-RIM', 'أخاف من الأفاعي.', 'لە مار دەترسم.']),
]);

const clothing = pack('clothing', 'a1', 'noun', [
  w('giysi', 'giy-Sİ', 'ملابس', 'جلوبەرگ', ['Giysilerimi yıkadım.', 'giy-si-le-ri-Mİ yı-ka-DIM', 'غسلت ملابسي.', 'جلوبەرگەکانم شۆرد.']),
  w('gömlek', 'göm-LEK', 'قميص', 'کراس', ['Beyaz gömlek giydim.', 'be-YAZ göm-LEK giy-DİM', 'ارتديت قميصاً أبيض.', 'کراسێکی سپیم لەبەرکرد.']),
  w('pantolon', 'pan-to-LON', 'بنطال', 'پانتۆڵ', ['Bu pantolon bana dar.', 'BU pan-to-LON ba-NA DAR', 'هذا البنطال ضيق عليّ.', 'ئەم پانتۆڵە بۆ من تەسکە.']),
  w('elbise', 'el-bi-SE', 'فستان', 'کراسی ژنانە', ['Elbisen çok güzel.', 'el-bi-SEN ÇOK gü-ZEL', 'فستانك جميل جداً.', 'کراسەکەت زۆر جوانە.']),
  w('ceket', 'dje-KET', 'سترة / جاكيت', 'چاکەت', ['Ceketini giy, hava soğuk.', 'dje-ke-ti-Nİ GİY ha-VA so-UK', 'ارتدِ سترتك، الجو بارد.', 'چاکەتەکەت لەبەرکە، کەشوهەوا ساردە.']),
  w('palto', 'pal-TO', 'معطف', 'پاڵتۆ', ['Kışın palto giyerim.', 'kı-ŞIN pal-TO gi-ye-rim', 'أرتدي معطفاً في الشتاء.', 'لە زستاندا پاڵتۆ لەبەر دەکەم.']),
  w('ayakkabı', 'a-yak-ka-BI', 'حذاء', 'پێڵاو', ['Yeni ayakkabı aldım.', 'ye-Nİ a-yak-ka-BI al-DIM', 'اشتريت حذاءً جديداً.', 'پێڵاوی نوێم کڕی.']),
  w('çorap', 'ço-RAP', 'جورب', 'گۆرەوی', ['Çoraplarım delik.', 'ço-rap-la-RIM de-LİK', 'جواربي مثقوبة.', 'گۆرەوییەکانم کون بوون.']),
  w('şapka', 'şap-KA', 'قبّعة', 'کڵاو', ['Güneşte şapka tak.', 'gü-neş-TE şap-KA TAK', 'ضع قبعة تحت الشمس.', 'لە خۆردا کڵاو لەسەر بکە.']),
  w('kemer', 'ke-MER', 'حزام', 'قایش', ['Kemerini bağla.', 'ke-me-ri-Nİ ba-LA', 'اربط حزامك.', 'قایشەکەت ببەستە.']),
  w('gözlük', 'göz-LÜK', 'نظّارة', 'چاویلکە', ['Gözlüğümü unuttum.', 'göz-lü-ü-MÜ u-nut-TUM', 'نسيت نظارتي.', 'چاویلکەکەم لەبیر کرد.']),
  w('çanta', 'çan-TA', 'حقيبة', 'جانتا', ['Çantam nerede?', 'çan-TAM ne-re-DE', 'أين حقيبتي؟', 'جانتاکەم لە کوێیە؟']),
  w('eldiven', 'el-di-VEN', 'قفاز', 'دەستکێش', ['Eldivenlerini giy.', 'el-di-ven-le-ri-Nİ GİY', 'ارتدِ قفازيك.', 'دەستکێشەکانت بکە دەستت.']),
]);

const places = pack('places', 'a1', 'noun', [
  w('yer', 'YER', 'مكان', 'شوێن', ['Burası güzel bir yer.', 'bu-ra-SI gü-ZEL bir YER', 'هذا مكان جميل.', 'ئێرە شوێنێکی جوانە.']),
  w('şehir', 'şe-HİR', 'مدينة', 'شار', ['İstanbul büyük bir şehir.', 'is-tan-BUL bü-YÜK bir şe-HİR', 'إسطنبول مدينة كبيرة.', 'ئەستەنبوڵ شارێکی گەورەیە.']),
  w('köy', 'KÖY', 'قرية', 'گوند', ['Köyde hava temiz.', 'köy-DE ha-VA te-MİZ', 'الهواء نقيّ في القرية.', 'لە گوند هەوا پاکە.']),
  w('ülke', 'ül-KE', 'بلد / دولة', 'وڵات', ['Hangi ülkedensin?', 'han-Gİ ül-ke-den-SİN', 'من أي بلد أنت؟', 'خەڵکی کام وڵاتیت؟']),
  w('sokak', 'so-KAK', 'زقاق / شارع فرعي', 'کۆڵان', ['Sokakta çocuklar oynuyor.', 'so-kak-TA ço-djuk-LAR oy-nu-YOR', 'الأطفال يلعبون في الشارع.', 'لە کۆڵانەکە منداڵان یاری دەکەن.']),
  w('cadde', 'djad-DE', 'شارع رئيسي', 'شەقام', ['İstiklal Caddesi çok kalabalık.', 'is-tik-LAL djad-de-Sİ ÇOK ka-la-ba-LIK', 'شارع الاستقلال مزدحم جداً.', 'شەقامی ئیستیقلال زۆر قەرەباڵغە.']),
  w('meydan', 'mey-DAN', 'ساحة', 'گۆڕەپان', ['Meydanda buluşalım.', 'mey-dan-DA bu-lu-şa-LIM', 'لنلتقِ في الساحة.', 'لە گۆڕەپانەکە یەکتر ببینین.']),
  w('park', 'PARK', 'حديقة عامة', 'پارک', ['Parkta yürüyüş yaptık.', 'park-TA yü-rü-YÜŞ yap-TIK', 'تمشّينا في الحديقة.', 'لە پارکەکە پیاسەمان کرد.']),
  {
    ...w('pazar', 'pa-ZAR', 'سوق شعبي', 'بازاڕ', ['Pazardan sebze aldım.', 'pa-zar-DAN seb-ZE al-DIM', 'اشتريت خضاراً من السوق.', 'لە بازاڕەکە سەوزەم کڕی.']),
    // Kept separate from Pazar (Sunday) because Turkish capitalises weekday
    // names, so the two ARE distinguishable in writing — but they sound
    // identical, so each points at the other.
    note: b(
      'تُكتب بحرف صغير بمعنى السوق، وبحرف كبير Pazar بمعنى يوم الأحد. الأصل واحد: كان السوق يُقام يوم الأحد.',
      'بە پیتی بچووک واتە بازاڕ، بە پیتی گەورە Pazar واتە یەکشەممە. ڕەگەکە یەکە: بازاڕ ڕۆژی یەکشەممە دەکرا.',
    ),
  },
  w('market', 'mar-KET', 'بقالة / سوبرماركت', 'مارکێت', ['Markete gidiyorum.', 'mar-ke-TE gi-di-YO-rum', 'أنا ذاهب إلى البقالة.', 'دەچمە مارکێت.']),
  w('hastane', 'has-ta-NE', 'مستشفى', 'نەخۆشخانە', ['Hastane çok uzak.', 'has-ta-NE ÇOK u-ZAK', 'المستشفى بعيد جداً.', 'نەخۆشخانەکە زۆر دوورە.']),
  w('eczane', 'edj-za-NE', 'صيدلية', 'دەرمانخانە', ['En yakın eczane nerede?', 'EN ya-KIN edj-za-NE ne-re-DE', 'أين أقرب صيدلية؟', 'نزیکترین دەرمانخانە لە کوێیە؟']),
  w('okul', 'o-KUL', 'مدرسة', 'قوتابخانە', ['Okul saat sekizde başlıyor.', 'o-KUL sa-AT se-kiz-DE baş-lı-YOR', 'تبدأ المدرسة الساعة الثامنة.', 'قوتابخانە کاتژمێر هەشت دەست پێدەکات.']),
  w('cami', 'dja-Mİ', 'مسجد', 'مزگەوت', ['Sultanahmet Camii çok ünlü.', 'sul-ta-nah-MET dja-mi-İ ÇOK ün-LÜ', 'جامع السلطان أحمد مشهور جداً.', 'مزگەوتی سوڵتان ئەحمەد زۆر بەناوبانگە.']),
  w('lokanta', 'lo-kan-TA', 'مطعم', 'چێشتخانە', ['Bu lokanta çok iyi.', 'BU lo-kan-TA ÇOK i-Yİ', 'هذا المطعم جيد جداً.', 'ئەم چێشتخانەیە زۆر باشە.']),
  w('otel', 'o-TEL', 'فندق', 'هوتێل', ['Otelde kaldık.', 'o-tel-DE kal-DIK', 'أقمنا في الفندق.', 'لە هوتێلەکە ماینەوە.']),
  w('banka', 'ban-KA', 'بنك', 'بانک', ['Bankaya gitmem gerek.', 'ban-ka-YA git-MEM ge-REK', 'يجب أن أذهب إلى البنك.', 'پێویستە بچمە بانک.']),
  w('havalimanı', 'ha-va-li-ma-NI', 'مطار', 'فڕۆکەخانە', ['Havalimanına nasıl giderim?', 'ha-va-li-ma-nı-NA na-SIL gi-de-rim', 'كيف أذهب إلى المطار؟', 'چۆن بچمە فڕۆکەخانە؟']),
  w('deniz', 'de-NİZ', 'بحر', 'دەریا', ['Deniz bugün sakin.', 'de-NİZ bu-GÜN sa-KİN', 'البحر هادئ اليوم.', 'دەریا ئەمڕۆ ئارامە.']),
  w('dağ', 'DAA', 'جبل', 'چیا', ['Dağlar karla kaplı.', 'da-LAR kar-LA kap-LI', 'الجبال مغطاة بالثلج.', 'چیاکان بە بەفر داپۆشراون.']),
]);

const verbs = pack('verbs', 'a1', 'verb', [
  w('olmak', 'ol-MAK', 'أن يكون / يصير', 'بوون', ['Doktor olmak istiyorum.', 'dok-TOR ol-MAK is-ti-YO-rum', 'أريد أن أصبح طبيباً.', 'دەمەوێت ببمە پزیشک.']),
  w('yapmak', 'yap-MAK', 'يفعل / يصنع', 'کردن', ['Ne yapıyorsun?', 'NE ya-pı-yor-sun', 'ماذا تفعل؟', 'چی دەکەیت؟']),
  w('gitmek', 'git-MEK', 'يذهب', 'چوون', ['Okula gidiyorum.', 'o-ku-LA gi-di-YO-rum', 'أذهب إلى المدرسة.', 'دەچمە قوتابخانە.']),
  w('gelmek', 'gel-MEK', 'يأتي', 'هاتن', ['Yarın geliyorum.', 'ya-RIN ge-li-YO-rum', 'سآتي غداً.', 'سبەینێ دێم.']),
  w('almak', 'al-MAK', 'يأخذ / يشتري', 'وەرگرتن / کڕین', ['Ekmek aldım.', 'ek-MEK al-DIM', 'اشتريت خبزاً.', 'نانم کڕی.']),
  w('vermek', 'ver-MEK', 'يعطي', 'دان', ['Bana kalem ver.', 'ba-NA ka-LEM VER', 'أعطني قلماً.', 'پێنووسێکم بدەرێ.']),
  w('görmek', 'gör-MEK', 'يرى', 'بینین', ['Onu dün gördüm.', 'o-NU DÜN gör-DÜM', 'رأيته أمس.', 'دوێنێ بینیم.']),
  w('bakmak', 'bak-MAK', 'ينظر', 'سەیرکردن', ['Pencereden dışarı bak.', 'pen-dje-re-DEN dı-şa-RI BAK', 'انظر خارجاً من النافذة.', 'لە پەنجەرەکەوە سەیری دەرەوە بکە.']),
  w('bilmek', 'bil-MEK', 'يعرف', 'زانین', ['Cevabı biliyorum.', 'dje-va-BI bi-li-YO-rum', 'أعرف الجواب.', 'وەڵامەکە دەزانم.']),
  w('istemek', 'is-te-MEK', 'يريد', 'ویستن', ['Çay istiyorum.', 'ÇAY is-ti-YO-rum', 'أريد شاياً.', 'چام دەوێت.']),
  w('sevmek', 'sev-MEK', 'يحب', 'خۆشویستن', ['Seni seviyorum.', 'se-Nİ se-vi-YO-rum', 'أحبك.', 'خۆشمدەوێیت.']),
  {
    ...w('yemek', 'ye-MEK', 'يأكل', 'خواردن', ['Kahvaltı yedim.', 'kah-val-TI ye-DİM', 'تناولت الفطور.', 'نانی بەیانیم خوارد.']),
    // Inline, not in the verb-pattern overlay: `yemek` is a homonym of the
    // noun "food", and an overlay keyed by the word would decorate both.
    note: b(
      'يأخذ المفعول مباشرة. ⚠️ نفس الشكل للاسم «الطعام» وللفعل «يأكل» — والسياق وحده يفصل: «yemek yemek» = أكل الطعام، وهي صحيحة تماماً رغم غرابتها.',
      '⚠️ هەمان شێوە بۆ ناو و کردار: «yemek yemek».',
    ),
  },
  w('içmek', 'iç-MEK', 'يشرب', 'خواردنەوە', ['Su içiyorum.', 'SU i-çi-YO-rum', 'أشرب الماء.', 'ئاو دەخۆمەوە.']),
  w('okumak', 'o-ku-MAK', 'يقرأ / يدرس', 'خوێندن', ['Kitap okuyorum.', 'ki-TAP o-ku-YO-rum', 'أقرأ كتاباً.', 'کتێب دەخوێنمەوە.']),
  w('yazmak', 'yaz-MAK', 'يكتب', 'نووسین', ['Mektup yazdım.', 'mek-TUP yaz-DIM', 'كتبت رسالة.', 'نامەیەکم نووسی.']),
  w('konuşmak', 'ko-nuş-MAK', 'يتكلّم', 'قسەکردن', ['Türkçe konuşuyorum.', 'türk-ÇE ko-nu-şu-YO-rum', 'أتكلم التركية.', 'تورکی قسە دەکەم.']),
  w('dinlemek', 'din-le-MEK', 'يستمع', 'گوێگرتن', ['Müzik dinliyorum.', 'mü-ZİK din-li-YO-rum', 'أستمع إلى الموسيقى.', 'گوێ لە مۆسیقا دەگرم.']),
  w('anlamak', 'an-la-MAK', 'يفهم', 'تێگەیشتن', ['Anlamadım, tekrar eder misiniz?', 'an-la-ma-DIM tek-RAR e-DER mi-si-niz', 'لم أفهم، هل تعيد؟', 'تێنەگەیشتم، دووبارەی دەکەیتەوە؟']),
  w('söylemek', 'söy-le-MEK', 'يقول', 'گوتن', ['Ne söyledin?', 'NE söy-le-din', 'ماذا قلت؟', 'چیت گوت؟']),
  w('çalışmak', 'ça-lış-MAK', 'يعمل / يدرس بجدّ', 'کارکردن / خوێندن', ['Bankada çalışıyorum.', 'ban-ka-DA ça-lı-şı-YO-rum', 'أعمل في البنك.', 'لە بانکدا کار دەکەم.']),
  w('oturmak', 'o-tur-MAK', 'يجلس / يسكن', 'دانیشتن / ژیان', ['Ankara’da oturuyorum.', 'an-ka-RA-da o-tu-ru-YO-rum', 'أسكن في أنقرة.', 'لە ئەنقەرە دەژیم.']),
  w('kalkmak', 'kalk-MAK', 'ينهض / يستيقظ', 'هەستان', ['Sabah yedide kalkıyorum.', 'sa-BAH ye-di-DE kal-kı-YO-rum', 'أستيقظ الساعة السابعة صباحاً.', 'بەیانی حەوت هەڵدەستم.']),
  w('uyumak', 'u-yu-MAK', 'ينام', 'خەوتن', ['Erken uyudum.', 'er-KEN u-yu-DUM', 'نمت مبكراً.', 'زوو خەوتم.']),
  w('yürümek', 'yü-rü-MEK', 'يمشي', 'ڕۆیشتن', ['Her gün yürüyorum.', 'her GÜN yü-rü-YO-rum', 'أمشي كل يوم.', 'هەموو ڕۆژێک پیاسە دەکەم.']),
  w('koşmak', 'koş-MAK', 'يركض', 'ڕاکردن', ['Çocuk koşuyor.', 'ço-DJUK ko-şu-YOR', 'الطفل يركض.', 'منداڵەکە ڕادەکات.']),
  w('açmak', 'aç-MAK', 'يفتح', 'کردنەوە', ['Kapıyı açtım.', 'ka-pı-YI aç-TIM', 'فتحت الباب.', 'دەرگاکەم کردەوە.']),
  w('kapatmak', 'ka-pat-MAK', 'يغلق', 'داخستن', ['Işığı kapat.', 'ı-şı-I ka-PAT', 'أطفئ الضوء.', 'ڕووناکییەکە بکوژێنەوە.']),
  w('beklemek', 'bek-le-MEK', 'ينتظر', 'چاوەڕوانکردن', ['Beni bekle.', 'be-Nİ bek-LE', 'انتظرني.', 'چاوەڕێم بکە.']),
  w('başlamak', 'baş-la-MAK', 'يبدأ', 'دەستپێکردن', ['Ders başlıyor.', 'DERS baş-lı-YOR', 'يبدأ الدرس.', 'وانەکە دەست پێدەکات.']),
  w('bitirmek', 'bi-tir-MEK', 'يُنهي', 'تەواوکردن', ['Ödevimi bitirdim.', 'ö-de-vi-Mİ bi-tir-DİM', 'أنهيت واجبي.', 'ئەرکەکەم تەواو کرد.']),
  w('yaşamak', 'ya-şa-MAK', 'يعيش', 'ژیان', ['Türkiye’de yaşıyorum.', 'tür-ki-YE-de ya-şı-YO-rum', 'أعيش في تركيا.', 'لە تورکیا دەژیم.']),
  w('bulmak', 'bul-MAK', 'يجد', 'دۆزینەوە', ['Anahtarımı buldum.', 'a-nah-ta-rı-MI bul-DUM', 'وجدت مفتاحي.', 'کلیلەکەم دۆزییەوە.']),
  w('getirmek', 'ge-tir-MEK', 'يُحضر', 'هێنان', ['Bana su getir.', 'ba-NA SU ge-TİR', 'أحضر لي ماءً.', 'ئاوم بۆ بێنە.']),
  w('sormak', 'sor-MAK', 'يسأل', 'پرسین', ['Bir şey sorabilir miyim?', 'bir ŞEY so-ra-bi-LİR mi-yim', 'هل يمكنني أن أسأل شيئاً؟', 'دەتوانم شتێک بپرسم؟']),
  w('durmak', 'dur-MAK', 'يقف / يتوقف', 'وەستان', ['Otobüs burada duruyor.', 'o-to-BÜS bu-ra-DA du-ru-YOR', 'الحافلة تقف هنا.', 'پاسەکە لێرە دەوەستێت.']),
]);

const adjectives = pack('adjectives', 'a1', 'adjective', [
  w('büyük', 'bü-YÜK', 'كبير', 'گەورە', ['Büyük bir ev.', 'bü-YÜK bir EV', 'بيت كبير.', 'ماڵێکی گەورە.']),
  w('küçük', 'kü-ÇÜK', 'صغير', 'بچووک', ['Küçük bir çanta.', 'kü-ÇÜK bir çan-TA', 'حقيبة صغيرة.', 'جانتایەکی بچووک.']),
  w('yeni', 'ye-Nİ', 'جديد', 'نوێ', ['Yeni bir telefon aldım.', 'ye-Nİ bir te-le-FON al-DIM', 'اشتريت هاتفاً جديداً.', 'تەلەفۆنێکی نوێم کڕی.']),
  w('eski', 'es-Kİ', 'قديم', 'کۆن', ['Eski bir arkadaşım.', 'es-Kİ bir ar-ka-da-ŞIM', 'صديق قديم لي.', 'هاوڕێیەکی کۆنمە.']),
  w('iyi', 'i-Yİ', 'جيد', 'باش', ['Bu çok iyi.', 'BU ÇOK i-Yİ', 'هذا جيد جداً.', 'ئەمە زۆر باشە.']),
  w('kötü', 'kö-TÜ', 'سيّئ', 'خراپ', ['Hava çok kötü.', 'ha-VA ÇOK kö-TÜ', 'الطقس سيّئ جداً.', 'کەشوهەوا زۆر خراپە.']),
  w('güzel', 'gü-ZEL', 'جميل', 'جوان', ['Çok güzel bir şehir.', 'ÇOK gü-ZEL bir şe-HİR', 'مدينة جميلة جداً.', 'شارێکی زۆر جوان.']),
  w('uzun', 'u-ZUN', 'طويل', 'درێژ', ['Uzun bir yol.', 'u-ZUN bir YOL', 'طريق طويل.', 'ڕێگایەکی درێژ.']),
  w('kısa', 'kı-SA', 'قصير', 'کورت', ['Kısa bir hikâye.', 'kı-SA bir hi-kâ-YE', 'قصة قصيرة.', 'چیرۆکێکی کورت.']),
  w('kolay', 'ko-LAY', 'سهل', 'ئاسان', ['Türkçe kolay mı?', 'türk-ÇE ko-LAY mı', 'هل التركية سهلة؟', 'تورکی ئاسانە؟']),
  w('zor', 'ZOR', 'صعب', 'قورس', ['Bu soru çok zor.', 'BU so-RU ÇOK ZOR', 'هذا السؤال صعب جداً.', 'ئەم پرسیارە زۆر قورسە.']),
  w('sıcak', 'sı-DJAK', 'حارّ', 'گەرم', ['Çay çok sıcak.', 'ÇAY ÇOK sı-DJAK', 'الشاي حارّ جداً.', 'چاکە زۆر گەرمە.']),
  w('soğuk', 'so-UK', 'بارد', 'سارد', ['Bugün hava soğuk.', 'bu-GÜN ha-VA so-UK', 'الجو بارد اليوم.', 'ئەمڕۆ کەشوهەوا ساردە.']),
  w('hızlı', 'hız-LI', 'سريع', 'خێرا', ['Çok hızlı konuşuyorsun.', 'ÇOK hız-LI ko-nu-şu-yor-sun', 'أنت تتكلم بسرعة كبيرة.', 'زۆر بە خێرایی قسە دەکەیت.']),
  w('yavaş', 'ya-VAŞ', 'بطيء', 'هێواش', ['Lütfen yavaş konuşun.', 'lüt-FEN ya-VAŞ ko-nu-şun', 'من فضلك تكلم ببطء.', 'تکایە هێواش قسە بکە.']),
  w('temiz', 'te-MİZ', 'نظيف', 'پاک', ['Oda çok temiz.', 'o-DA ÇOK te-MİZ', 'الغرفة نظيفة جداً.', 'ژوورەکە زۆر پاکە.']),
  w('kirli', 'kir-Lİ', 'متّسخ', 'پیس', ['Elbisen kirli.', 'el-bi-SEN kir-Lİ', 'ملابسك متسخة.', 'کراسەکەت پیسە.']),
  w('dolu', 'do-LU', 'ممتلئ', 'پڕ', ['Otobüs dolu.', 'o-to-BÜS do-LU', 'الحافلة ممتلئة.', 'پاسەکە پڕە.']),
  w('boş', 'BOŞ', 'فارغ', 'بەتاڵ', ['Bardak boş.', 'bar-DAK BOŞ', 'الكوب فارغ.', 'پەرداخەکە بەتاڵە.']),
  w('açık', 'a-ÇIK', 'مفتوح / فاتح (لون)', 'کراوە / ڕووناک', ['Market açık mı?', 'mar-KET a-ÇIK mı', 'هل البقالة مفتوحة؟', 'مارکێتەکە کراوەیە؟']),
  w('kapalı', 'ka-pa-LI', 'مغلق', 'داخراو', ['Dükkân kapalı.', 'dük-KÂN ka-pa-LI', 'المحلّ مغلق.', 'دوکانەکە داخراوە.']),
  w('mutlu', 'mut-LU', 'سعيد', 'دڵخۆش', ['Bugün çok mutluyum.', 'bu-GÜN ÇOK mut-lu-YUM', 'أنا سعيد جداً اليوم.', 'ئەمڕۆ زۆر دڵخۆشم.']),
  w('üzgün', 'üz-GÜN', 'حزين', 'خەمگین', ['Neden üzgünsün?', 'ne-DEN üz-gün-SÜN', 'لماذا أنت حزين؟', 'بۆچی خەمگینیت؟']),
  w('yorgun', 'yor-GUN', 'متعب', 'ماندوو', ['Çok yorgunum.', 'ÇOK yor-gu-NUM', 'أنا متعب جداً.', 'زۆر ماندووم.']),
  w('aç', 'AÇ', 'جائع', 'برسی', ['Açım, yemek yiyelim.', 'a-ÇIM ye-MEK yi-ye-LİM', 'أنا جائع، لنأكل.', 'برسیمە، با نان بخۆین.']),
  w('tok', 'TOK', 'شبعان', 'تێر', ['Tokum, teşekkürler.', 'to-KUM te-şek-kür-LER', 'أنا شبعان، شكراً.', 'تێرم، سوپاس.']),
  w('hasta', 'has-TA', 'مريض', 'نەخۆش', ['Bugün hastayım.', 'bu-GÜN has-ta-YIM', 'أنا مريض اليوم.', 'ئەمڕۆ نەخۆشم.']),
  w('ucuz', 'u-DJUZ', 'رخيص', 'هەرزان', ['Bu çok ucuz.', 'BU ÇOK u-DJUZ', 'هذا رخيص جداً.', 'ئەمە زۆر هەرزانە.']),
  w('pahalı', 'pa-ha-LI', 'غالٍ', 'گران', ['Çok pahalı!', 'ÇOK pa-ha-LI', 'غالٍ جداً!', 'زۆر گرانە!']),
  w('yakın', 'ya-KIN', 'قريب', 'نزیک', ['Ev okula yakın.', 'EV o-ku-LA ya-KIN', 'البيت قريب من المدرسة.', 'ماڵەکە نزیکە لە قوتابخانە.']),
  w('uzak', 'u-ZAK', 'بعيد', 'دوور', ['Havalimanı uzak mı?', 'ha-va-li-ma-NI u-ZAK mı', 'هل المطار بعيد؟', 'فڕۆکەخانە دوورە؟']),
]);

const nouns = pack('nouns', 'a1', 'noun', [
  w('kitap', 'ki-TAP', 'كتاب', 'کتێب', ['Bu kitap çok güzel.', 'BU ki-TAP ÇOK gü-ZEL', 'هذا الكتاب جميل جداً.', 'ئەم کتێبە زۆر جوانە.']),
  w('kalem', 'ka-LEM', 'قلم', 'پێنووس', ['Kalemin var mı?', 'ka-le-MİN var MI', 'هل لديك قلم؟', 'پێنووست هەیە؟']),
  w('defter', 'def-TER', 'دفتر', 'دەفتەر', ['Defterime yazdım.', 'def-te-ri-ME yaz-DIM', 'كتبت في دفتري.', 'لە دەفتەرەکەمدا نووسیم.']),
  w('kâğıt', 'kâ-IT', 'ورقة', 'کاغەز', ['Bir kâğıt ver.', 'bir kâ-IT VER', 'أعطني ورقة.', 'کاغەزێکم بدەرێ.']),
  w('telefon', 'te-le-FON', 'هاتف', 'تەلەفۆن', ['Telefonum bozuldu.', 'te-le-fo-NUM bo-zul-DU', 'تعطّل هاتفي.', 'تەلەفۆنەکەم خراپ بوو.']),
  w('para', 'pa-RA', 'نقود / مال', 'پارە', ['Param yok.', 'pa-RAM YOK', 'ليس معي نقود.', 'پارەم نییە.']),
  w('araba', 'a-ra-BA', 'سيارة', 'ئۆتۆمبێل', ['Arabam eski.', 'a-ra-BAM es-Kİ', 'سيارتي قديمة.', 'ئۆتۆمبێلەکەم کۆنە.']),
  w('yol', 'YOL', 'طريق', 'ڕێگا', ['Yol çok uzun.', 'YOL ÇOK u-ZUN', 'الطريق طويل جداً.', 'ڕێگاکە زۆر درێژە.']),
  w('iş', 'İŞ', 'عمل / شغل', 'کار', ['İşim çok var.', 'i-ŞİM ÇOK VAR', 'لديّ عمل كثير.', 'کارم زۆر هەیە.']),
  w('kelime', 'ke-li-ME', 'كلمة', 'وشە', ['Yeni kelimeler öğreniyorum.', 'ye-Nİ ke-li-me-LER öö-re-ni-YO-rum', 'أتعلم كلمات جديدة.', 'وشەی نوێ فێر دەبم.']),
  w('cümle', 'djüm-LE', 'جملة', 'ڕستە', ['Bir cümle kur.', 'bir djüm-LE KUR', 'كوّن جملة.', 'ڕستەیەک دروست بکە.']),
  w('soru', 'so-RU', 'سؤال', 'پرسیار', ['Sorun var mı?', 'so-RUN var MI', 'هل لديك سؤال؟', 'پرسیارت هەیە؟']),
  w('cevap', 'dje-VAP', 'جواب', 'وەڵام', ['Cevabı bilmiyorum.', 'dje-va-BI bil-mi-YO-rum', 'لا أعرف الجواب.', 'وەڵامەکە نازانم.']),
  w('ders', 'DERS', 'درس', 'وانە', ['Ders saat üçte.', 'DERS sa-AT üç-TE', 'الدرس الساعة الثالثة.', 'وانەکە کاتژمێر سێیە.']),
  w('hayat', 'ha-YAT', 'حياة', 'ژیان', ['Hayat güzel.', 'ha-YAT gü-ZEL', 'الحياة جميلة.', 'ژیان جوانە.']),
  w('dünya', 'dün-YA', 'عالم / دنيا', 'جیهان', ['Dünya çok büyük.', 'dün-YA ÇOK bü-YÜK', 'العالم كبير جداً.', 'جیهان زۆر گەورەیە.']),
  w('şey', 'ŞEY', 'شيء', 'شت', ['Bir şey söyle.', 'bir ŞEY söy-LE', 'قل شيئاً.', 'شتێک بڵێ.']),
]);

export const A1_VOCABULARY: VocabItem[] = [
  ...greetings, ...family, ...people, ...numberWords, ...colors, ...days, ...months, ...time,
  ...food, ...drinks, ...house, ...body, ...animals, ...clothing, ...places,
  ...verbs, ...adjectives, ...nouns,
];
